### ISSUE TITLE
[Bug]程序位于后台时标题不会刷新

### ISSUE THREAD

**Issue by AsterisMono** [mydockfinder/mydockfinder#109]
如题，当程序位于后台时，程序更改自身的标题，鼠标悬停在Dock栏出现的Title提示不会改变，需要手动将窗口前台一次才会同步。
此问题经常出现在需要不断改变窗口标题的程序（例如，开着音乐播放器的浏览器）。
![image](https://user-images.githubusercontent.com/54884471/123415938-85de4f00-d5e8-11eb-90b5-a6e50607f8d4.png)

**Comment by mydockfinder** [comment]
嗯 窗口的标题我还真没有加刷新，就是最小化的时候检测一次标题后面就不检测了，回来我加个检测




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月25日(星期五) 晚上7:07
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder] [Bug]程序位于后台时标题不会刷新 (#109)





 
如题，当程序位于后台时，程序更改自身的标题，鼠标悬停在Dock栏出现的Title提示不会改变，需要手动将窗口前台一次才会同步。
 此问题经常出现在需要不断改变窗口标题的程序（例如，开着音乐播放器的浏览器）。
