### ISSUE TITLE
窗口最大化沉浸模式的取色有两种情况

### ISSUE THREAD

**Issue by Miuzarte** [mydockfinder/mydockfinder#112]
有时候是这样
![NT)4%1Z}MLVX1407OF_VEWP](https://user-images.githubusercontent.com/66856838/123510264-05cded00-d6ad-11eb-8a12-eb41d79b4099.png)
有时候却是这样
![61{OQ5Q6097~FAEV%L9FSO4](https://user-images.githubusercontent.com/66856838/123510265-06ff1a00-d6ad-11eb-8359-482b617d5eb3.png)
这个是正常情况
![BEJJ~8SQC4VI6MN60QRH(WP](https://user-images.githubusercontent.com/66856838/123510267-0797b080-d6ad-11eb-932f-9bd079071196.png)

**Comment by mydockfinder** [comment]
win10新版沉浸模式就好了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月26日(星期六) 晚上6:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder] 窗口最大化沉浸模式的取色有两种情况 (#112)





 
有时候是这样
 
 有时候却是这样
 
 这个是正常情况
