### ISSUE TITLE
Dock激活条只能单击触发吗？

### ISSUE THREAD

**Issue by M-Cosmosss** [mydockfinder/mydockfinder#115]
主要是为了好看开启的激活条，能否像不开启激活条那样通过鼠标下移就能唤起dock呢？

**Comment by mydockfinder** [comment]
后面会加上悬停一段时间以后自动激活




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月27日(星期天) 晚上8:40
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder] Dock激活条只能单击触发吗？ (#115)





 
主要是为了好看开启的激活条，能否像不开启激活条那样通过鼠标下移就能唤起dock呢？
