### ISSUE TITLE
Dock 栏出现一个消除不掉的指示器（小黑点）

### ISSUE THREAD

**Issue by ghost** [mydockfinder/mydockfinder#121]
系统：微软视窗 10 版本 21H1
版本：5.9.9.86
显卡：英特尔 高清图形 610
处理器：英特尔 奔腾 G4560
其他：计算机中安装了 MacType 字体渲染软件版本 2021

### 问题1：多出一个小黑点
如图所示：Dock 栏会出现一个消除不掉的指示器（小黑点），如果启用“使用GPU合成渲染Dock图标”就正常。
![动画.gif](https://i.loli.net/2021/06/30/AL5xtwd36S2Iq9T.gif)

### 问题2：程序崩溃
另外如果程序崩溃能不能自动重启并生成日志？每天都会提示程序崩溃一次，也不知道是什么原因，想反馈也没办法反馈😂

**Comment by mydockfinder** [comment]
1、gpu合成是win10才可以用的，win10以下没有，而且以后的版本我也不打算在旧系统里面加功能了，能勾选就勾选gpu，那个黑点是旧系统才会有的bug
2、你说的是睡眠唤醒以后崩溃的吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月30日(星期三) 中午11:22
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder] Dock 栏出现一个消除不掉的指示器（小黑点） (#121)





 
系统：微软视窗 10 版本 21H1
 版本：5.9.9.86
 显卡：英特尔 高清图形 610
 处理器：英特尔 奔腾 G4560
 其他：计算机中安装了 MacType 字体渲染软件版本 2021
 
问题1：多出一个小黑点
 
如图所示：Dock 栏会出现一个消除不掉的指示器（小黑点），如果启用“使用GPU合成渲染Dock图标”就正常。
 
 
问题2：程序崩溃
 
另外如果程序崩溃能不能自动重启并生成日志？每天都会提示程序崩溃一次，也不知道是什么原因，想反馈也没办法反馈😂

**Comment by ghost** [comment]
> 
> 1、gpu合成是win10才可以用的，win10以下没有，而且以后的版本我也不打算在旧系统里面加功能了，能勾选就勾选gpu，那个黑点是旧系统才会有的bug 2、你说的是睡眠唤醒以后崩溃的吧
> […](#)

感谢作者答复，我的系统是这个：
```
版本	Windows 10 专业版
版本号	21H1
安装日期	‎2021/‎6/‎25
操作系统内部版本	19043.928
体验	Windows Feature Experience Pack 120.2212.551.0
```

崩溃是在正常使用电脑的时候崩溃，我的是台式机很少睡眠。希望能崩溃后自动重启 Dock。

**Comment by mydockfinder** [comment]
崩溃不是有提示 已崩溃是否重启吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月30日(星期三) 中午11:28
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] Dock 栏出现一个消除不掉的指示器（小黑点） (#121)





  
1、gpu合成是win10才可以用的，win10以下没有，而且以后的版本我也不打算在旧系统里面加功能了，能勾选就勾选gpu，那个黑点是旧系统才会有的bug 2、你说的是睡眠唤醒以后崩溃的吧
 …
  
感谢作者答复，我的系统是这个：
 版本	Windows 10 专业版 版本号	21H1 安装日期	‎2021/‎6/‎25 操作系统内部版本	19043.928 体验	Windows Feature Experience Pack 120.2212.551.0  
崩溃是在正常使用电脑的时候崩溃，我的是台式机很少睡眠。希望能崩溃后自动重启 Dock。

**Comment by ghost** [comment]
> 
> 崩溃不是有提示 已崩溃是否重启吗
> […](#)

是的，不过一般电脑是在工作，崩溃了那个提示框可能被工作的软件挡住，有时候也没空去点重启，希望能自动重启。

**Comment by mydockfinder** [comment]
我之前加过崩溃自动重启，主要有一次遇到过启动就崩溃的，他就一直无限重启了，而且任务管理器也关不了，因为鼠标刚点上他就没了自动重启了，所以后来我就取消了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月30日(星期三) 中午11:37
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] Dock 栏出现一个消除不掉的指示器（小黑点） (#121)





  
崩溃不是有提示 已崩溃是否重启吗
 …
  
是的，不过一般电脑是在工作，崩溃了那个提示框可能被工作的软件挡住，有时候也没空去点重启，希望能自动重启。
 
&mdash;

**Comment by ghost** [comment]
> 
> 我之前加过崩溃自动重启，主要有一次遇到过启动就崩溃的，他就一直无限重启了，而且任务管理器也关不了，因为鼠标刚点上他就没了自动重启了，所以后来我就取消了
> […](#)

好吧 😹

**Comment by ghost** [comment]
谢谢作者大大的耐心解答
