### ISSUE TITLE
遇到几次内存溢出的现象

### ISSUE THREAD

**Issue by smdx** [mydockfinder/mydockfinder#122]
在dock点击最小化的app返回时出现过好几次内存溢出的现象（aida64副屏能看到内存突然变成100%使用率），然后桌面什么的都没反应了鼠标能极其缓慢的动几下。

Win10Pro-19042.1052、MyDockFinder v5.9.9.86（旧版本也遇到过这个问题）
![IMG_20210629_170914](https://user-images.githubusercontent.com/9279217/123900702-22fc0780-d99c-11eb-9f15-716732dae0ac.jpg)

**Comment by mydockfinder** [comment]
是开启了 显示新运行图标分隔符的bug，下次修复可以先取消勾选 新运行图标分隔符




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月30日(星期三) 中午12:12
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder] 遇到几次内存溢出的现象 (#122)





 
在dock点击最小化的app返回时出现过好几次内存溢出的现象（aida64副屏能看到内存突然变成100%使用率），然后桌面什么的都没反应了鼠标能极其缓慢的动几下。
 
Win10Pro-19042.1052、MyDockFinder v5.9.9.86（旧版本也遇到过这个问题）

**Comment by smdx** [comment]
好的，谢谢。
