### ISSUE TITLE
桌面情况下，dock不显示，只有打开某个程序全屏后，鼠标滑动到底部dock才会显示

### ISSUE THREAD

**Issue by Androidkobe** [mydockfinder/mydockfinder#126]
V5.9.9.86
1、修复上一版本dock隐藏后偶尔不显示问题（待实验）
这个版本貌似没有修复这个问题

**Comment by mydockfinder** [comment]
是的&nbsp; 不过窗口最大化以后取消最大化，让dock在隐藏显示一次就出来了，这个新的渲染结构没玩明白




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月1日(星期四) 上午10:23
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder] 桌面情况下，dock不显示，只有打开某个程序全屏后，鼠标滑动到底部dock才会显示 (#126)





 
V5.9.9.86
 1、修复上一版本dock隐藏后偶尔不显示问题（待实验）
 这个版本貌似没有修复这个问题
