### ISSUE TITLE
更新后，如果程序关闭后到托盘，dock上图标不消失

### ISSUE THREAD

**Issue by heloook** [mydockfinder/mydockfinder#136]
![image](https://user-images.githubusercontent.com/27837566/124383026-f5e18900-dcfc-11eb-8708-3fe032766612.png)
这两个程序窗口均被我关闭，但在dock上的图标未消失。
我发现这两个程序和其他表现正常软件的不同点是：在托盘上能找到它们。
上一个版本没有这个问题。

希望作者大大解决一下。

**Comment by mydockfinder** [comment]
我是真的受不了了，之前不显示让我显示，这回显示又让我不显示




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月4日(星期天) 晚上7:26
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder] 更新后，如果程序关闭后到托盘，dock上图标不消失 (#136)





 

 这两个程序窗口均被我关闭，但在dock上的图标未消失。
 我发现这两个程序和其他表现正常软件的不同点是：在托盘上能找到它们。
 上一个版本没有这个问题。
 
希望作者大大解决一下。

**Comment by heloook** [comment]
之前我提的不是关于显示的问题啊

**Comment by heloook** [comment]
可能是别的用户提的吧。
我提的是关于消失时间的问题。
隐藏到托盘上的窗口当然要在dock上也隐藏啦。

**Comment by heloook** [comment]
如果是其他用户想显示，拜托作者弄一个设置吧，想显示的显示，不想显示的不显示
拜托啦 拜托啦

**Comment by smdx** [comment]
> 我是真的受不了了，之前不显示让我显示，这回显示又让我不显示[…](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mydockfinder/mydockfinder" ***@***.***&gt;; 发送时间:&nbsp;2021年7月4日(星期天) 晚上7:26 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[mydockfinder/mydockfinder] 更新后，如果程序关闭后到托盘，dock上图标不消失 (#136) 这两个程序窗口均被我关闭，但在dock上的图标未消失。 我发现这两个程序和其他表现正常软件的不同点是：在托盘上能找到它们。 上一个版本没有这个问题。 希望作者大大解决一下。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

哎...作者你好，记得本来是关闭到任务栏的app图标在dock一直显示的，到后来5.9.9.8后面的版本才改成了关闭到任务栏就不显示（这样非常好），今天这个版本又改回去了。如果众口难调的话可以加个设置选项选择不同的方式。麻烦你了，谢谢。

**Comment by heloook** [comment]
完美解决！👍👍👍
