### ISSUE TITLE
再上报两个小问题，作者大大一定要解决啊

### ISSUE THREAD

**Issue by heloook** [mydockfinder/mydockfinder#137]
（1）当选择隐藏wifi和蓝牙图标后，
![image](https://user-images.githubusercontent.com/27837566/124383782-e82e0280-dd00-11eb-8d59-1652e9b25f8a.png)

myfinder右上角的控制台（是叫控制台吗？），里面的蓝牙可以点击，但是wifi却不能点击
![image](https://user-images.githubusercontent.com/27837566/124383738-a604c100-dd00-11eb-938d-915f6c1616b9.png)

（2）更新后，设置窗口一旦聚焦（用鼠标点一下）就自动透明了。。。
![image](https://user-images.githubusercontent.com/27837566/124383851-3b07ba00-dd01-11eb-93d9-e667ebba836b.png)

**Comment by heloook** [comment]
我是很喜欢才提建议的！

**Comment by heloook** [comment]
第二个关于透明度的问题，在我重启电脑之后就没有这个问题了。

**Comment by heloook** [comment]
第一个问题我再补充描述一下：当开启finder显示wifi时，控制台中的wifi按钮可以正常点击。但是关闭显示wifi后，控制台中的wifi按钮就不能正常点击了。

**Comment by mydockfinder** [comment]
后面设置要重新改的，那个选项应该是网络图标 而不是仅限于WiFi




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月5日(星期一) 下午5:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] 再上报两个小问题，作者大大一定要解决啊 (#137)





 
第一个问题我再补充描述一下：当开启finder显示wifi时，控制台中的wifi按钮可以正常点击。但是关闭显示wifi后，控制台中的wifi按钮就不能正常点击了。
 
&mdash;

**Comment by heloook** [comment]
好的，期待。

奇怪的地方在于，如果选中“在访达中显示wifi图标”，那里就是正常的。

**这几天下来，我个人的使用感受**：

finder右上角的功能我挺喜欢的，网速啊、托盘啊、监控啊、搜索啊，很好用，希望其他的（比如作者刚提到的”设置“）也能更完美一些。

finder左上角的功能我倒不怎么在意，很少用。只要没有点不动的按钮显示出来就行。

dock是我最喜欢的部分。我最希望改善的地方在于：图标消失速度，以及不显示"隐藏到托盘中的程序“的图标（或者提供个性化设置）。

**Comment by mydockfinder** [comment]
谢谢，那个WiFi我自己测试了一下确实有问题，关闭就不正常了，回来修复一下，dock图标消失速度已经比mac快了，mac还慢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月5日(星期一) 晚上6:32
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] 再上报两个小问题，作者大大一定要解决啊 (#137)





 
好的，期待。
 
奇怪的地方在于，如果选中“在访达中显示wifi图标”，那里就是正常的。
 
这几天下来，我个人的使用感受：
 
finder右上角的功能我挺喜欢的，网速啊、托盘啊、监控啊、搜索啊，很好用，希望其他的（比如作者刚提到的”设置“）也能更完美一些。
 
finder左上角的功能我倒不怎么在意，很少用。只要没有点不动的按钮显示出来就行。
 
dock是我最喜欢的部分。我最希望改善的地方在于：图标消失速度，以及不显示"隐藏到托盘中的程序“的图标（或者提供个性化设置）。

**Comment by heloook** [comment]
嗯，多谢！

**Comment by Andy-Landers** [comment]
附议！！真的很爱这个软件，是我见过的最逼真的美化软件了！我也遇到了这个问题。

**Comment by mydockfinder** [comment]
嗯 我尽量下个版本修复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月6日(星期二) 下午5:45
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] 再上报两个小问题，作者大大一定要解决啊 (#137)





 
附议！！真的很爱这个软件，是我见过的最逼真的美化软件了！我也遇到了这个问题。
 
&mdash;

**Comment by heloook** [comment]
完美解决！
