### ISSUE TITLE
5.9.6.2 版本被windows defender认为是威胁

### ISSUE THREAD

**Issue by hairyOwl** [mydockfinder/mydockfinder#14]
昨天更新前没有问题，更新后今天电脑抱威胁，我想重新安装，但是安装软件也被认为是威胁
![image](https://user-images.githubusercontent.com/67627152/115486788-f0da7500-a289-11eb-809e-459fd5446e7c.png)
![image](https://user-images.githubusercontent.com/67627152/115486838-0780cc00-a28a-11eb-94d3-192c7adf1116.png)

**Comment by DingLiPlus** [comment]
同遇到此问题

**Comment by mydockfinder** [comment]
没事 个人软件都这样，没交保护费，大厂的软件后台偷你的浏览记录也不报毒，钱给够了

**Comment by db-one** [comment]
加入白名单

**Comment by hairyOwl** [comment]
懂了，这就去加白名单
