### ISSUE TITLE
输入法左侧的图标显示错误

### ISSUE THREAD

**Issue by heloook** [mydockfinder/mydockfinder#154]
![image](https://user-images.githubusercontent.com/27837566/125152143-46356c80-e17d-11eb-890a-273b82757d67.png)

如图。重启dock后，这个显示错误的图标会消失，但不知道什么时候就会又冒出来。

求解决🙏

**Comment by heloook** [comment]
![image](https://user-images.githubusercontent.com/27837566/125369198-68620100-e3ae-11eb-9e40-058d7922deb4.png)
新版本中，依然有此问题。

诱发原因不明。

**Comment by heloook** [comment]
![image](https://user-images.githubusercontent.com/27837566/125391053-63b14300-e3d6-11eb-8eff-2348f9608c8d.png)
可能和我之前选择在任务栏上隐藏输入法有关，
应该不是普遍问题，
暂时关闭。

**Comment by mydockfinder** [comment]
那有可能




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月13日(星期二) 中午12:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] 输入法左侧的图标显示错误 (#154)





 

 可能和我之前选择在任务栏上隐藏输入法有关，
 应该不是普遍问题，
 暂时关闭。
 
&mdash;
