### ISSUE TITLE
finder的网速,CPU,GPU,时间不更新但可正常点击, dock无法呼出

### ISSUE THREAD

**Issue by Miuzarte** [mydockfinder/mydockfinder#158]
finder的网速,CPU,GPU,时间不更新但可正常点击, dock无法呼出
0:53这个时间点应该是我显示器息屏的时间
![image](https://user-images.githubusercontent.com/66856838/125345126-b8c76780-e38a-11eb-931c-5ce4d1a38fa7.png)
![image](https://user-images.githubusercontent.com/66856838/125344873-6b4afa80-e38a-11eb-8f66-4507cf40e600.png)

**Comment by mydockfinder** [comment]
好吧 看来还是没修好




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月13日(星期二) 凌晨3:31
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder] finder的网速,CPU,GPU,时间不更新但可正常点击, dock无法呼出 (#158)





 
finder的网速,CPU,GPU,时间不更新但可正常点击, dock无法呼出
 0:53这个时间点应该是我显示器息屏的时间
