### ISSUE TITLE
有人碰到这个问题了吗？输入法左侧图标显示bug

### ISSUE THREAD

**Issue by heloook** [mydockfinder/mydockfinder#162]
最近每次开机的时候都出现

**Comment by heloook** [comment]
![image](https://user-images.githubusercontent.com/27837566/126092072-07b3a7bd-3be4-46c1-bf71-65ea5f1ff080.png)
![image](https://user-images.githubusercontent.com/27837566/126092106-a0b93f50-2173-44a6-9257-2eb23debca93.png)

**Comment by mydockfinder** [comment]
你倒是传个图啊  不知道什么样的

**Comment by heloook** [comment]
有没有人也碰到了这个问题？不清楚是不是个例

**Comment by smdx** [comment]
搜狗输入法没遇到这个问题

**Comment by heloook** [comment]
> 搜狗输入法没遇到这个问题

多谢回复。
我用的是微软拼音输入法。

**Comment by heloook** [comment]
换输入法了

**Comment by heloook** [comment]
换输入法之后，还是有，
![image](https://user-images.githubusercontent.com/27837566/127736398-e085301f-1780-4de1-8a60-e082c4a7325f.png)
能禁用输入法图标吗？我的系统是不能正常用了
