### ISSUE TITLE
finder的模糊没了  沉浸正常

### ISSUE THREAD

**Issue by Miuzarte** [mydockfinder/mydockfinder#165]
v5.9.9.91
![P}JSYIZZ9${OYH4JJ PS~Y](https://user-images.githubusercontent.com/66856838/126650292-83505168-8e95-4b00-a7d7-4e4285a6c6b5.png)
![image](https://user-images.githubusercontent.com/66856838/126650322-52dee79b-6ddc-4684-aa16-1d4d1d3100cc.png)

**Comment by mydockfinder** [comment]
下个版本模糊就好了&nbsp; 用了WINUI3.0




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月22日(星期四) 晚上9:51
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder] finder的模糊没了  沉浸正常 (#165)
