### ISSUE TITLE
文件夹中的图片不能打开

### ISSUE THREAD

**Issue by DFNJKD-98** [mydockfinder/mydockfinder#17]
![image](https://user-images.githubusercontent.com/63192338/115965044-da6a3d00-a559-11eb-9d4c-cae452ead0a4.png)
![image](https://user-images.githubusercontent.com/63192338/115965075-fa99fc00-a559-11eb-9c40-5ad25706f868.png)
请问这是属于哪方面的问题呢？

**Comment by mydockfinder** [comment]
我本来想看看路径是不是错了，你还给挡住了，，，，，

**Comment by DFNJKD-98** [comment]
今天重新启动电脑以后，可以打开图片了。但是还是没有图片预览（而且这个好像和路径没有关系，我每个路径下的图片都是这样子）

**Comment by mydockfinder** [comment]
我看之前的截图，那些图片在资源管理器里面也没有缩略图啊

**Comment by DFNJKD-98** [comment]
![image](https://user-images.githubusercontent.com/63192338/115989581-a5112e00-a5f1-11eb-93ca-3241d68913a1.png)
原来打开文件夹是可以看到这样子的，现在都显示不出来图片本来的样子啦

**Comment by DFNJKD-98** [comment]
win10系统在高级系统设置里面的视觉效果，找到了解决办法。
还是希望软件不要改变一些原有的设置（我也不知道是不是软件改的\(￣︶￣*\))

**Comment by mydockfinder** [comment]
软件没改那个设置，而且我都不知道代码怎么才能改那里的设置



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月25日(星期天) 晚上6:39
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] 文件夹中的图片不能打开 (#17)





 
win10系统在高级系统设置里面的视觉效果，找到了解决办法。
 还是希望软件不要改变一些原有的设置（我也不知道是不是软件改的(￣︶￣*))
 
&mdash;
