### ISSUE TITLE
finder请教

### ISSUE THREAD

**Issue by PowerDi** [mydockfinder/mydockfinder#224]
![image](https://user-images.githubusercontent.com/15917030/133915172-68f16200-4897-4e96-be6f-68a9479ee878.png)
![image](https://user-images.githubusercontent.com/15917030/133915177-67169eed-43d2-4002-9547-ede7c95fd6a4.png)

打扰了，请问这个微信的图标是否可以移到状态栏呢？我搜了好久都没有找到，但是看其他人是可以的，然后我已经从windows隐藏托盘里拉出来微信的了

**Comment by HaoShen2021** [comment]
点击这里的图标
![74D1682D-6D73-4979-B4CD-48A56EF2305A](https://user-images.githubusercontent.com/90556839/133915827-a1cd9ee3-fcb0-4ccf-9fec-07cd28da6960.jpeg)

**Comment by PowerDi** [comment]
> 点击这里的图标
> ![74D1682D-6D73-4979-B4CD-48A56EF2305A](https://user-images.githubusercontent.com/90556839/133915827-a1cd9ee3-fcb0-4ccf-9fec-07cd28da6960.jpeg)

谢谢!
