### ISSUE TITLE
启动提示winui failed

### ISSUE THREAD

**Issue by Pinghigh** [mydockfinder/mydockfinder#237]
由新版本系统降级下来出现这问题

**Comment by Pinghigh** [comment]
删除config.ini后恢复正常

**Comment by Laxdal** [comment]
我试了一下删除config，但是还是会有Winui failed的提示
我又重新装了一下VC2019，但是也没有效果

**Comment by mydockfinder** [comment]
重新装VC2019就会好的，32和64位都要装




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月12日(星期六) 中午11:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 启动提示winui failed (#237)





 
我试了一下删除config，但是还是会有Winui failed的提示
 我又重新装了一下VC2019，但是也没有效果
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Laxdal** [comment]
没找到32位的VC2019，看网上说64和32是同一个安装包，我又装了一下还是有提示

**Comment by Laxdal** [comment]
有可能我的不是最新版，我是从这里下的
https://docs.microsoft.com/zh-cn/cpp/windows/latest-supported-vc-redist?view=msvc-170
如果有最新版能不能挂下链接，谢谢😊

**Comment by mydockfinder** [comment]
你是在steam里面下载的吗






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月12日(星期六) 中午1:24
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 启动提示winui failed (#237)





 
有可能我的不是最新版，我是从这里下的
 https://docs.microsoft.com/zh-cn/cpp/windows/latest-supported-vc-redist?view=msvc-170
 如果有最新版能不能挂下链接，谢谢😊
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Laxdal** [comment]
不是，我没买steam版的
我看好像steam版可以自动安装运行库，
但是，能白嫖何必花钱呢😉

**Comment by Laxdal** [comment]
我的系统是win11，我更改看了一下steam的评论区，也有老哥碰到了这个问题，也是说安装最新的微软运行库，可是没挂链接😥

**Comment by mydockfinder** [comment]
免费版已经不更新了

http://www.winwin7.com/soft/21931.html




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月12日(星期六) 中午1:30
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 启动提示winui failed (#237)





 
不是，我没买steam版的
 我看好像steam版可以自动安装运行库，
 但是，能白嫖何必花钱呢😉
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mydockfinder** [comment]
因为steam自带，去steam目录里面安装一下就好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月12日(星期六) 中午1:32
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 启动提示winui failed (#237)





 
我的系统是win11，我更改看了一下steam的评论区，也有老哥碰到了这个问题，也是说安装最新的微软运行库，可是没挂链接😥
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
