### ISSUE TITLE
电脑开始会先出现任务栏，有好的办法处理吗?

### ISSUE THREAD

**Issue by zuoqiyin** [mydockfinder/mydockfinder#25]
希望电脑开机直接显示mydock，而不是先出现任务栏，闪一下才出来dock

**Comment by mydockfinder** [comment]
目前这个办法是兼容性最好的，因为考虑到部分没有密码的电脑，他的登录会特别快，那时候启动dock时dock需要的系统组件都还没起来。dock就开机起不来了，只能这样检测资源管理器是不是完全起来了dock才会启动，如果有密码的就没有这些顾虑的，因为要停留在锁屏界面一会，那一阵时间足够系统完全起来了

**Comment by zuoqiyin** [comment]
这个能不能设置成可配置的呢？

**Comment by smdx** [comment]
可以做个开关做成“开机任务栏完全不显示，然后检测资源管理器是不是完全起来了dock才会启动”吗？

**Comment by mydockfinder** [comment]
这是个方法 我试试，我可以先用mydock服务隐藏系统任务栏，然后等dock启动那样系统任务栏就不会显示了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月9日(星期天) 下午2:07
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] 电脑开始会先出现任务栏，有好的办法处理吗? (#25)





 
可以做个开关做成“开机任务栏完全不显示，然后检测资源管理器是不是完全起来了dock才会启动”吗？
 
&mdash;

**Comment by smdx** [comment]
这个好，系统任务栏闪一下太突兀了。期待。

**Comment by mydockfinder** [comment]
嗯 我试一下，之前说的是理论实际还不知道行不行




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月9日(星期天) 下午2:15
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] 电脑开始会先出现任务栏，有好的办法处理吗? (#25)





 
这个好，系统任务栏闪一下太突兀了。期待。
 
&mdash;

**Comment by smdx** [comment]
0509今天这个版本完美解决这个问题了，感谢作者。
