### ISSUE TITLE
Tray icon bug

### ISSUE THREAD

**Issue by RUvlad1** [mydockfinder/mydockfinder#267]
Opening Task Manager creates duplicates in the Tray Icon. This could be happening due to the name or icon rapidly changing.
This might be an issue in other applications, too.
![AeroShot 1_b1](https://user-images.githubusercontent.com/60317461/141525257-48fc72fa-d42b-44b0-b98c-a850fa7ee34b.png)

**Comment by mydockfinder** [comment]
好的，我尽量修复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月13日(星期六) 凌晨3:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] Tray icon bug (Issue #267)






打开任务管理器会在托盘图标中创建重复的任务。这可能是由于名称或图标的快速变化。
这在其他应用程序中可能也是一个问题。


—
您正在接收此消息，因为您订阅了此线程。
直接回复此邮件，在 GitHub 上查看或取消订阅.
GitHub Mobile 上的分流通知监督办或机器人.
