### ISSUE TITLE
dock图标遮罩功能有问题

### ISSUE THREAD

**Issue by smdx** [mydockfinder/mydockfinder#27]
你好，win10-19043.928、mydockfinder 5.9.9。dock图标遮罩功能有问题设置了无遮罩后在dock的图标有些还是会显示遮罩。试过重启app了。
![2021-05-09_141132](https://user-images.githubusercontent.com/9279217/117562333-c3d2f280-b0d0-11eb-951a-72668aa843a6.jpg)

**Comment by mydockfinder** [comment]
有的图标是有缓存图片的，看一下runpng和png文件夹里面有没有对应的图片，有的话删除就可以了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月9日(星期天) 下午2:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder] dock图标遮罩功能有问题 (#27)





 
你好，win10-19043.928、mydockfinder 5.9.9。dock图标遮罩功能有问题设置了无遮罩后在dock的图标有些还是会显示遮罩。试过重启app了。

**Comment by smdx** [comment]
感谢，在png文件夹删除缓存后解决了。
