### ISSUE TITLE
Mydockfinder 应用程序打开时总是崩溃

### ISSUE THREAD

**Issue by qirkl1** [mydockfinder/mydockfinder#285]
![image](https://user-images.githubusercontent.com/82781802/143623858-b1a89a6e-9a5d-42e3-971c-c7d08d4226b3.png)

您好，我已经使用这个应用程序 2 周了，我真的很喜欢这个应用程序，但最近我在尝试打开应用程序时总是崩溃。我尝试了一切，我尝试重新安装应用程序并重置我的电脑，但没有任何效果。如果崩溃仍然存在，我怀疑是否从 Steam 购买该应用程序。

希望你能帮助我:)

**Comment by qirkl1** [comment]
顺便说一下，我实际上安装了 VC2015，所以我实际上不知道它为什么会崩溃。

**Comment by mydockfinder** [comment]
VC2015-2019 32和64位都要安装，不要用管理员模式和兼容模式运行，程序别放在C盘

**Comment by qirkl1** [comment]
非常感谢，成功了！ ！
如果我有钱，我会买steam版，谢谢你这么棒的应用！
