### ISSUE TITLE
程序图标的读取很影响体验

### ISSUE THREAD

**Issue by db-one** [mydockfinder/mydockfinder#3]
每次都要读取很长时间才能显示，看了他的逻辑好像是直接读取了完整的程序，然后才显示的，如果可以直接跟WIN一样显示就好了，默认文件夹下直接一次就显示了
特别是软件多的情况下，真的要读取很长时间，启动台也是一样的，每次首次启动点击都没反应，要等个十几秒才弹出来窗口
如果可以像WIN文件夹一样，里面再多程序，点开直接秒进就好了，或者加一个缓存
另外就是最新版本的，还是会出现透明模糊背景显示灰白色的情况，鼠标上去晃一下就好了

**Comment by db-one** [comment]
另外文件夹反复点开 关闭 动鼠标 会死机，第一次死机了，刚刚重新开机以后再次反复点击动鼠标又死机了

**Comment by mydockfinder** [comment]
看来要加个图标的缓存了，文件夹每次都是读取系统的图标缓存，看来你的系统图标缓存很多啊，试一下清理图标缓存重启系统看看，这个版本确实会卡死新的渲染方式有点问题，模糊的问题目前解决不了的，这个是系统的渲染的模糊而且exe目前微软是不让用这种模糊效果的这是个未公开的接口只能私底下用




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月12日(星期一) 中午11:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] 程序图标的读取很影响体验 (#3)





 
另外文件夹反复点开 关闭 动鼠标 会死机，第一次死机了，刚刚重新开机以后再次反复点击动鼠标又死机了
 
&mdash;

**Comment by db-one** [comment]
哈哈哈  ，也不多   68个而已

**Comment by wangxiaoqiang1998** [comment]
分隔符没法删除   删除就崩溃，重启也不行

**Comment by mydockfinder** [comment]
emmmmmmmmmmmmmmmmmm




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月12日(星期一) 晚上9:03
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] 程序图标的读取很影响体验 (#3)





 
分隔符没法删除   删除就崩溃，重启也不行
 
&mdash;

**Comment by db-one** [comment]
RocketDock里面的StackDocklet插件，不管加载多少个图标都是秒开的，不知道是什么方法读取的图标，不知道有没有参考价值

**Comment by mydockfinder** [comment]
没有源码 就没法参考




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月12日(星期一) 晚上9:55
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] 程序图标的读取很影响体验 (#3)





 
RocketDock里面的StackDocklet插件，不管加载多少个图标都是秒开的，不知道是什么方法读取的图标，不知道有没有参考价值
 
&mdash;

**Comment by db-one** [comment]
6.1版本在线更新失败，手动下载覆盖更新的话，启动之后会自己变成6.0版本，很奇怪，然后还会继续死机

**Comment by db-one** [comment]
新版已经OK了，关闭了GPU渲染，图标缓存之后，打开文件夹终于可以秒开了
另外就是那个dock栏模糊效果经常变为灰白色的问题，是否可以增加一个设置为透明效果的选项，让他直接半透明状态，不用模糊也可以，这样还可以避免经常变灰白色的问题
