### ISSUE TITLE
访达左侧按钮有时候会和windows开始键混合在一起

### ISSUE THREAD

**Issue by Amhertx** [mydockfinder/mydockfinder#30]
![bug反馈](https://user-images.githubusercontent.com/46993971/117599909-6f398100-b17d-11eb-87f7-da0be322b28e.png)
点击访达上面的图标打开软件或者点击dock上面的软件有很大概率复现，
访达有时候点击音量，wifi等图标会有黑色背景闪过，
最后希望增加访达右击软件弹窗可以通过点击访达任意空白取消掉弹框，不然很容易出现如下情况（多个弹窗重叠），望采纳，开发者辛苦了
![image](https://user-images.githubusercontent.com/46993971/117600093-deaf7080-b17d-11eb-884a-a96d56eb1cc3.png)

**Comment by mydockfinder** [comment]
谢谢
1、是不是装了stack什么的任务栏那个修改软件了，目前和他冲突，因为系统自带的开始按钮不是一个独立的按钮，隐藏任务栏是不可能再出现的
2、没太懂，是访达上面有黑色背景闪过，还是应该出菜单的地方
3、能力有限目前无解




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月10日(星期一) 上午10:54
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder] 访达左侧按钮有时候会和windows开始键混合在一起 (#30)





 

 点击访达上面的图标打开软件或者点击dock上面的软件有很大概率复现，
 访达有时候点击音量，wifi等图标会有黑色背景闪过，
 最后希望增加访达右击软件弹窗可以通过点击访达任意空白取消掉弹框，不然很容易出现如下情况（多个弹窗重叠），望采纳，开发者辛苦了

**Comment by Amhertx** [comment]
1、是有装修改任务栏的软件，所以这个冲突是只能卸载startlsBack解决吗，还是有什么别的办法呢
2、是应该出现菜单的地方会有个黑色背景闪过
3、啊这。。。作者加油，用头发或许可以换取解决办法

**Comment by mydockfinder** [comment]
1、是的只有这个办法，因为他是把任务栏修改了，结构都变了，而且有他有时隐藏了任务栏他还会再把任务栏显示出来
2、应该是出菜单了立马就隐藏了，几率大吗能不能截图或者拍个视频，视频发我邮箱就可以






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月10日(星期一) 中午11:10
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] 访达左侧按钮有时候会和windows开始键混合在一起 (#30)





 
1、是有装修改任务栏的软件，所以这个冲突是只能卸载startlsBack解决吗，还是有什么别的办法呢
 2、是应该出现菜单的地方会有个黑色背景闪过
 3、啊这。。。作者加油，用头发或许可以换取解决办法

**Comment by Amhertx** [comment]
重启了dock开启Finder后，第二点暂时无法复现了

**Comment by mydockfinder** [comment]
好吧，我在看看代码没准下次更新就好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月10日(星期一) 中午11:36
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] 访达左侧按钮有时候会和windows开始键混合在一起 (#30)





 
重启了dock开启Finder后，第二点暂时无法复现了
 
&mdash;
