### ISSUE TITLE
URL too long, display bug in sound section

### ISSUE THREAD

**Issue by isaiahwtc** [mydockfinder/mydockfinder#306]
https://user-images.githubusercontent.com/93420142/146506550-42fc8ae0-5963-42f2-8c7f-c28413a4ac0a.mp4

as shown in video

**Comment by mydockfinder** [comment]
懂了，这是浏览器的媒体控制标题，但是网页标题是网址链接就会这样，我回来加一个文字截断就可以了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月17日(星期五) 下午3:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] URL too long, display bug in sound section (Issue #306)





 
https://user-images.githubusercontent.com/93420142/146506550-42fc8ae0-5963-42f2-8c7f-c28413a4ac0a.mp4
 
as shown in video
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by isaiahwtc** [comment]
对呀 只是报告一下。这应该容易修复我也是在读电脑，有需要帮忙/找bug 可以找我
