### ISSUE TITLE
个别软件显示问题

### ISSUE THREAD

**Issue by Amhertx** [mydockfinder/mydockfinder#31]
steam在后台的时候，点击图标唤起窗口会有一个右键任务栏steam的效果
![屏幕截图 2021-05-10 110106](https://user-images.githubusercontent.com/46993971/117600858-6649af00-b17f-11eb-82c2-18799036d8a8.png)

cent浏览器和chrome的图标有时候会变成同一个
![Snipaste_2021-05-10_11-02-13](https://user-images.githubusercontent.com/46993971/117600916-7cf00600-b17f-11eb-9e78-fd323cddb812.png)

**Comment by mydockfinder** [comment]
1、点击stream图标时，默认是先寻找有没有stream的窗口，如果没有会后台模拟点击一下系统托盘图标激活它，弹出来菜单就是后台点击他的事
2、打开dock目录png或者runpng文件夹，找到chrome.png应该是这个文件名删除它就可以了，没有的话找找有没有这个chrome的图片删除就可以了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月10日(星期一) 中午11:05
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder] 个别软件显示问题 (#31)





 
steam在后台的时候，点击图标唤起窗口会有一个右键任务栏steam的效果
 
 
cent浏览器和chrome的图标有时候会变成同一个

**Comment by Amhertx** [comment]
哦哦，谢谢
