### ISSUE TITLE
Any plan to release in MS Store?

### ISSUE THREAD

**Issue by onlytanmoy** [mydockfinder/mydockfinder#313]
Hiya, first things first- many thanks for this amazing app 👍
Just wanted to know if you plan to release it in Microsoft Store for purchasing or it will be Steam only?

**Comment by mydockfinder** [comment]
过几个月会在微软商店上架，不过要等steam版本创意工坊功能全部做好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月26日(星期天) 凌晨3:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] Any plan to release in MS Store? (Issue #313)






Hiya ，首先，非常感谢这个神奇的应用程序👍
只是想知道，如果你计划在微软商店发布购买或它将是蒸汽只？

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
GitHub Mobile 上的分流通知监督办或机器人. 
***@***.***与&gt;

**Comment by onlytanmoy** [comment]
Thanks for confirming mate, I will check back after 2 months 🙂 closing this ticket now.
