### ISSUE TITLE
Disable dock hiding when window is maximised

### ISSUE THREAD

**Issue by Ephelyon** [mydockfinder/mydockfinder#319]
Hi, I really love this program!

But there's only one thing stopping me from switching to it fully, and that's that I'd prefer the Dock NOT to hide when a window is maximised. I never turn on auto-hide on my MacBook Air, and I like the Dock to still always be visible even if a window is maximised.

But not as an overlay - just that the maximised window only reaches down to the top of the Dock, which is treated as the bottom of the screen for that maximised window. Other programs like ObjectDock can do this, for example.

Do you think this would be possible, please?

**Comment by mydockfinder** [comment]
可以，偏好设置-mydock 高级-开启窗口边界防止遮挡窗口，开启后就和mac一样了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月3日(星期一) 晚上11:24
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] Disable dock hiding when window is maximised (Issue #319)





 
Hi, I really love this program!
 
But there's only one thing stopping me from switching to it fully, and that's that I'd prefer the Dock NOT to hide when a window is maximised. I never turn on auto-hide on my MacBook Air, and I like the Dock to still always be visible even if a window is maximised.
 
But not as an overlay - just that the maximised window only reaches down to the top of the Dock, which is treated as the bottom of the screen for that maximised window. Other programs like ObjectDock can do this, for example.
 
Do you think this would be possible, please?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ephelyon** [comment]
Many thanks! :)
