### ISSUE TITLE
测试版本壁纸预览有问题

### ISSUE THREAD

**Issue by Pylogmon** [mydockfinder/mydockfinder#324]
![image](https://user-images.githubusercontent.com/59004461/150685264-d6b3cc1c-51a4-455d-b706-6b7be6925a7e.png)

**Comment by mydockfinder** [comment]
厉害了，你是不是把系统的图片缩略图关了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月23日(星期天) 晚上11:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 测试版本壁纸预览有问题 (Issue #324)





 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Pylogmon** [comment]
> 厉害了，你是不是把系统的图片缩略图关了
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人: ***@***.***&gt;; 
> 发送时间: 2022年1月23日(星期天) 晚上11:14
> 收件人: ***@***.***&gt;; 
> 抄送: ***@***.***&gt;; 
> 主题: [mydockfinder/mydockfinder-for-Win10-Win11] 测试版本壁纸预览有问题 (Issue #324)
> 
> 
> 
> 
> 
>  
> 
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

啊这，还真是
