### ISSUE TITLE
Crash when changing icons

### ISSUE THREAD

**Issue by TRINCETT** [mydockfinder/mydockfinder#329]
I was changing the icons of my applications but when changing several icons in the launcher crashes and closes.

**Comment by TRINCETT** [comment]
Sorry if the quality of the video is low, github does not allow me more than 10MB

https://user-images.githubusercontent.com/93570862/151915611-b0fc4175-004c-4964-958c-4e3669e29412.mp4

**Comment by mydockfinder** [comment]
崩溃以后会有dmp文件，请把它传给我




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月1日(星期二) 中午1:08
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [mydockfinder/mydockfinder-for-Win10-Win11] Crash when changing icons (Issue #329)





 
Sorry if the quality of the video is low, github does not allow me more than 10MB
 
https://user-images.githubusercontent.com/93570862/151915611-b0fc4175-004c-4964-958c-4e3669e29412.mp4
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by TRINCETT** [comment]
[MyDockFinder.zip](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/files/7982260/MyDockFinder.zip)
