### ISSUE TITLE
翻譯問題可在這裏匯報嗎?

### ISSUE THREAD

**Issue by aaronyip675** [mydockfinder/mydockfinder#331]
![problem](https://user-images.githubusercontent.com/96892176/152191374-645ac3c1-b009-41c4-8059-00d66395557e.png)
开启关闭 Dock 窗口边界快捷键
要翻譯成
開啟關閉 Dock 窗口邊界快捷鍵

**Comment by aaronyip675** [comment]
以選擇繁體中文還出現簡體字

**Comment by mydockfinder** [comment]
刚才那一个地方还是所有的地方都是



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月3日(星期四) 凌晨0:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 翻譯問題可在這裏匯報嗎? (Issue #331)





 
以選擇繁體中文還出現簡體字
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aaronyip675** [comment]
目前只發現只一處地方!
控制面板 
我們港澳台是控制台

**Comment by mydockfinder** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月3日(星期四) 上午10:20
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 翻譯問題可在這裏匯報嗎? (Issue #331)





 
目前只發現只一處地方!
 控制面板
 我們港澳台是控制台
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
