### ISSUE TITLE
修改語言檔沒有這條項目?

### ISSUE THREAD

**Issue by aaronyip675** [mydockfinder/mydockfinder#333]
开启关闭 Dock 窗口边界快捷键
Traditional Chinese.ini
![image](https://user-images.githubusercontent.com/96892176/152705374-903023c9-2f11-486e-9255-437a148356ad.png)
無法翻譯

**Comment by mydockfinder** [comment]
繁体中文是其他网友帮我翻译的，可能他把这个给忘了，我下次更新加上




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月7日(星期一) 上午7:08
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] 修改語言檔沒有這條項目? (Issue #333)





 
开启关闭 Dock 窗口边界快捷键
 Traditional Chinese.ini
 
 無法翻譯
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
