### ISSUE TITLE
Can't poweroff or reboot my pc

### ISSUE THREAD

**Issue by cathome1** [mydockfinder/mydockfinder#338]
When i click on puttons on this menu(screenshot) nothing is happening
![image](https://user-images.githubusercontent.com/31789194/157128842-b179cfe5-dcf3-4fdb-9ffa-1ae4508ebadc.png)
sleep and log out too
almost all buttons do not respond to pressing
only Task Manager and App Store reacts

**Comment by mydockfinder** [comment]
这是旧版本，新版本已经修复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月8日(星期二) 上午6:32
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] Can't poweroff or reboot my pc (Issue #338)





 
When i click on puttons on this menu(screenshot) nothing is happening
 
 sleep and log out too
 almost all buttons do not respond to pressing
 only Task Manager and App Store reacts
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
