### ISSUE TITLE
Lỗi khi chia sẻ màn hình-ghi màn hình!

### ISSUE THREAD

**Issue by viethungnguyen230860** [mydockfinder/mydockfinder#341]
Khi chia sẻ-ghi màn hình thì các hiệu ứng hoạt hình thu nhỏ cửa sổ sẽ bị chậm lại, tôi cũng không biết mọi người cảm thấy thế nào khi hiệu ứng hoạt hình qúa chậm. Đối với tôi, nó chiếm 1 khoảng thời gian khá lớn làm cho tôi thấy hơi khó chịu mong nhà sản xuất sẽ ra bản sửa lỗi.

**Comment by mydockfinder** [comment]
显示器刷新率是不是超过了60Hz



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月12日(星期六) 晚上11:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] Lỗi khi chia sẻ màn hình-ghi màn hình! (Issue #341)






当共享-记录屏幕时,最小化窗口的动画效果会减慢,我也不知道当动画效果太慢时,人们的感受会很慢。对我来说,它占用了相当长的时间,这让我感觉有点不舒服。

—
直接回复这封电子邮件，在GitHub上查看，或取消订阅.
GitHub Mobile Go的分流通知IOS或机器人. 
您收到此消息是因为您订阅了此线程。留言 ID ***@***.***与&gt;

**Comment by viethungnguyen230860** [comment]
> Tốc độ làm mới màn hình có vượt quá 60Hz không?
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年3月12日(星期六) 晚上11:15 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [mydockfinder/mydockfinder-for-Win10-Win11] Lỗi khi chia sẻ màn hình-ghi màn hình! (Issue #341) 当共享-记录屏幕时,最小化窗口的动画效果会减慢,我也不知道当动画效果太慢时,人们的感受会很慢。对我来说,它占用了相当长的时间,这让我感觉有点不舒服。 — 直接回复这封电子邮件，在GitHub上查看，或取消订阅. GitHub Mobile Go的分流通知IOS或机器人. 您收到此消息是因为您订阅了此线程。留言 ID ***@***.***与&gt;

**Comment by viethungnguyen230860** [comment]
Không. Mà nó thu nhỏ hay phóng to cửa sổ rất chậm.

**Comment by mydockfinder** [comment]
![image](https://user-images.githubusercontent.com/32895737/158042138-3e2b1bbd-7751-44ec-8071-bb166ffebf5c.png)
系统-显示-高级显示

**Comment by viethungnguyen230860** [comment]
Cái máy của mình chỉ có 60Hz thôi.

**Comment by mydockfinder** [comment]
那就是显卡的问题了，应该是屏幕共享的时候显卡负载太大了，所以渲染才会变慢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月13日(星期天) 上午10:25
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Lỗi khi chia sẻ màn hình-ghi màn hình! (Issue #341)





 
Cái máy của mình chỉ có 60Hz thôi.
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by viethungnguyen230860** [comment]
Trường hợp của mình là khi không chia sẻ màn hình hay ghi màn hình thì hiệu ứng hoạt hình rất mượt, nhưng khi chia sẻ màn hình thị nó bị chậm và giật

**Comment by viethungnguyen230860** [comment]
Vậy có cách nào sửa lỗi card đồ hoạ không?
Vì mình đã cho MyDockFinder chạy hết công suất card đồ hoạ rồi.

**Comment by mydockfinder** [comment]
如果是笔记本使用集显，不要使用独立显卡



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月13日(星期天) 中午11:06
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Lỗi khi chia sẻ màn hình-ghi màn hình! (Issue #341)





 
Vậy có cách nào sửa lỗi card đồ hoạ không?
 Vì mình đã cho MyDockFinder chạy hết công suất card đồ hoạ rồi.
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
