### ISSUE TITLE
程序崩溃如何关闭任务栏隐藏

### ISSUE THREAD

**Issue by huarzone** [mydockfinder/mydockfinder#346]
想问一下，程序崩溃，重启无效，但是任务栏被隐藏无法显示，这个怎么关闭任务栏隐藏。

**Comment by mydockfinder** [comment]
崩溃以后目录会有dmp文件，传给我。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月19日(星期六) 中午12:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 程序崩溃如何关闭任务栏隐藏 (Issue #346)





 
想问一下，程序崩溃，重启无效，但是任务栏被隐藏无法显示，这个怎么关闭任务栏隐藏。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by huarzone** [comment]
并没有发现dmp文件

**Comment by huarzone** [comment]
![IMG_20220319_143427](https://user-images.githubusercontent.com/101872541/159110406-6692eac1-521c-416e-8c71-1200cddfb648.jpg)

**Comment by mydockfinder** [comment]
i这是旧版本啊，已经不支持了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月19日(星期六) 下午2:32
***@***.***&gt;;
抄送:&nbsp;"№じ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [mydockfinder/mydockfinder-for-Win10-Win11] 程序崩溃如何关闭任务栏隐藏 (Issue #346)





 
并没有发现dmp文件
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by huarzone** [comment]
emmmm，那我应该如何退出或关闭这个程序，恢复任务栏呢

**Comment by mydockfinder** [comment]
任务管理器结束了，然后结束mydock程序，再把程序整个文件夹删除了，然后系统任务栏设置一下别用自动隐藏了就好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月19日(星期六) 下午2:53
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 程序崩溃如何关闭任务栏隐藏 (Issue #346)





 
emmmm，那我应该如何退出或关闭这个程序，恢复任务栏呢
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by huarzone** [comment]
并没有解决，程序删除，结束任务，而且重启后没有这个进程了，但是仍然没有任务栏

**Comment by mydockfinder** [comment]
系统任务栏设置里面取消掉自动隐藏




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月19日(星期六) 晚上8:28
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 程序崩溃如何关闭任务栏隐藏 (Issue #346)





 
并没有解决，程序删除，结束任务，而且重启后没有这个进程了，但是仍然没有任务栏
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
