### ISSUE TITLE
微信截图会触发消息提示

### ISSUE THREAD

**Issue by yxzlwz** [mydockfinder/mydockfinder#348]
如题，steam最新版

**Comment by mydockfinder** [comment]
目前无解，消息提示是我找到的一种规律，如果微信触发了那个规律就算没有消息也会提示来消息




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月21日(星期一) 晚上7:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 微信截图会触发消息提示 (Issue #348)





 
如题，steam最新版

**Comment by yxzlwz** [comment]
不知道是您修复了还是微信更新后好了，现在问题解决✌

**Comment by mydockfinder** [comment]
我没改。。。。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月9日(星期六) 中午12:36
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 微信截图会触发消息提示 (Issue #348)





 
Closed #348 as completed.
 
&mdash;
