### ISSUE TITLE
时钟图标为什么每次启动软件都显示出来

### ISSUE THREAD

**Issue by bestv5** [mydockfinder/mydockfinder#350]
时钟图标为什么每次启动软件都显示出来，即便我手动去掉。是我设置的问题还是默认就这样

**Comment by mydockfinder** [comment]
dock上固定的图标如果少于5个删不下去




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月22日(星期二) 晚上7:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 时钟图标为什么每次启动软件都显示出来 (Issue #350)





 
时钟图标为什么每次启动软件都显示出来，即便我手动去掉。是我设置的问题还是默认就这样

**Comment by bestv5** [comment]
在配置文件中已删除...
