### ISSUE TITLE
finder栏输入法键盘

### ISSUE THREAD

**Issue by azhaYOLO** [mydockfinder/mydockfinder#353]
finder栏输入法键盘不显示是中文状态或者是英文状态。能否设置不显示输入法 只显示中文、英文的状态切换？

**Comment by mydockfinder** [comment]
我也想，但是我不会




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月24日(星期四) 下午2:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] finder栏输入法键盘 (Issue #353)





 
finder栏输入法键盘不显示是中文状态或者是英文状态。能否设置不显示输入法 只显示中文、英文的状态切换？
