### ISSUE TITLE
[Query]Availability in Microsoft Store?

### ISSUE THREAD

**Issue by onlytanmoy** [mydockfinder/mydockfinder#364]
Hi mate, just wanted to know when are you planning to make the app available in Microsoft store for purchase?

**Comment by onlytanmoy** [comment]
@mydockfinder any plans to make the app available in MS Store soon?

**Comment by mydockfinder** [comment]
还没有想好是使用steam账号登陆还是一个独立的商店版本



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月16日(星期六) 下午3:51
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] [Query]Availability in Microsoft Store? (Issue #364)






我的码头搜索器有计划使应用程序在 MS 商店很快？

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
你收到这个是因为你被提到了。留言 ID ***@***.***与&gt;

**Comment by onlytanmoy** [comment]
@mydockfinder I have now purchased the Steam version and all seem fine.
Just one query - I have WhatsApp installed from MS Store, how do I add it to the Dock and Launchpad?

**Comment by mydockfinder** [comment]
将开始菜单中的WhatsApp拽到创建桌面创建快捷方式，将这个快捷方式添加就可以了，添加完了快捷方式可以删了&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月10日(星期一) 凌晨5:00
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] [Query]Availability in Microsoft Store? (Issue #364)





 
@mydockfinder我现在已经购买了Steam版本，一切似乎都很好。
只有一个查询 - 我已经从MS商店安装了WhatsApp，我如何将其添加到扩展坞和快速启动板？
 
—
 直接回复此电子邮件、在 GitHub 上查看或取消订阅。
你收到这个是因为你被提及了。Message ID: ***@***.***&gt;

**Comment by onlytanmoy** [comment]
Thanks mate, happy to close this issue.

**Comment by mydockfinder** [comment]
我不知道怎么上传到微软商店，UWP程序很简单但是exe程序不会上传，找不到上传的地方




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月10日(星期天) 凌晨1:23
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] [Query]Availability in Microsoft Store? (Issue #364)





 
Hi mate, just wanted to know when are you planning to make the app available in Microsoft store for purchase?

**Comment by onlytanmoy** [comment]
Yeah don't worry about MS Store, I have already purchased the Steam version :)

Will I get notified once a new version of the app is available in Steam? I do not have Steam running in the background.

**Comment by mydockfinder** [comment]
我打算下个版本加入更新提示和更新日志功能的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月11日(星期二) 晚上7:17
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] [Query]Availability in Microsoft Store? (Issue #364)





 
Yeah don't worry about MS Store, I have already purchased the Steam version :)
 
Will I get notified once a new version of the app is available in Steam? I do not have Steam running in the background.
 
&mdash;

**Comment by onlytanmoy** [comment]
That will be great, thanks mate 👍
