### ISSUE TITLE
Minimize Windows

### ISSUE THREAD

**Issue by Razzanfbr** [mydockfinder/mydockfinder#378]
Minimize Windows isn't turned on even I turned on the option "Minimize Windows to dock"

**Comment by mydockfinder** [comment]
是不是勾选了 关闭最小化动画




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月17日(星期二) 晚上11:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] Minimize Windows (Issue #378)






最小化 Windows 没有打开,即使我打开选项"最小化窗口停靠"

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
您收到此消息是因为您订阅了此线程。留言 ID ***@***.*** Windows isn't turned on even I turned on the option "Minimize Windows to dock".—

**Comment by Razzanfbr** [comment]
是的，它检查了，这是我的错误，对不起

**Comment by mydockfinder** [comment]
没事，很多人都是这样勾选多了最后没有动画




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月19日(星期四) 上午10:46
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Minimize Windows (Issue #378)





 
是的，它检查了，这是我的错误，对不起

**Comment by Razzanfbr** [comment]
无论如何，媒体播放器进度条是否延迟，在我的电脑中它已延迟

**Comment by Razzanfbr** [comment]
无论如何，媒体播放器进度条是否延迟，在我的电脑中它已延迟

**Comment by mydockfinder** [comment]
播放进度是播放器的问题，有的播放器更新是5秒一次，有的是一秒一次




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月19日(星期四) 晚上9:18
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Minimize Windows (Issue #378)





 
无论如何，媒体播放器进度条是否延迟，在我的电脑中它已延迟
 
&mdash;
