### ISSUE TITLE
Windows11 QQ音乐歌词问题

### ISSUE THREAD

**Issue by yxzlwz** [mydockfinder/mydockfinder#398]
先膜拜大佬，能把桌面歌词这样的东西靠主动适配做出来！

开启桌面歌词后finder正常显示，但是单机finder中的歌词隐藏QQ音乐本身的歌词后finder栏歌词不再更新，再次单击开启QQ音乐的桌面歌词后恢复正常，100%复现，麻烦看下什么情况，不胜感谢。

**Comment by mydockfinder** [comment]
不应该啊，最新版我是修复这个问题了，版本是1.8.6吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月9日(星期六) 凌晨0:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] Windows11 QQ音乐歌词问题 (Issue #398)





 
先膜拜大佬，能把桌面歌词这样的东西靠主动适配做出来！
 
开启桌面歌词后finder正常显示，但是单机finder中的歌词隐藏QQ音乐本身的歌词后finder栏歌词不再更新，再次单击开启QQ音乐的桌面歌词后恢复正常，100%复现，麻烦看下什么情况，不胜感谢。

**Comment by yxzlwz** [comment]
> 

是1.8.6没错

之前的版本没更新，只试了这一个版本

**Comment by mydockfinder** [comment]
这怪了 我这里没事啊，你是几个显示器




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月9日(星期六) 中午12:28
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Windows11 QQ音乐歌词问题 (Issue #398)





   
是1.8.6没错
 
之前的版本没更新，只试了这一个版本

**Comment by yxzlwz** [comment]
好的，找到问题了，一个显示器没问题，连接第二个就不行了

**Comment by mydockfinder** [comment]
你的显示器怎么排列的能截图给我吗，在系统设置 显示器里面了






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月9日(星期六) 中午12:31
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Windows11 QQ音乐歌词问题 (Issue #398)





 
好的，找到问题了，一个显示器没问题，连接第二个就不行了
 
&mdash;

**Comment by yxzlwz** [comment]
![image](https://user-images.githubusercontent.com/75941562/178091693-2d332db8-45e5-429f-8ff0-1524949ad6e7.png)

如图，上下排列

**Comment by mydockfinder** [comment]
懂了，应该是隐藏的时候我没适配多屏的问题，我适配一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月9日(星期六) 中午12:33
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Windows11 QQ音乐歌词问题 (Issue #398)





 

 
如图，上下排列
 
&mdash;

**Comment by yxzlwz** [comment]
OK，感谢大佬！

**Comment by mydockfinder** [comment]
不客气 明天更新就好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月9日(星期六) 中午12:35
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Windows11 QQ音乐歌词问题 (Issue #398)





 
OK，感谢大佬！

**Comment by yxzlwz** [comment]
嘻嘻解决问题……给大佬端茶~

**Comment by mydockfinder** [comment]
emmm&nbsp; 我更新日志忘写了。。。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月10日(星期天) 晚上9:35
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Windows11 QQ音乐歌词问题 (Issue #398)





 
嘻嘻解决问题……给大佬端茶~
 
&mdash;

**Comment by Coder-ZZY** [comment]
hello，Windows11也遇到了相同的问题，使用的时候必须开启QQ音乐桌面歌词功能，mydockfinder版本1.9.9，QQ音乐版本是2031，只有一个显示器，请问怎么解决？

**Comment by mydockfinder** [comment]
播放器歌词是必须要开的，因为没有公开的接口只能用播放器的歌词来转换
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月23日(星期二) 中午11:01
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Windows11 QQ音乐歌词问题 (Issue #398)














 
hello，Windows11也遇到了相同的问题，使用的时候必须开启QQ音乐桌面歌词功能，mydockfinder版本1.9.9，QQ音乐版本是2031，只有一个显示器，请问怎么解决？

**Comment by Coder-ZZY** [comment]
> 播放器歌词是必须要开的，因为没有公开的接口只能用播放器的歌词来转换 &nbsp; №じ&nbsp;尐乄鈊~→☆ ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年7月23日(星期二) 中午11:01 收件人: ***@***.***&gt;; 抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Windows11 QQ音乐歌词问题 (Issue #398) hello，Windows11也遇到了相同的问题，使用的时候必须开启QQ音乐桌面歌词功能，mydockfinder版本1.9.9，QQ音乐版本是2031，只有一个显示器，请问怎么解决？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

请问怎么隐藏桌面歌词呢，两个在一起看着很呆

**Comment by mydockfinder** [comment]
点一下myfinder歌词就隐藏了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月23日(星期二) 中午11:07
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Windows11 QQ音乐歌词问题 (Issue #398)





  
播放器歌词是必须要开的，因为没有公开的接口只能用播放器的歌词来转换   №じ 尐乄鈊~→☆ @.***  
 …
 ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2024年7月23日(星期二) 中午11:01 收件人: @.&gt;; 抄送: "№じ @.&gt;; @.&gt;; 主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Windows11 QQ音乐歌词问题 (Issue #398) hello，Windows11也遇到了相同的问题，使用的时候必须开启QQ音乐桌面歌词功能，mydockfinder版本1.9.9，QQ音乐版本是2031，只有一个显示器，请问怎么解决？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
请问怎么隐藏桌面歌词呢，两个在一起看着很呆
 
&mdash;
