### ISSUE TITLE
会影响右键跳出？

### ISSUE THREAD

**Issue by db-one** [mydockfinder/mydockfinder#406]
mydock会影响右键跳出，具体如图，很早就有这个问题了，之前反馈过一次好像你没看到，不知道其他人有没有遇到过，右键在任务栏弹出菜单，几秒之后会被关闭，它这个时间也不是说右键弹出之后才开始计时几秒被关闭，好像就是一个纯周期性的，然后右键点击的时机正好遇到这个周期，那么会在右键弹出瞬间被关闭，不知道我这样描述是不是很清晰，严重时候甚至输入法打字都会被每隔几秒被打断一次
有时候又没有这个问题，但是每次遇到这个问题，只要结束了mydock就可以解决，尝试过遇到问题时候关闭其他所有的软件仅保留mydock这个问题依然存在，所以暂时只能把这个问题锁定在mydock上，如果不是软件问题还请抱歉，用老版本的最后一个免费版本没有遇到这个问题的
仅开启了mydock，桌面那个没有开
给人的感觉好像就是每隔几秒检查了一下键盘或者输入什么按键类似的
![动画](https://user-images.githubusercontent.com/20243226/179430830-ca74e896-8c05-4624-8e49-485a481377f4.gif)
![image](https://user-images.githubusercontent.com/20243226/179431021-53d67de1-f8cd-4416-b07c-8425a3b31a08.png)

**Comment by db-one** [comment]
截图中我是仅按了右键，其他什么都没动然后菜单就被关闭了

**Comment by mydockfinder** [comment]
我知道这个，但是我自己右键真的没事，所以我调试时找不到问题根源就没法修复，不过我可以远程调试你的电脑就可以找到原因了，如果你方便的话




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月18日(星期一) 上午8:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 会影响右键跳出？ (Issue #406)





 
截图中我是仅按了右键，其他什么都没动然后菜单就被关闭了
 
&mdash;

**Comment by db-one** [comment]
不介意的话加个Q什么的  我待会发你邮箱  遇到了到时候给你看看 这会又是好的
我也是排除了好久  才跟你反馈的

**Comment by db-one** [comment]
新版已修复，关闭了吧

**Comment by mydockfinder** [comment]
可以&nbsp; 121817313



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月18日(星期一) 下午3:10
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 会影响右键跳出？ (Issue #406)





 
不介意的话加个Q什么的  我待会发你邮箱  遇到了到时候给你看看 这会又是好的
 我也是排除了好久  才跟你反馈的
