### ISSUE TITLE
Bug when using CrystalDiskInfo

### ISSUE THREAD

**Issue by He-Jingkai** [mydockfinder/mydockfinder#410]
在运行CrystalDiskInfo时mydockerfinder会出现以下问题
1.下方任务栏不显示CrystalDiskInfo图标
2.mydockerfinder上方任务栏遮挡CrystalDiskInfo部分窗口
如下图：
The following problem occurs with mydockerfinder when running CrystalDiskInfo
1.The CrystalDiskInfo icon is not displayed in the lower task bar
2.The taskbar above mydockerfinder blocks some CrystalDiskInfo windows
As shown below:
![image](https://user-images.githubusercontent.com/72253004/180801417-38c7bbb4-c39d-45f7-aa56-2fa1d1bab2f1.png)
link to download CrystalDiskInfo: https://crystalmark.info/en/software/crystaldiskinfo/

**Comment by mydockfinder** [comment]
道理我都懂你为啥发英文
myfinder左边第二个按钮logo旁边那个，点击二级菜单，选择开启窗口边界就可以了，myfinder窗口边界就是这种情况下用的
