### ISSUE TITLE
Icons keep reappearing

### ISSUE THREAD

**Issue by atferrys** [mydockfinder/mydockfinder#414]
I tried to remove some of the default icons such as launchpad, calendar, and clock, but when I restarted the application they were added again. Is it a bug or an intended feature? If it's a feature how can I disable it?

**Comment by mydockfinder** [comment]
图标最少5个，如果dock上的图标少于5个图标配置将不会保存




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月8日(星期一) 晚上10:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] Icons keep reappearing (Issue #414)






我试图删除一些默认的图标，如启动板，日历和时钟，但当我重新启动应用程序，他们又被添加。是一个bug还是一个预期的功能？如果是一个功能怎么才能禁用它？

—
直接回复此邮件，在GitHub上查看，或取消订阅.
***@***.***与&gt;.

**Comment by atferrys** [comment]
Ok thank you, I've added more icons and now they're gone :)
