### ISSUE TITLE
Dock instantly disappears when opening applications and the taskbar is on another screen.

### ISSUE THREAD

**Issue by atferrys** [mydockfinder/mydockfinder#415]
I moved my taskbar to my second screen by unlocking and dragging it over to the other monitor.
Now when I open any application via the dock, the dock disappears instantly instead of being visible until I move the mouse away. 
And also, the dock can't be triggered until I focus on the desktop of the screen where I have the taskbar.

**Comment by mydockfinder** [comment]
好的，下个版本修复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月14日(星期天) 上午7:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] Dock instantly disappears when opening applications and the taskbar is on another screen. (Issue #415)






我把我的任务栏移动到我的第二个屏幕解锁和拖动到其他显示器。
现在，当我通过dock打开任何应用程序时，dock会立即消失，而不是可见，直到我移动鼠标。
而且，码头不能被触发，直到我把重点放在桌面上的屏幕，我有任务栏。

—
直接回复此邮件，在GitHub上查看，或取消订阅.
***@***.***与&gt;.
