### ISSUE TITLE
De-minimizing event doesn't get fired

### ISSUE THREAD

**Issue by atferrys** [mydockfinder/mydockfinder#417]
I'm using AutoHotkey to execute an action when a certain event is fired. The event waits for a specific window to be de-minimized _(maximized?)_.
While de-minimizing the window by clicking the respective icon on the taskbar fires the event, clicking it on myDock does not.

The instruction on AutoHotkey is `WinWaitActive`. Maybe myDock uses another method to re-open the minimized window, but it isn't caught by AutoHotkey.

**Comment by atferrys** [comment]
Ok seems that the event is actually fired but the window somehow doesn't react to my script instantly so I needed to add a little delay in the script (that isn't needed using the normal taskbar).
It would be cool if you could fix this without having to use the delay.

**Comment by mydockfinder** [comment]
OK, I need to adapt. May I ask what task is AutoHotkey?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月19日(星期五) 晚上8:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] De-minimizing event doesn't get fired (Issue #417)





 
Ok seems that the event is actually fired but the window somehow doesn't react to my script instantly so I needed to add a little delay in the script (that isn't needed using the normal taskbar).
 It would be cool if you could fix this without having to use the delay.
 
&mdash;

**Comment by atferrys** [comment]
The "event" is `WinWaitActive` but what the script does is: waits for the specific window to be active (or opened through the dock/taskbar) and then call an application that hooks in the DWM to apply an effect to the window.

The problem is that this happens instantly instead of waiting for the opening animation to end, making the application not work.

I think that you should make myDock wait for the animation to end and then fire the window-opening event

**Comment by mydockfinder** [comment]
我目前还不能挂接DWM进行窗口动画的渲染，我现在只是在窗口最小化或者还原的时候进行拦截，然后进行窗口截图生成D3D纹理，然后渲染动画，最后在显示或者隐藏窗口
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月22日(星期一) 晚上11:18
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] De-minimizing event doesn't get fired (Issue #417)






“事件”是WinWaitActive但是脚本所做的是：等待特定窗口处于活动状态（或通过dock/任务栏打开），然后调用挂接DWM的应用程序来对窗口应用效果。

问题是，这会立即发生，而不是等待打开动画结束，使应用程序无法工作。

我认为你应该让myDock等待动画结束，然后启动窗口打开事件

—
直接回复此邮件，在GitHub上查看，或取消订阅.
***@***.***与&gt;.

**Comment by atferrys** [comment]
So the window is shown after the d3d animation has finished rendering?

**Comment by mydockfinder** [comment]
yes



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月25日(星期四) 凌晨3:57
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] De-minimizing event doesn't get fired (Issue #417)





 
So the window is shown after the d3d animation has finished rendering?
 
&mdash;
