### ISSUE TITLE
My dock 螢幕左右下角觸發功能

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#418]
使用my dock 螢幕左下角觸發功能，並設定為顯示所有螢幕，
發現這個功能好像並無法及時觸發，有很長的時間延遲? 或是根本沒作用
導致不太能使用這個功能

PS. 另外，這個左右下角觸發功能，可以增加自訂組合快捷鍵的功能嗎? 
這樣有些快捷鍵 可以在滑鼠滑到左右下角時，就幫忙執行快捷鍵組合，
這樣功能應用性就可以更拉高了。

**Comment by mydockfinder** [comment]
好像有很多人反馈左下角总失灵，但是我自己测试真的没事。。。。。
这些细节功能要等我把大框架的功能都加完了，慢慢研究




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月25日(星期四) 下午3:38
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] My dock 螢幕左右下角觸發功能 (Issue #418)





 
使用my dock 螢幕左下角觸發功能，並設定為顯示所有螢幕，
 發現這個功能好像並無法及時觸發，有很長的時間延遲? 或是根本沒作用
 導致不太能使用這個功能
 
PS. 另外，這個左右下角觸發功能，可以增加自訂組合快捷鍵的功能嗎?
 這樣有些快捷鍵 可以在滑鼠滑到左右下角時，就幫忙執行快捷鍵組合，
 這樣功能應用性就可以更拉高了。

**Comment by linitfor** [comment]
應該是說如果多幾次重新把滑鼠滑到左下角幾次 並加上滑鼠點擊，他是有概率會觸發的，
而且有趣的是當觸發後，立即再測試重新觸發，第二次重新測試，速度就會變快，
也比較容易成功的。

PS. 右下角觸發機率比較高，好像也跟目前開啟的視窗程式有關，感覺有點複雜....

不過就感謝大大回復喔，辛苦啦! 大大真的很強大，增加了很多實用的功能喔!
