### ISSUE TITLE
希望能够设置 dock 隐藏前停留时间

### ISSUE THREAD

**Issue by shenxin-karl** [mydockfinder/mydockfinder#421]
显示 dock 后, 至少经过 n 秒才会触发自动隐藏

**Comment by mydockfinder** [comment]
emmmmm 不太好弄




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月27日(星期六) 凌晨1:24
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] 希望能够设置 dock 隐藏前停留时间 (Issue #421)





 
显示 dock 后, 至少经过 n 秒才会触发自动隐藏

**Comment by shenxin-karl** [comment]
emmmm 好吧
