### ISSUE TITLE
Issue: Launchpad icons do not save their position if they are renamed

### ISSUE THREAD

**Issue by TRINCETT** [mydockfinder/mydockfinder#422]
If you change the name of the icons of the launchpad, it causes that every time the program starts, its position is restarted

https://user-images.githubusercontent.com/93570862/187016857-7fc45078-96ec-4d77-91a8-05f66e1584a9.mp4

**Comment by mydockfinder** [comment]
OK




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月27日(星期六) 中午1:50
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] Issue: Launchpad icons do not save their position if they are renamed (Issue #422)





 
If you change the name of the icons of the launchpad, it causes that every time the program starts, its position is restarte
 
https://user-images.githubusercontent.com/93570862/187016857-7fc45078-96ec-4d77-91a8-05f66e1584a9.mp4
 
d

**Comment by TRINCETT** [comment]
Solved !
