### ISSUE TITLE
屏幕圆角只在偏好设置打开的情况下有效

### ISSUE THREAD

**Issue by Pylogmon** [mydockfinder/mydockfinder#424]
偏好设置关闭之后，屏幕上面两个角恢复直角，下面还是圆角

**Comment by Pylogmon** [comment]
圆角调整到最大之后发现，是被顶栏挡住了
![image](https://user-images.githubusercontent.com/59004461/187393215-51a6bc58-ff1b-47f3-8106-6e0eed589600.png)

**Comment by Pylogmon** [comment]
进一步测试后发现，只有在桌面会触发，还有应用最大化启动的时候概率触发

**Comment by Pylogmon** [comment]
启动edge后的状态：（鼠标移上去之后会恢复圆角）
![image](https://user-images.githubusercontent.com/59004461/187394025-9fff8c26-4f58-4c24-aa30-2e976d5efbfb.png)
桌面的状态：
![image](https://user-images.githubusercontent.com/59004461/187394229-5d1cbbe1-4905-4a3e-a802-6ebb66bb8e31.png)

**Comment by mydockfinder** [comment]
重启就好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月30日(星期二) 下午4:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 屏幕圆角只在偏好设置打开的情况下有效 (Issue #424)





 
启动edge后的状态：（鼠标移上去之后会恢复圆角）
 
 桌面的状态：
 
 
&mdash;

**Comment by Pylogmon** [comment]
> 重启就好了

问题还是存在

**Comment by mydockfinder** [comment]
是最新版1.8.9.5吗&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月30日(星期二) 晚上9:47
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 屏幕圆角只在偏好设置打开的情况下有效 (Issue #424)





  
重启就好了
  
问题还是存在

**Comment by Pylogmon** [comment]
> 是最新版1.8.9.5吗&nbsp;

是测试版1.8.9.6

**Comment by mydockfinder** [comment]
没事，下个版本改超级置顶了，屏幕圆角强制超级置顶就不会被挡住了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月30日(星期二) 晚上10:48
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 屏幕圆角只在偏好设置打开的情况下有效 (Issue #424)





  
是最新版1.8.9.5吗 
  
是测试版1.8.9.6
 
&mdash;
