### ISSUE TITLE
Myfinder 選擇顯示在所有螢幕的放大倍率

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#428]
請問一下，Myfinder 當在多螢幕同時顯示下，且啟用顯示在所有螢幕上時，
是不是就無法個別設定Myfinder在不同螢幕下的放大倍率，
好像只有多螢幕下，且只在顯示在單一螢幕上時，才可以個別設定對應的解析度。

**Comment by mydockfinder** [comment]
是的，因为所有屏幕同时显示都是主屏幕的镜像复制，不是单独渲染为了节省资源




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月13日(星期二) 上午10:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] Myfinder 選擇顯示在所有螢幕的放大倍率 (Issue #428)





 
請問一下，Myfinder 當在多螢幕同時顯示下，且啟用顯示在所有螢幕上時，
 是不是就無法個別設定Myfinder在不同螢幕下的放大倍率，
 好像只有多螢幕下，且只在顯示在單一螢幕上時，才可以個別設定對應的解析度。

**Comment by linitfor** [comment]
那有機會在同時開啟多螢幕顯示時，如果資源使用上還可以接受的話，提供個別顯示倍率的選項嗎? 
還是這樣的設計不好處理?

**Comment by linitfor** [comment]
因為myfinder 在工作上的實用性很高，已取代原有windows 功能，但我的兩個顯示器倍率有差異，導致雙開的情況下，低顯示器的myfinder 變得很大，造成有點占視窗大小。

**Comment by mydockfinder** [comment]
不是很好弄，不过也不是完全不能实现，不过缩放肯定是不如实时渲染的清楚



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月13日(星期二) 上午10:43
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Myfinder 選擇顯示在所有螢幕的放大倍率 (Issue #428)





 
因為myfinder 在工作上的實用性很高，已取代原有windows 功能，但我的兩個顯示器倍率有差異，導致雙開的情況下，低顯示器的myfinder 變得很大，造成有點占視窗大小。
 
&mdash;

**Comment by linitfor** [comment]
了解! 感謝囉! 那還是以您的布局前進吧!
