### ISSUE TITLE
Second monitor

### ISSUE THREAD

**Issue by abcen7** [mydockfinder/mydockfinder#430]
Each time the panel jumps to the monitor where the application was highlighted

**Comment by mydockfinder** [comment]
偏好设置-通用-选择dock所在屏幕
myfinder也是这样设置




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月19日(星期一) 凌晨1:51
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] Second monitor (Issue #430)





 
Each time the panel jumps to the monitor where the application was highlighted

**Comment by abcen7** [comment]
Thanks!
