### ISSUE TITLE
希望优化下myDock的智能隐藏模式

### ISSUE THREAD

**Issue by zhuang-xd** [mydockfinder/mydockfinder#440]
如果多任务分屏的情况下，靠近myDock一侧的应用失去焦点，就会自动弹出
<img src="https://c2.im5i.com/2022/10/10/TvI95.gif" style="zoom: 100%" />

**Comment by mydockfinder** [comment]
没有问题啊我刚给测试了一下，能不能拍个视频




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月10日(星期一) 下午2:09
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] 希望优化下自动隐藏模式 (Issue #440)





 
如果多任务分屏的情况下，靠近myDock一侧的应用失去焦点，就会自动弹出

**Comment by zhuang-xd** [comment]
myDock在底部是正常的，但我把它设置在了左侧
![GIF 2022-10-10 13-46-35](https://user-images.githubusercontent.com/60739949/194808797-c0553559-be84-46f0-a916-f1554a3c82fb.gif)

**Comment by mydockfinder** [comment]
那这就不好办了。。。。。。。。&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月10日(星期一) 下午2:28
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 希望优化下myDock的智能隐藏模式 (Issue #440)





 
myDock在底部是正常的，但我把它设置在了左侧
