### ISSUE TITLE
Folder icon keeps getting resetted on restart.

### ISSUE THREAD

**Issue by atferrys** [mydockfinder/mydockfinder#442]
I tried to edit the icon of a folder I added to myDock. By default, it's only a blue folder with no background, so I changed the Icon scale slightly to make the rounded white background appear.
But, when I restart the computer or the application itself, the icon turns back to a blue folder without the edits I made (Obviously, I applied the changes first.).

**Comment by mydockfinder** [comment]
应该是图标配置没有成功保存的问题，可以看一下程序安装目录png文件夹里面有没有对应修改文件夹的图片，如果没有就是保存失败了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月13日(星期四) 凌晨3:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] Folder icon keeps getting resetted on restart. (Issue #442)





 
我尝试编辑我添加到 myDock 的文件夹的图标。默认情况下，它只是一个没有背景的蓝色文件夹，因此我稍微更改了图标比例，以使圆形白色背景显示。
但是，当我重新启动计算机或应用程序本身时，图标会变回蓝色文件夹，而没有我所做的编辑（显然，我首先应用了更改）。
 
—
 直接回复此电子邮件、在 GitHub 上查看或取消订阅。
您收到此消息是因为您订阅了此线程。Message ID: ***@***.***&gt;

**Comment by atferrys** [comment]
I'm not using a custom icon, I'm only resizing the existing one. So it should be saved...

**Comment by mydockfinder** [comment]
我没有明白，能不能录个视频
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月13日(星期四) 晚上10:59
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Folder icon keeps getting resetted on restart. (Issue #442)





 
I'm not using a custom icon, I'm only resizing the existing one. So it should be saved...

**Comment by atferrys** [comment]
Here you are!
https://i.imgur.com/9hbREbr.mp4

**Comment by mydockfinder** [comment]
我测试了一下没有问题，看一下程序目录里面png文件夹下有没有自定义后的对应图片
![image](https://user-images.githubusercontent.com/32895737/196037892-dc05b8db-14f8-4243-8469-078b56c94498.png)

**Comment by atferrys** [comment]
There isn't any folder icon in the png folder

**Comment by mydockfinder** [comment]
那就是文件夹目录权限问题了，是程序不能往文件夹里面保存文件，可以先备份配置到steam云，然后卸载，安装到其他分区不是C盘的分区




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月16日(星期天) 晚上9:36
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Folder icon keeps getting resetted on restart. (Issue #442)





 
There isn't any folder icon in the png folder
 
&mdash;

**Comment by atferrys** [comment]
But with other icons it worked, in fact there are some other icons in the png folder...

**Comment by atferrys** [comment]
Can I give it RW permissions without changing the installation directory?

**Comment by mydockfinder** [comment]
那咱能不能一次把话说全了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月16日(星期天) 晚上9:40
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Folder icon keeps getting resetted on restart. (Issue #442)





 
But with other icons it worked, in fact there are some other icons in the png folder...
 
&mdash;

**Comment by mydockfinder** [comment]
如果只是那一个文件夹图标这样的话就不是权限问题了，应该是别的问题，但是我也不知道怎么回事了。。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月16日(星期天) 晚上9:41
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Folder icon keeps getting resetted on restart. (Issue #442)





 
Can I give it RW permissions without changing the installation directory?
 
&mdash;

**Comment by atferrys** [comment]
![image](https://user-images.githubusercontent.com/61624086/196038750-9d02b850-a69d-4a16-b416-cc9a7206973d.png)
Sorry? Wdym?

**Comment by atferrys** [comment]
> 如果只是那一个文件夹图标这样的话就不是权限问题了，应该是别的问题，但是我也不知道怎么回事了。。。。

How can I help figure that out?

**Comment by mydockfinder** [comment]
你可以试试添加其他不同的文件夹。然后修改图标看看，是不是也会重置




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月16日(星期天) 晚上9:44
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Folder icon keeps getting resetted on restart. (Issue #442)





  
如果只是那一个文件夹图标这样的话就不是权限问题了，应该是别的问题，但是我也不知道怎么回事了。。。。
  
How can I help figure that out?
 
&mdash;

**Comment by atferrys** [comment]
Ok, I tried with another folder that I had lying on the desktop and it didn't reset. Maybe the problem is that the first folder is the root directory of another drive?

**Comment by atferrys** [comment]
Here:
![image](https://user-images.githubusercontent.com/61624086/196039050-a1a7de39-f779-49f5-8821-5b6900369acb.png)

**Comment by mydockfinder** [comment]
应该是没有区别，或者试一下删除这个图标，然后重新添加移除，再修改图标试试



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月16日(星期天) 晚上9:50
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Folder icon keeps getting resetted on restart. (Issue #442)





 
Here:
 
 
&mdash;

**Comment by atferrys** [comment]
Re-added and it still resets... :(

**Comment by mydockfinder** [comment]
我测试了一下，根目录确实会重置，是bug了，修改版本修复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月16日(星期天) 晚上9:56
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Folder icon keeps getting resetted on restart. (Issue #442)





 
Re-added and it still resets... :(
 
&mdash;

**Comment by atferrys** [comment]
Soo... I need to select the beta branch on steam?

**Comment by mydockfinder** [comment]
是下次更新的时候修复，我还没更新了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月16日(星期天) 晚上10:04
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Folder icon keeps getting resetted on restart. (Issue #442)





 
Soo... I need to select the beta branch on steam?
 
&mdash;

**Comment by atferrys** [comment]
Ok, thank you!

**Comment by mydockfinder** [comment]
不客气




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月16日(星期天) 晚上10:08
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Folder icon keeps getting resetted on restart. (Issue #442)





 
Ok, thank you!
 
&mdash;
