### ISSUE TITLE
平板螢幕鎖定功能加入到myfinder 按鈕上

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#443]
![image](https://user-images.githubusercontent.com/58168507/196357769-15da7379-8c2f-47fe-8e96-0a8bf969230e.png)
請問有辦法把旋轉鎖定這個功能

加入到myfinder 上嗎?
或這可以整合進去下面這個panel
![image](https://user-images.githubusercontent.com/58168507/196358860-7f8d8e7d-e721-4868-9cee-6c2f62400db7.png)

**Comment by mydockfinder** [comment]
我想过，但是不会。。。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月18日(星期二) 下午3:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 平板螢幕鎖定功能加入到myfinder 按鈕上 (Issue #443)





 

 請問有辦法把旋轉鎖定這個功能
 
加入到myfinder 上嗎?
 或這可以整合進去下面這個panel

**Comment by linitfor** [comment]
ok! 沒關係 現有功能就很棒了 感謝喔!
