### ISSUE TITLE
行事曆/時鐘/天氣預報 自定義建議 App 選項

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#446]
請問有機會開放行事曆按鈕可以自己定義連結到其他款的行事曆
例如: 當我點擊該行事曆時，他會打開Google Calendar

另外，目前點擊時鐘/天氣預報 App icon，目前是不會連結到任何程式的，
是否也可提供自定義連結啟動其他的APP
舉例.1 : 時鐘部分 可以連結到 Windows 鬧鐘與時鐘
https://www.microsoft.com/store/productId/9WZDNCRFJ3PR

舉例.2 : 天氣預報 可以連結到 MSN 天氣
https://www.microsoft.com/store/productId/9WZDNCRFJ3Q2

**Comment by mydockfinder** [comment]
可以



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月25日(星期二) 中午1:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 行事曆/時鐘/天氣預報 自定義建議 App 選項 (Issue #446)





 
請問有機會開放行事曆按鈕可以自己定義連結到其他款的行事曆
 例如: 當我點擊該行事曆時，他會打開Google Calendar
 
另外，目前點擊時鐘/天氣預報 App icon，目前是不會連結到任何程式的，
 是否也可提供自定義連結啟動其他的APP
 舉例.1 : 時鐘部分 可以連結到 Windows 鬧鐘與時鐘
 https://www.microsoft.com/store/productId/9WZDNCRFJ3PR
 
舉例.2 : 天氣預報 可以連結到 MSN 天氣
 https://www.microsoft.com/store/productId/9WZDNCRFJ3Q2

**Comment by linitfor** [comment]
請問這個部分有規畫什麼時候會實現嗎?

**Comment by mydockfinder** [comment]
今晚更新就加入了
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月16日(星期三) 下午3:43
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 行事曆/時鐘/天氣預報 自定義建議 App 選項 (Issue #446)





 
請問這個部分有規畫什麼時候會實現嗎?

**Comment by linitfor** [comment]
感謝感謝! 1.9.3 這版 天氣跟時鐘的部分 有看到這個部份了
如果 行事曆也多提供自訂連結到其他自定義的 行事曆程式 就更棒了
這版 昨晚測試到現在 mydock 在多桌面切換 與偵測程式顯示icon 感覺有變更穩定了 
感謝大大提供這麼實用功能喔!

**Comment by mydockfinder** [comment]
谢谢，话说行事曆想绑定在哪个图标，行事曆是啥。。。。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月17日(星期四) 上午10:36
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 行事曆/時鐘/天氣預報 自定義建議 App 選項 (Issue #446)





 
感謝感謝! 1.9.3 這版 天氣跟時鐘的部分 有看到這個部份了
 如果 行事曆也多提供自訂連結到其他自定義的 行事曆程式 就更棒了
 這版 昨晚測試到現在 mydock 在多桌面切換 與偵測程式顯示icon 感覺有變更穩定了
 感謝大大提供這麼實用功能喔!
 
&mdash;

**Comment by linitfor** [comment]
我想綁定Google calendar 
這是用Microsoft Edge 製作 Google calendar 成為一個應用程式捷徑
如果我們可以自定義點選行事曆按鈕 會開啟哪個 app 的話，我會去連結這個Google calendar 應用程式捷徑

想法是保留現有行事曆在myDock 上，可以顯示今天日期，但點選行事曆按鈕時，不使用Windows 內建行事曆，而是開啟我指定的行事曆網頁。

會想要改用Google 行事曆，是因為windows 內建行事曆，在提供顯示線上會議連結，這個功能做得不太好，我要點選到內頁，程式才會識別到連結網址，他目前在行事曆主介面提供的網址都是純文字介面，我們要全選複製該連結，開啟網頁並貼上網址才能開啟視訊會議。
Google calendar 在滑鼠移到會議行程，就會浮出頁面，並提供線上會議網址連結，提供給我們開啟視訊會議連結，相對方便不少。

**Comment by mydockfinder** [comment]
edge是可以用PWA程序的啊
你可以把Google calendar做成PWA绑定在dock




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月17日(星期四) 中午12:51
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 行事曆/時鐘/天氣預報 自定義建議 App 選項 (Issue #446)





 
我想綁定Google calendar
 這是用Microsoft Edge 製作 Google calendar 成為一個應用程式捷徑
 如果我們可以自定義點選行事曆按鈕 會開啟哪個 app 的話，我會去連結這個Google calendar 應用程式捷徑
 
想法是保留現有行事曆在myDock 上，可以顯示今天日期，但點選行事曆按鈕時，不使用Windows 內建行事曆，而是開啟我指定的行事曆網頁。
 
會想要改用Google 行事曆，是因為windows 內建行事曆，在提供顯示線上會議連結，這個功能做得不太好，我要點選到內頁，程式才會識別到連結網址，他目前在行事曆主介面提供的網址都是純文字介面，我們要全選複製該連結，開啟網頁並貼上網址才能開啟視訊會議。
 Google calendar 在滑鼠移到會議行程，就會浮出頁面，並提供線上會議網址連結，提供給我們開啟視訊會議連結，相對方便不少。
 
&mdash;
