### ISSUE TITLE
Myfinder 增加 win+A 按鈕，解決平板模式螢幕旋轉鎖定功能。

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#447]
可否在myfinder 加上一個按鈕提供 win + A 這個指令的快捷鍵，
這樣可以調出Windows 內建的Quick setting
這樣就可以在平板模式時，利用Quick setting 來決定要不要讓螢幕旋轉了。

**Comment by mydockfinder** [comment]
右键点击myfinder控制中心按钮就可以了，触屏就是按住了控制中心




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月29日(星期六) 下午3:32
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] Myfinder 增加 win+A 按鈕，解決平板模式螢幕旋轉鎖定功能。 (Issue #447)





 
可否在myfinder 加上一個按鈕提供 win + A 這個指令的快捷鍵，
 這樣可以調出Windows 內建的Quick setting
 這樣就可以在平板模式時，利用Quick setting 來決定要不要讓螢幕旋轉了。

**Comment by linitfor** [comment]
ok ok 感謝
