### ISSUE TITLE
5.9.9.3启动台图标丢失

### ISSUE THREAD

**Issue by dyphire** [mydockfinder/mydockfinder#45]
5.9.9.3启动台第一次点击会正常加载图标，之后再点开就是一片空白了，图标丢失。
![image](https://user-images.githubusercontent.com/61936050/118647315-c8578380-b813-11eb-900b-5d189c4f33c2.png)

**Comment by mydockfinder** [comment]
目前临时的解决办法，重启dock以后启动台有图标，然后把一个不常用的图标拽到第二屏幕，然后在显示启动台没有图标时翻页就出来了

**Comment by dyphire** [comment]
> 目前临时的解决办法，重启dock以后启动台有图标，然后把一个不常用的图标拽到第二屏幕，然后在显示启动台没有图标时翻页就出来了

其实还有个问题，部分图标显示不正常，过小了。
![image](https://user-images.githubusercontent.com/61936050/118648398-ec679480-b814-11eb-80e1-9fa65f2c6230.png)

**Comment by mydockfinder** [comment]
图标检测的问题 还没来及修复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月18日(星期二) 晚上8:09
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] 5.9.9.3启动台图标丢失 (#45)





  
目前临时的解决办法，重启dock以后启动台有图标，然后把一个不常用的图标拽到第二屏幕，然后在显示启动台没有图标时翻页就出来了
  
其实还有个问题，部分图标显示不正常，过小了。
