### ISSUE TITLE
分享 Stage Mananger 開發資訊

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#452]
大大，我發現有其他作者正在實作Stage Manager 了，
不知道我們未來有沒有機會整合這個部分，這個功能在foucs mode，感覺還不錯喔!

https://github.com/awaescher/StageManager

**Comment by mydockfinder** [comment]
会的，不过我的做法和他的原理不一样，我要加动画的，而且winui做窗口预览很轻松效果也会更好




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月8日(星期二) 下午4:48
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] 分享 Stage Mananger 開發資訊 (Issue #452)





 
大大，我發現有其他作者正在實作Stage Manager 了，
 不知道我們未來有沒有機會整合這個部分，這個功能在foucs mode，感覺還不錯喔!
 
https://github.com/awaescher/StageManager

**Comment by linitfor** [comment]
酷喔 大大厲害 他的版本的確只有 snapshot，沒辦法像大大的mydock 預覽視窗是可以即時的，
目前的方法也沒辦法把視窗回放到對應位置，跟mac 版還有點距離，期待大大的版本啦 ^.^b

**Comment by mydockfinder** [comment]
不要着急，慢工出细活




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月11日(星期五) 中午11:30
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 分享 Stage Mananger 開發資訊 (Issue #452)





 
酷喔 大大厲害 他的版本的確只有 snapshot，沒辦法像大大的mydock 預覽視窗是可以即時的，
 目前的方法也沒辦法把視窗回放到對應位置，跟mac 版還有點距離，期待大大的版本啦 ^.^b
 
&mdash;

**Comment by yarikbright** [comment]
Can you add the ability to turn off animations in the Stage Manager? Or add animation speed setting?

**Comment by mydockfinder** [comment]
关闭动画不是很好做，因为窗口层次的问题，有可能还原动画的窗口层次会渲染错误，比如最下面的窗口渲染在上面了
动画速度可以加
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月6日(星期四) 晚上11:38
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 分享 Stage Mananger 開發資訊 (Issue #452)






能否在舞台管理器中添加关闭动画的功能？或者添加动画速度设置？

—
直接回复这封邮件，在GitHub上查看或取消订阅.
***@***.***与&gt;.
