### ISSUE TITLE
Battery information

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#455]
Battery information 
除了剩餘時間，有辦法額外提供Battery 耗損比例資訊嗎?

**Comment by mydockfinder** [comment]
不会获取那些信息。。。。。。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月10日(星期四) 下午5:10
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] Battery information (Issue #455)





 
Battery information
 除了剩餘時間，有辦法額外提供Battery 耗損比例資訊嗎?

**Comment by linitfor** [comment]
Windows 有內建查詢功能:
CMD terminal 鍵入以下資訊:
powercfg/batteryreport

參考資料:
https://www.cool3c.com/article/130219

所查詢出的資訊 有提供FULL CHARGE CAPACITY/DESIGN CAPACITY，兩者相除就是電池健康度。
![image](https://user-images.githubusercontent.com/58168507/201257876-2b31be95-0df4-458e-a96d-fde7377c0fb1.png)

**Comment by mydockfinder** [comment]
powercfg/batteryreport : 无法将“powercfg/batteryreport”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称
的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ powercfg/batteryreport
+ ~~~~~~~~~~~~~~~~~~~~~~
&nbsp; &nbsp; + CategoryInfo&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; : ObjectNotFound: (powercfg/batteryreport:String) [], CommandNotFoundException
&nbsp; &nbsp; + FullyQualifiedErrorId : CommandNotFoundException



不行。。。。。。
我是win11beta
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月11日(星期五) 中午11:42
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Battery information (Issue #455)





 
Windows 有內建查詢功能:
 CMD terminal 鍵入以下資訊:
 powercfg/batteryreport
 
參考資料:
 https://www.cool3c.com/article/130219
 
所查詢出的資訊 有提供FULL CHARGE CAPACITY/DESIGN CAPACITY，兩者相除就是電池健康度。

**Comment by mydockfinder** [comment]
啊 错了 我是台式机，我回来用笔记本试试
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月11日(星期五) 中午11:42
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Battery information (Issue #455)





 
Windows 有內建查詢功能:
 CMD terminal 鍵入以下資訊:
 powercfg/batteryreport
 
參考資料:
 https://www.cool3c.com/article/130219
 
所查詢出的資訊 有提供FULL CHARGE CAPACITY/DESIGN CAPACITY，兩者相除就是電池健康度。
