### ISSUE TITLE
Mydock 上的保留icon 會莫名被移除

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#456]
好像在我開的程式數量多到一個程度時，已經釘選保留在mydock 上的icon 會有一個小概率莫名被移除，
目前最常遇到被移除的是edge icon，然後onenote icon 也曾經被移除過。

這個狀況，我有確定過我有勾選保留icon 在dock 上，也有勾選鎖定圖示拖動，避免滑鼠把icon 拉動移除。

**Comment by mydockfinder** [comment]
应该是bug，之前也有人反馈了，目前还没找到原因



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月16日(星期三) 下午3:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] Mydock 上的保留icon 會莫名被移除 (Issue #456)





 
好像在我開的程式數量多到一個程度時，已經釘選保留在mydock 上的icon 會有一個小概率莫名被移除，
 目前最常遇到被移除的是edge icon，然後onenote icon 也曾經被移除過。
 
這個狀況，我有確定過我有勾選保留icon 在dock 上，也有勾選鎖定圖示拖動，避免滑鼠把icon 拉動移除。

**Comment by eliaszon** [comment]
我也有一样的问题。很久了
