### ISSUE TITLE
Notification type 建議

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#461]
大大有沒有考慮接管windows notificaiton呢?
原先使用大大的設定為消息提示時，
這類訊息程式跳出訊息通知時會出現右上跟右下同時出現通知
![image](https://user-images.githubusercontent.com/58168507/204193433-64e5f223-4c21-4024-bd93-d5ba233b8b49.png)

發現有其他開發方可以把windows notification 完整往右上方移動
這樣的確訊息出現的時候，也比較不會擋到mydocker
感覺這樣修改會更貼近使用

其他參考資訊
https://github.com/SamarthCat/notifications-at-top

**Comment by mydockfinder** [comment]
也可以，但是我还是想彻底接管系统通知，但是我现在能做的就是只能显示文字，点击不能激活通知对应的操作




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月28日(星期一) 中午12:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] Notification type 建議 (Issue #461)





 
大大有沒有考慮接管windows notificaiton呢?
 原先使用大大的設定為消息提示時，
 這類訊息程式跳出訊息通知時會出現右上跟右下同時出現通知
 
 
發現有其他開發方可以把windows notification 完整往右上方移動
 這樣的確訊息出現的時候，也比較不會擋到mydocker
 感覺這樣修改會更貼近使用
 
其他參考資訊
 https://github.com/SamarthCat/notifications-at-top

**Comment by linitfor** [comment]
如果能做到激活對應操作，這樣的功能十分完整耶，期待喔!
不過如果還不行，先能顯示對應的文字，這樣也已經很棒了，有考慮預計什麼時候，先提供option讓我們試試看嗎?

**Comment by linitfor** [comment]
Hi mydockfinder,
我剛修改了其他作者的Code 後，成功把通知移到右上角，且可以激活對應操作了!!

**Comment by mydockfinder** [comment]
那个代码只适用于英文操作系统，换个语言就失效了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月29日(星期二) 中午1:42
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Notification type 建議 (Issue #461)





 
Hi mydockfinder,
 我剛修改了其他作者的Code 後，成功把通知移到右上角，且可以激活對應操作了!!
 
&mdash;

**Comment by linitfor** [comment]
大大內行呀，期待大大整合完的版本啦!
Stage manager 測試的還順利嗎?
這周什麼時候可以看到，真期待呀 ^.^

**Comment by mydockfinder** [comment]
周日差不多，不过bug确实有点多，还是发测试通道，这是第一版后面慢慢优化吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月30日(星期三) 晚上9:54
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Notification type 建議 (Issue #461)





 
大大內行呀，期待大大整合完的版本啦!
 Stage manager 測試的還順利嗎?
 這周什麼時候可以看到，真期待呀 ^.^
 
&mdash;

**Comment by linitfor** [comment]
嗯嗯 沒關係 好事多磨
可以放出來吧 😄😁
讓我們幫忙測試看看

**Comment by linitfor** [comment]
今天幾點公布新版呀 好期待呀👀👀

**Comment by mydockfinder** [comment]
下午，不好说，不过在做最后的准备
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月4日(星期天) 中午1:05
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Notification type 建議 (Issue #461)





 
今天幾點公布新版呀 好期待呀👀👀

**Comment by linitfor** [comment]
好哦 辛苦啦狂刷狀態
等待大大您的更新
立馬幫忙測試😁😁

**Comment by mydockfinder** [comment]
马上 正在编译，差不多十几分钟吧
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月4日(星期天) 下午2:29
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Notification type 建議 (Issue #461)





 
好哦 辛苦啦狂刷狀態
 等待大大您的更新
 立馬幫忙測試😁😁
