### ISSUE TITLE
你好，能否请求做一下双屏的支持。

### ISSUE THREAD

**Issue by KyoMio** [mydockfinder/mydockfinder#464]
双屏使用会出现dock在两个屏幕来回切换的情况，同时桌面图标也会两个屏幕互换。能不能设置为固定一个屏幕显示或者两块屏幕都显示。

另外就是副屏的任务栏无法隐藏，鼠标移过去还是会升起来。

**Comment by KyoMio** [comment]
无事了，我没看到dock和finder有单独的显示屏幕设置。zzz
不过还是建议一下能否把副屏的任务栏也给隐藏掉。

**Comment by mydockfinder** [comment]
偏好设置里面，勾选启动时隐藏任务栏，然后下面选隐藏所有屏幕任务栏就可以了，不过系统设置里面任务栏也有设置的，显示其他屏幕任务栏取消就可以了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月1日(星期四) 下午5:36
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [mydockfinder/mydockfinder-for-Win10-Win11] 你好，能否请求做一下双屏的支持。 (Issue #464)





 
无事了，我没看到dock和finder有单独的显示屏幕设置。zzz
 不过还是建议一下能否把副屏的任务栏也给隐藏掉。
