### ISSUE TITLE
能开放其他付费方法吗？

### ISSUE THREAD

**Issue by xiaozhinian-g** [mydockfinder/mydockfinder#470]
不想安装steam，有没有其他购买的地方？

**Comment by mydockfinder** [comment]
目前还没有，微软商店上架收费的exe挺麻烦的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月9日(星期五) 晚上10:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 能开放其他付费方法吗？ (Issue #470)





 
不想安装steam，有没有其他购买的地方？
