### ISSUE TITLE
QQ聊天窗口台前调度调出时显示异常

### ISSUE THREAD

**Issue by Thesouth-EricWang** [mydockfinder/mydockfinder#484]
QQ聊天窗口在台前调度显示的时候会突然鬼畜一下变大，然后恢复正常
（这个还是有点影响观感的🤣）
![QQ截图20230104234851](https://user-images.githubusercontent.com/109672389/210594595-7e564922-9903-4383-ae93-07c9f5c5fd07.jpg)

**Comment by Thesouth-EricWang** [comment]
![QQ截图20230104234851](https://user-images.githubusercontent.com/109672389/210596396-ac7c2fea-47d0-4c45-a75b-bd924fb75d72.jpg)

**Comment by Thesouth-EricWang** [comment]
刚测试了一下，目前还有钉钉、腾讯会议和网易云音乐会出现这样的bug

**Comment by Thesouth-EricWang** [comment]
目前使用下来发现好像所有的应用都有几率触发这个bug，不知道什么原理，个人猜测有可能是因为后台挂得太久导致不渲染

**Comment by mydockfinder** [comment]
哦 没事 这是新版的bug，下个版本修复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月5日(星期四) 下午2:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] QQ聊天窗口台前调度调出时显示异常 (Issue #484)





 
目前使用下来发现好像所有的应用都有几率触发这个bug，不知道什么原理，个人猜测有可能是因为后台挂得太久导致不渲染
 
&mdash;
