### ISSUE TITLE
网易云歌词无法隐藏

### ISSUE THREAD

**Issue by Thesouth-EricWang** [mydockfinder/mydockfinder#486]
更新1.9.7.2版本后网易云音乐的歌词无法在桌面隐藏了，在finder里点击歌词没反应

**Comment by mydockfinder** [comment]
是不是两个屏幕，用一个屏幕试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月9日(星期一) 晚上7:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 网易云歌词无法隐藏 (Issue #486)





 
更新1.9.7.2版本后网易云音乐的歌词无法在桌面隐藏了，在finder里点击歌词没反应

**Comment by Thesouth-EricWang** [comment]
是单屏，更新前没这个问题，更新完了就这样了

**Comment by mydockfinder** [comment]
那不应该啊
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月9日(星期一) 晚上7:52
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 网易云歌词无法隐藏 (Issue #486)





 
是单屏，更新前没这个问题，更新完了就这样了

**Comment by Thesouth-EricWang** [comment]
就是这样，点了也没反应，不知道什么原因，更新之前还好好的呢
![20230109195526](https://user-images.githubusercontent.com/109672389/211302504-4ec58af9-fa2f-4c1c-9e5a-d434c3d95af7.png)

**Comment by mydockfinder** [comment]
但是我很久没动过歌词了
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月9日(星期一) 晚上7:56
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 网易云歌词无法隐藏 (Issue #486)





 
就是这样，点了也没反应，不知道什么原因，更新之前还好好的呢

**Comment by Thesouth-EricWang** [comment]
确实是，这次更新按理来说不关歌词的事，但是确实不好用了
有没有可能是调音量按钮无意间干扰到这方面的功能
我感觉应该跟台前调度没关系，因为不管开还是关台前调度都有这种情况

**Comment by mydockfinder** [comment]
音量改的是音量二级菜单不是音量的按钮啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月9日(星期一) 晚上8:04
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 网易云歌词无法隐藏 (Issue #486)





 
确实是，这次更新按理来说不关歌词的事，但是确实不好用了
 有没有可能是调音量按钮无意间干扰到这方面的功能
 我感觉应该跟台前调度没关系，因为不管开还是关台前调度都有这种情况
 
&mdash;

**Comment by Thesouth-EricWang** [comment]
那就不知道是怎么回事了🤣也有可能是网易云事

**Comment by mydockfinder** [comment]
我刚刚测试了一下QQ音乐没有问题
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月9日(星期一) 晚上8:07
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 网易云歌词无法隐藏 (Issue #486)





 
那就不知道是怎么回事了🤣也有可能是网易云事

**Comment by Thesouth-EricWang** [comment]
啊，我刚刚重启了下网易云，没事了
有可能又卡了什么奇奇怪怪的bug
