### ISSUE TITLE
How to show tray icon on the top menu bar?

### ISSUE THREAD

**Issue by zina0316** [mydockfinder/mydockfinder#489]
I have a lot of tray icons, if I use mydock, they won't show up, are there any ways to show them?

**Comment by mydockfinder** [comment]
目前只能添加系统图标-托盘图标，然后点击mydock添加的托盘图标可以显示所有的托盘，就是需要每次都点击一次。不能像myfinder直接的操作




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月15日(星期天) 下午4:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] How to show tray icon on the top menu bar? (Issue #489)






我有很多托盘图标，如果我用mydock，就显示不出来了，有什么方法可以显示出来吗？

—
直接回复此邮件，在GitHub上查看或取消订阅.
***@***.***与&gt;.

**Comment by zina0316** [comment]
那有沒有辦法可以把單獨托盤圖標放到 dock 裡？

**Comment by mydockfinder** [comment]
目前不行，因为托盘图标尺寸是16*16的，dock图标都是256*256的，放大就太模糊了
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月16日(星期一) 晚上9:05
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] How to show tray icon on the top menu bar? (Issue #489)





 
那有沒有辦法可以把單獨托盤圖標放到 dock 裡？

**Comment by zina0316** [comment]
可以讓用戶自定義圖標

**Comment by mydockfinder** [comment]
目前还不支持自定义托盘图标




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月25日(星期三) 下午3:56
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] How to show tray icon on the top menu bar? (Issue #489)





 
可以讓用戶自定義圖標
 
&mdash;

**Comment by SrPhilippe** [comment]
There is a specific icon that shows all the tray icons

![image](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/20309766/08ebd6d0-56ed-464b-81ea-02c6f99279d3)

If you click there, you can click on  the left side of the icon you want to maintain fixed.

![image](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/20309766/a1d73f7a-c5b2-4d10-908f-e637ec566864)

**Comment by mydockfinder** [comment]
偏好设置-托盘，勾选在myfinder中显示所有托盘图标
Preferences - Trays, tick Show all tray icons in MyFinder
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月3日(星期一) 上午7:01
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] How to show tray icon on the top menu bar? (Issue #489)






有一个特定的图标，显示所有的托盘图标



如果你点击那里，你可以点击左侧的图标，你要保持固定。



—
直接回复此邮件，在GitHub上查看，或者取消订阅.
***@***.***与&gt;.

**Comment by zina0316** [comment]
我當時的問題是因爲我使用在github下載的舊版，我現在用 steam 的新版就沒問題了
