### ISSUE TITLE
重複出現system tray icon

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#499]
Mydockfinder 從1.9.7.5 開始會不預期重複出現system tray icon

![圖片](https://user-images.githubusercontent.com/58168507/218354058-bf796989-fa34-4451-a391-7f4ccd2e3c8f.png)

**Comment by mydockfinder** [comment]
正在查找原因，请问是重启电脑以后出现的重复图标吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月13日(星期一) 上午10:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 重複出現system tray icon (Issue #499)





 
Mydockfinder 從1.9.7.5 開始會不預期重複出現system tray icon

**Comment by linitfor** [comment]
是的

但剛剛只是休眠 後喚醒後， 某些icon 會無法顯示
![圖片](https://user-images.githubusercontent.com/58168507/218360660-1b669b75-a626-4a62-93c5-3f268a47e171.png)

**Comment by mydockfinder** [comment]
好的
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月13日(星期一) 中午11:00
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 重複出現system tray icon (Issue #499)





 
是的
 
但剛剛只是休眠 後喚醒後， 某些icon 會無法顯示

**Comment by linitfor** [comment]
請問這個問題 這周更新可以解決嗎?
icon 消失，在工作上有點困擾

**Comment by mydockfinder** [comment]
嗯 下次更新就好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月18日(星期六) 中午11:04
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 重複出現system tray icon (Issue #499)





 
請問這個問題 這周更新可以解決嗎?
 icon 消失，在工作上有點困擾
 
&mdash;
