### ISSUE TITLE
MyDockFinder freezes when maximizing windows on a seperate screen

### ISSUE THREAD

**Issue by Lappun0** [mydockfinder/mydockfinder#502]
Whenever I maximize a window on another monitor (and have the option called "Maximized windows affect Finder appearance" enabled), MyDockFinder freezes until I make the window not maximized again. Everything works fine if the option is turned off, but it is really good for consistency and so it would be really nice if it worked with multiple monitors. I also should mention that I have my finder set to be displayed on all my monitors, so thats probably why windows on seperate monitors even affect it. Im on the latest steam release, 1.9.7.7

**Comment by mydockfinder** [comment]
能不能录制一个视频，我想看一下过程




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月1日(星期三) 凌晨2:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] MyDockFinder freezes when maximizing windows on a seperate screen (Issue #502)






每当我在另一台显示器上最大化一个窗口（并启用名为“最大化窗口影响Finder外观”的选项），MyDockFinder就会冻结，直到我再次使该窗口不最大化。如果关闭该选项，一切正常，但它确实有利于一致性因此，如果它能与多个显示器一起工作，那就太好了。我还应该提到，我有我的查找器设置为显示在我所有的显示器上，所以这可能就是为什么在单独的显示器上的窗口甚至会影响它。我在最新的蒸汽发布，1.9.7.7

—
直接回复此邮件，在GitHub上查看或取消订阅.
***@***.***与&gt;.

**Comment by Lappun0** [comment]
Im sorry for the low quality, my main screen is on the left and the seperate one is on the right
https://user-images.githubusercontent.com/90772200/222148155-a5142ef2-0779-464e-9866-8b383a4d707b.mp4

After filming I also noticed that there is a lot more weird behaviour, but I can't explain it because its constantly changing, sometimes MyDockFinder will lag after maximizing a window, sometimes it will freeze, sometimes the effect doesn't work and the finder stays the same, sometimes everything works, sometimes nothing works and every window freezes MyDockFinder. I really don't know how to describe it. Also as you may saw in the video, firefox has a problem with a white line at the bottom of the screen and if you could help with that aswell I would be very happy (its visible at around 0:36)

**Comment by mydockfinder** [comment]
好的，明白了，应该是窗口拖到另一个屏幕时，窗口所在屏幕识别错误的问题，争取下个版本修复
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月1日(星期三) 晚上9:35
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] MyDockFinder freezes when maximizing windows on a seperate screen (Issue #502)






我很抱歉质量不高，我的主屏幕在左边，而另一个在右边
https://user-images.githubusercontent.com/90772200/222148155-a5142ef2-0779-464e-9866-8b383a4d707b.mp4

拍摄结束后，我还注意到，有很多更奇怪的行为，但我不能解释，因为它不断变化，有时MyDockFinder将最大化一个窗口后滞后，有时会冻结，有时效果不起作用，查找器保持不变，有时一切正常，有时什么都不起作用，每个窗口都冻结MyDockFinder。我真的不知道该怎么形容另外，正如你在视频中看到的，Firefox在屏幕底部有一条白线，如果你能帮助解决这个问题，我会很高兴。（在0点36分左右可见）

—
直接回复此邮件，在GitHub上查看或取消订阅.
***@***.***与&gt;.

**Comment by Lappun0** [comment]
The issue seems to be fixed as of 1.9.7.8, Thanks! (The white line bug is still present, but im going to close this issue for now.)

**Comment by mydockfinder** [comment]
Firefox白线是浏览器自己的白线，这个不能修复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月6日(星期一) 凌晨0:01
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] MyDockFinder freezes when maximizing windows on a seperate screen (Issue #502)





 
Closed #502 as completed.
 
&mdash;
