### ISSUE TITLE
我没有开启“开启窗口边界防止遮挡DOCK”这个选项，但是运行最大化窗口，在Dock自动隐藏后，总是底下还是有空白的地方，露出桌面壁纸

### ISSUE THREAD

**Issue by chuck00000** [mydockfinder/mydockfinder#506]
最新版本1.9.7.8还有这问题，最新win11 Dev预览版
![Screenshot 2023-03-07 090552](https://user-images.githubusercontent.com/98159699/223294043-defd85b3-b120-493c-afb8-b47c4ff311cc.png)
![Screenshot (11)](https://user-images.githubusercontent.com/98159699/223294096-cebcd962-a3c2-47e6-a144-9fe7d5556448.png)

**Comment by chuck00000** [comment]
![Screenshot 2023-03-07 092005](https://user-images.githubusercontent.com/98159699/223294752-9ba034f8-475f-41b9-b5c2-68701ddf99fd.png)

**Comment by mydockfinder** [comment]
win11dev的问题 需要在系统任务栏设置里面勾选自动隐藏任务栏




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月7日(星期二) 上午9:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 为啥我没有开启“开启窗口边界防止遮挡DOCK”这个选项，但是运行最大化窗口，在Dock自动隐藏后，总是底下还是有这么空白的地方，露出桌面壁纸 (Issue #506)





 

 
&mdash;
