### ISSUE TITLE
打开最大化软件的时候，动画末尾会往下移一点，很难受

### ISSUE THREAD

**Issue by bling-yshs** [mydockfinder/mydockfinder#507]
版本：1.9.7.8

https://user-images.githubusercontent.com/41812674/223316086-eaf0c2ef-a44b-4821-98d0-4f61e52c3f05.mp4

**Comment by mydockfinder** [comment]
确实会有点，新版本用的UWP截图可能是窗口实际尺寸不符就会有错位，我后面会优化的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月7日(星期二) 中午11:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 打开最大化软件的时候，动画末尾会往下移一点，很难受 (Issue #507)





 
版本：1.9.7.8
 
https://user-images.githubusercontent.com/41812674/223316086-eaf0c2ef-a44b-4821-98d0-4f61e52c3f05.mp4

**Comment by bling-yshs** [comment]
最新版已修复
