### ISSUE TITLE
控制台异常bug

### ISSUE THREAD

**Issue by dyphire** [mydockfinder/mydockfinder#51]
![image](https://user-images.githubusercontent.com/61936050/119592905-ea509780-be0b-11eb-80bd-2c1c34fe1f4f.png)
如图所示，控制台显示异常，这问题其实持续好几个版本了，不过之前重启后会正常，新版本触发后重启多次依然未恢复正常，且该状态cpu占用极高接近100%，极易卡死。

**Comment by mydockfinder** [comment]
目前触发原因未知，所以我在咨询每个人发生这种情况时的操作，这样之前有没有什么预兆，打开了什么软件或者点了哪里，或者有没有什么内存清理的软件后台清理内存了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月26日(星期三) 上午10:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder] 控制台异常bug (#51)





 

 如图所示，控制台显示异常，这问题其实持续好几个版本了，不过之前重启后会正常，新版本触发后重启多次依然未恢复正常，且该状态cpu占用极高接近100%，极易卡死。

**Comment by dyphire** [comment]
> 目前触发原因未知，所以我在咨询每个人发生这种情况时的操作，这样之前有没有什么预兆，打开了什么软件或者点了哪里，或者有没有什么内存清理的软件后台清理内存了

我这边触发条件也不明，这次是edge右键下载文件后突然出现bug了，前几次不可考了
