### ISSUE TITLE
[1.9.8] Mydock 上行事曆不預期消失

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#513]
如題，已確定有把鎖定圖示拖動打勾，行事曆會不預期消失，但重啟整個mydockfinder後，圖示會回來

**Comment by mydockfinder** [comment]
行事曆 是什么 能不能截个图



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月28日(星期二) 下午2:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] [1.9.8] Mydock 上行事曆不預期消失 (Issue #513)





 
如題，已確定有把鎖定圖示拖動打勾，行事曆會不預期消失，但重啟整個mydockfinder後，圖示會回來

**Comment by linitfor** [comment]
![圖片](https://user-images.githubusercontent.com/58168507/228149091-a1d90163-d4df-4f86-a5d4-a35c35755cff.png)
![圖片](https://user-images.githubusercontent.com/58168507/228149377-7ad678b7-2af7-4eb1-bf06-3b8d5c432f6c.png)

**Comment by mydockfinder** [comment]
好的 我测试看看
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月28日(星期二) 下午2:36
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] [1.9.8] Mydock 上行事曆不預期消失 (Issue #513)

**Comment by linitfor** [comment]
感謝 ^.^b

**Comment by mydockfinder** [comment]
不客气，或者试试把行事曆换个位置，我感觉有可能是最左侧的图标会不定期消息




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月28日(星期二) 下午2:38
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] [1.9.8] Mydock 上行事曆不預期消失 (Issue #513)





 
感謝 ^.^b
 
&mdash;

**Comment by linitfor** [comment]
我換位置試試看 之後再回報 不過這個是一段時間才會出現一次喔!

**Comment by mydockfinder** [comment]
嗯 我也测试看看




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月28日(星期二) 下午2:42
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] [1.9.8] Mydock 上行事曆不預期消失 (Issue #513)





 
我換位置試試看 之後再回報 不過這個是一段時間才會出現一次喔!
 
&mdash;

**Comment by linitfor** [comment]
更新到1.9.8.1 後，且把日曆移到內側，昨天跟今天日曆都消失一次。

**Comment by mydockfinder** [comment]
怪事，我这测试了好几天都没事
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月8日(星期六) 中午11:06
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] [1.9.8] Mydock 上行事曆不預期消失 (Issue #513)





 
更新到1.9.8.1 後，且把日曆移到內側，昨天跟今天日曆都消失一次。

**Comment by linitfor** [comment]
對阿 他真的是不預期的消失 目前還抓不住會消失的週期性 跟什麼狀態下會出現這個狀況
上次跟你回報完，把它移位子後，到更新成 1.9.8.1 版本之前 就沒消失過
這是更新到新版後第一次出現 @@
這個的確不好抓問題點 sorry......

**Comment by mydockfinder** [comment]
好吧，应该是有特定的触发条件的，我再慢慢找吧，应该是某种特定步骤




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月10日(星期一) 下午2:10
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] [1.9.8] Mydock 上行事曆不預期消失 (Issue #513)





 
對阿 他真的是不預期的消失 目前還抓不住會消失的週期性 跟什麼狀態下會出現這個狀況
 上次跟你回報完，把它移位子後，到更新成 1.9.8.1 版本之前 就沒消失過
 這是更新到新版後第一次出現 @@
 這個的確不好抓問題點 sorry......
 
&mdash;
