### ISSUE TITLE
[1.9.8]弹出动画会导致部分窗口无法显示

### ISSUE THREAD

**Issue by strange-qwq** [mydockfinder/mydockfinder#514]
比如：
- 微信截图会导致微信自身的隐藏失效（勉强可以接受）
- navicat 选择文件的弹窗无法显示（无法接受）

![1](https://user-images.githubusercontent.com/73089181/228201149-63e00001-6503-4559-86a7-d78a65b8f735.gif)

**Comment by mydockfinder** [comment]
嗯 可以先退回正式版 取消窗口关闭动画就可以了，是关闭动画的问题，下个版本修复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月28日(星期二) 晚上6:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] [1.9.8]弹出动画会导致部分窗口无法显示 (Issue #514)





 
比如：
  
微信截图会导致微信自身的隐藏失效（勉强可以接受）
 
navicat 选择文件的弹窗无法显示（无法接受）

**Comment by strange-qwq** [comment]
> 嗯 可以先退回正式版 取消窗口关闭动画就可以了，是关闭动画的问题，下个版本修复

请问有大概的时间嘛

**Comment by mydockfinder** [comment]
这周日&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月29日(星期三) 上午9:18
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] [1.9.8]弹出动画会导致部分窗口无法显示 (Issue #514)





  
嗯 可以先退回正式版 取消窗口关闭动画就可以了，是关闭动画的问题，下个版本修复
  
请问有大概的时间嘛
