### ISSUE TITLE
關閉窗口動畫

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#520]
![圖片](https://user-images.githubusercontent.com/58168507/230532126-59b4600e-e437-41fd-9933-1bf310c2f29c.png)

請問一下，關閉窗口動畫 是如上圖這樣設定嗎?
因為我好像無法關閉窗口動畫

PS.1 這個窗口動畫是蠻棒的，但會想要測試關閉是因為，先前有提到左側預覽視窗在先前版本加入窗口動畫後，就會出現左側預覽視窗不預期出現凍結，無法點選的狀況，當時與您討論，可能跟新增窗口動畫有關。
但我嘗試關閉窗口動畫，但是在1.9.8.1 這版，還是有機會會出現Pre-stage 預覽偶爾凍結。

PS.2 Pre-stage 預覽偶爾凍結，目前測試設定窗口列表隱藏模式設為"永遠顯示" ，會比設為"預設模式"，更常出現凍結狀況。
![圖片](https://user-images.githubusercontent.com/58168507/230532823-1f2bd295-e7b6-4a28-863e-9efa39bb21e1.png)

**Comment by mydockfinder** [comment]
窗口关闭动画只要是win10 2004以后的系统都是可以用，按理说是没有问题的，因为2004之前的系统偏好设置里面是看不见关闭动画功能的
预览冻结是什么意思，是窗口列表里面不刷新吗，如果窗口最小化了是不会刷新的，因为这是Windows系统机制的问题最小化之后停止渲染窗口，为了减低系统的后台占用，或者你可以拍个视频我看一下大概的情况




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月7日(星期五) 中午11:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 關閉窗口動畫 (Issue #520)





 

 
請問一下，關閉窗口動畫 是如上圖這樣設定嗎?
 因為我好像無法關閉窗口動畫
 
PS.1 這個窗口動畫是蠻棒的，但會想要測試關閉是因為，先前有提到左側預覽視窗在先前版本加入窗口動畫後，就會出現左側預覽視窗不預期出現凍結，無法點選的狀況，當時與您討論，可能跟新增窗口動畫有關。
 但我嘗試關閉窗口動畫，但是在1.9.8.1 這版，還是有機會會出現Pre-stage 預覽偶爾凍結。
 
PS.2 Pre-stage 預覽偶爾凍結，目前測試設定窗口列表隱藏模式設為"永遠顯示" ，會比設為"預設模式"，更常出現凍結狀況。

**Comment by linitfor** [comment]
![ScreenRecorderProject11](https://user-images.githubusercontent.com/58168507/230568894-4c13e26f-0d73-4cb2-99ed-90766a9061e6.gif)
如上圖在某些時候，我欲點選預覽視窗，出現無法點選，滑動滑鼠，也沒有放大視窗的動畫。
會間隔幾秒才會恢復正常，有時候時間會更長，甚至重新啟動mydockfinder 是沒有用的。

**Comment by mydockfinder** [comment]
这个确实会，我也遇到了，正在排查问题
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月7日(星期五) 下午4:06
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 關閉窗口動畫 (Issue #520)





 

 如上圖在某些時候，我欲點選預覽視窗，出現無法點選，滑動滑鼠，也沒有放大視窗的動畫。
