### ISSUE TITLE
1.9.8.2 休眠, 睡眠 按鈕功能 異常

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#524]
1.9.8.2 myfinder 左上方休眠, 睡眠 這兩個功能，好像按下去之後，都是導向關機@@
但先前1.9.8.1 之前的功能是正常的。

我的Windows 版本是:
版本	Windows 11 專業版
版本	22H2
安裝於	‎2023/‎3/‎9
OS 組建	22621.1555
體驗	Windows Feature Experience Pack 1000.22640.1000.0

**Comment by mydockfinder** [comment]
好的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月4日(星期四) 中午1:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 1.9.8.2 休眠, 睡眠 按鈕功能 異常 (Issue #524)





 
1.9.8.2 myfinder 左上方休眠, 睡眠 這兩個功能，好像按下去之後，都是導向關機@@
 但先前1.9.8.1 之前的功能是正常的。
 
我的Windows 版本是:
 版本	Windows 11 專業版
 版本	22H2
 安裝於	‎2023/‎3/‎9
 OS 組建	22621.1555
 體驗	Windows Feature Experience Pack 1000.22640.1000.0

**Comment by linitfor** [comment]
請問近期有規劃更新版本嗎？

**Comment by linitfor** [comment]
大大最近還好嗎?

**Comment by mydockfinder** [comment]
最近工作有点忙，而且有点到瓶颈了，不知道更新些什么功能好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月9日(星期二) 下午4:39
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 1.9.8.2 休眠, 睡眠 按鈕功能 異常 (Issue #524)





 
大大最近還好嗎?
 
&mdash;

**Comment by linitfor** [comment]
ok ok 工作優先吧!

不知道更新什麼嗎?
那後面等大大比較有空的時候，我們再來開新功能的許願清單吧 XD

**Comment by mydockfinder** [comment]
没事你可以说，我最近就是不知道加什么新功能有点迷茫，一直在修bug




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月12日(星期五) 下午3:17
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 1.9.8.2 休眠, 睡眠 按鈕功能 異常 (Issue #524)





 
ok ok 工作優先吧!
 
不知道更新什麼嗎?
 那後面等大大比較有空的時候，我們再來開新功能的許願清單吧 XD
 
&mdash;
