### ISSUE TITLE
1.9.8.4 12代U温度监测嘎了

### ISSUE THREAD

**Issue by lovesion** [mydockfinder/mydockfinder#527]
12800hx + 3070ti 
移动端
之前的版本OK的

**Comment by mydockfinder** [comment]
不应该啊&nbsp; CPU温度好多个版本没更新过了，他是个独立的exe程序




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月29日(星期一) 上午9:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 1.9.8.4 12代U温度监测嘎了 (Issue #527)





 
12800hx + 3070ti
 移动端
 之前的版本OK的

**Comment by lovesion** [comment]
1.9.8.5 它好了
