### ISSUE TITLE
mydockfinder 导致 explorer.exe基于堆栈的缓冲区溢出

### ISSUE THREAD

**Issue by Decem6er** [mydockfinder/mydockfinder#53]
mydockfinder 导致 explorer.exe基于堆栈的缓冲区溢出
![8180353](https://user-images.githubusercontent.com/16839570/119968477-1886d080-bfe0-11eb-96c7-0645e47980ab.jpg)

下面是事件查看器中的有关日志：
```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Popup" Guid="{47bfa2b7-bd54-4fac-b70b-29021084ca8f}" /> 
  <EventID>26</EventID> 
  <Version>0</Version> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2021-05-28T09:53:32.6604893Z" /> 
  <EventRecordID>355583</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="628" ThreadID="19620" /> 
  <Channel>System</Channel> 
  <Computer>Shi000</Computer> 
  <Security UserID="S-1-5-18" /> 
  </System>
- <EventData>
  <Data Name="Caption">explorer.exe - 系统错误</Data> 
  <Data Name="Message">系统在此应用程序中检测到基于堆栈的缓冲区溢出。溢出可能允许恶意用户获得此应用程序的控制。</Data> 
  </EventData>
  </Event>
```
```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-Winlogon" Guid="{DBE9B383-7CF3-4331-91CC-A3CB16A3B538}" EventSourceName="Winlogon" /> 
  <EventID Qualifiers="16384">1002</EventID> 
  <Version>0</Version> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-05-28T09:53:39.5340937Z" /> 
  <EventRecordID>278575</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>Shi000</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>explorer.exe</Data> 
  </EventData>
  </Event>
```

**Comment by Decem6er** [comment]
mydockfinder 版本：5.9.9.4
系统信息：

> 版本	  Windows 10 专业版
>版本号	  21H1
>操作系统内部版本	  19043.1023
>体验	  Windows Feature Experience Pack 120.2212.2020.0

**Comment by mydockfinder** [comment]
是不是一直右键点访达的logo，然后开始菜单出不来以后这样的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月28日(星期五) 晚上6:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] mydockfinder 导致 explorer.exe基于堆栈的缓冲区溢出 (#53)





 
mydockfinder 版本：5.9.9.4
 系统信息：
  
版本	  Windows 10 专业版
 版本号	  21H1
 操作系统内部版本	  19043.1023
 体验	  Windows Feature Experience Pack 120.2212.2020.0
  
&mdash;

**Comment by Decem6er** [comment]
不是，就在刚刚我收到您这封邮件时，点击右下角来自 操作中心 的通知来打开系统自带邮件应用后，又出现了这个问题。

**Comment by Decem6er** [comment]
我发现这个bug触发似乎没有特别规律，时不时就来这么一下，建议您在以后版本中增加日志记录的功能，便于反馈。

**Comment by mydockfinder** [comment]
那有可能是新版拦截系统通知的事，你开没开上面的myfinder



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月28日(星期五) 晚上6:55
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] mydockfinder 导致 explorer.exe基于堆栈的缓冲区溢出 (#53)





 
我发现这个bug触发似乎没有特别规律，时不时就来这么一下，建议您在以后对此版本中增加日志记录的功能，便于反馈。
 
&mdash;

**Comment by Decem6er** [comment]
开了

**Comment by mydockfinder** [comment]
有可能是他的事，在观察看看吧，不过这个问题还是第一次有人提




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月28日(星期五) 晚上8:16
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] mydockfinder 导致 explorer.exe基于堆栈的缓冲区溢出 (#53)





 
开了
 
&mdash;

**Comment by Decem6er** [comment]
好的，谢谢

**Comment by Decem6er** [comment]
查出来了，似乎是累积更新编号为 `KB5003214` 的积累更新与Mydockfinder冲突导致的。在卸载这枚更新后已经正常。（其实当时更新后发现任务栏有问题，本来打算用Mydockfinder替代一下的，结果装完mydockfinder后就出现了这个问题 : )  ）
