### ISSUE TITLE
[Mydock] Mydock Preview 功能增加會議連接按鈕

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#539]
發現在開啟Mydockfinder 時，使用 Microsoft teams, Cisco Webex 這類線上會議軟體時，要分享單一視窗，
會找不到已開啟的視窗，造成無法分享
關閉Mydockfinder 後，回到Windows 工作列，就可以找到視窗。

不確定是否跟Mydock Preview 沒有偵測連結會議分享視窗的關係

這是Mydock Preview 視窗
![image](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/f462a45e-1c04-40fa-9d5a-3c6cdf74056d)

這是Windows 11 內建Peview
![image](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/eaf4d3ab-e61a-40ff-90df-22eaab96fa1b)

仔細在Microsoft Teams 線上會議軟體，實驗到主要差別在於MyDock 是否有開啟有直接關係

在沒有開啟MyDock 時， Microsoft Teams 分享視窗，可以偵測到所有已開啟的視窗，以提供會議分享使用。
![image](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/cca46462-1141-4d3e-836d-96e1e647edba)

但有開啟MyDock時，Microsoft Teams 分享視窗，只會偵測到兩個開啟視窗
![image](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/3ccce91a-1bd0-406b-98ea-7335693e8857)

這個部分不知道大大有沒有辦法解決，不然在視訊會議要分享開啟檔案時，
得先關閉MyDock，才能啟用分享。

**Comment by mydockfinder** [comment]
这个共享的按钮怎么显示&nbsp; 我这里任务栏预览没有这个共享按钮




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月14日(星期五) 中午11:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] [Mydock] Mydock Preview 功能增加會議連接按鈕 (Issue #539)





 
發現在開啟Mydockfinder 時，使用 Microsoft teams, Cisco Webex 這類線上會議軟體時，要分享單一視窗，
 會找不到已開啟的視窗，造成無法分享
 關閉Mydockfinder 後，回到Windows 工作列，就可以找到視窗。
 
不確定是否跟Mydock Preview 沒有偵測連結會議分享視窗的關係
 
這是Mydock Preview 視窗
 
 
這是Windows 11 內建Peview

**Comment by linitfor** [comment]
要在Microsoft teams 內開一個會議，進入線上會議後，再去看預覽視窗就會出現囉

**Comment by linitfor** [comment]
大大有裝microsoft teams 嗎 有的話 我可以發個會議連結給你 登入後 就會發現上述的不同了

**Comment by mydockfinder** [comment]
没有啊&nbsp; 是要装他吗，我回来研究研究




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月15日(星期六) 晚上10:02
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] [Mydock] Mydock Preview 功能增加會議連接按鈕 (Issue #539)





 
大大有裝microsoft teams 嗎 有的話 我可以發個會議連結給你 登入後 就會發現上述的不同了
 
&mdash;

**Comment by linitfor** [comment]
對 下載連結在這
https://www.microsoft.com/zh-CN/microsoft-teams/download-app
不過要登入 你可能需要先有一組微軟的email 帳號喔! 不好意思!

再麻煩大大了   感謝!!

**Comment by linitfor** [comment]
大大 我發現 teams 會議軟體沒有顯示 所有開啟視窗的問題，是因為台前調度開啟的關係，會屏蔽調非同視窗的程式，
這樣我大概知道目前要先在開啟會議時，把要展示的程式拉到跟會議軟體同個畫面群組，這樣會議軟體就可以看得到準備分享的程式了，這樣就維持開啟使用mydock了!! 感謝 ~~

至於在預覽視窗加入會議軟體分享的按鈕，這個感覺有點難，這個就要交給大大幫忙了

**Comment by mydockfinder** [comment]
是我不会用吗，我怎么开了好几次会议任务栏的窗口预览都没有分享的按钮




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月18日(星期二) 下午2:32
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] [Mydock] Mydock Preview 功能增加會議連接按鈕 (Issue #539)





 
大大 我發現 teams 會議軟體沒有顯示 所有開啟視窗的問題，是因為台前調度開啟的關係，會屏蔽調非同視窗的程式，
 這樣我大概知道目前要先在開啟會議時，把要展示的程式拉到跟會議軟體同個畫面群組，這樣會議軟體就可以看得到準備分享的程式了，這樣就維持開啟使用mydock了!! 感謝 ~~
 
至於在預覽視窗加入會議軟體分享的按鈕，這個感覺有點難，這個就要交給大大幫忙了
 
&mdash;

**Comment by linitfor** [comment]
請問大大的windows 版本是?
我的是
![圖片](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/e3abb153-3db5-4e7a-a111-2df3e09d5a0e)

**Comment by mydockfinder** [comment]
22623.102022H2




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月21日(星期五) 中午11:04
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] [Mydock] Mydock Preview 功能增加會議連接按鈕 (Issue #539)





 
請問大大的windows 版本是?
 我的是
 
 
&mdash;

**Comment by linitfor** [comment]
疑 這應該是windows 11 會內建的功能耶 

網路上找的英文版新聞 
https://beebom.com/windows-11-screen-sharing-is-about-to-get-a-whole-lot-better-soon/

**Comment by mydockfinder** [comment]
为啥我的没有。。。。。
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月3日(星期四) 下午2:18
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] [Mydock] Mydock Preview 功能增加會議連接按鈕 (Issue #539)





 
疑 這應該是windows 11 會內建的功能耶
 
網路上找的英文版新聞
 https://beebom.com/windows-11-screen-sharing-is-about-to-get-a-whole-lot-better-soon/

**Comment by linitfor** [comment]
這我也不知道 哈哈哈
