### ISSUE TITLE
启动台中再次添加图标后，打开后找不到之前的所有图标

### ISSUE THREAD

**Issue by Refactoring** [mydockfinder/mydockfinder#54]
如题，首次添加快捷方式图标后，点开启动台，可以看到快捷方式图标。 再次添加快捷方式图标后，原先添加的图标全部没有显示，但占位了。 启动台中只在最后面显示新增的图标。
手工关闭，重启Dock_64.exe进程后，显示正常。(再次打开启动台后，一定几率出现所有图标都找不见的情况)

```
MyDock: v5.9.9.1
OS: Windows 10 企业版 x64 v10.0.19043.1023
```
![ISSUS](https://user-images.githubusercontent.com/451129/120093421-bdbeb780-c14c-11eb-9cc3-b6a143abb9ff.jpg)

**Comment by Refactoring** [comment]
程序安装目录：`D:\Program Files\MyDock`.
启动台快捷方式目录，添加的快捷方式全部存在的`D:\Program Files\MyDock\launchpad`

**Comment by mydockfinder** [comment]
都已经5.9.9.4了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月30日(星期天) 中午1:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] 启动台中再次添加图标后，打开后找不到之前的所有图标 (#54)





 
程序安装目录：D:\Program Files\MyDock.
 启动台快捷方式目录，添加的快捷方式全部存在的D:\Program Files\MyDock\launchpad
 
&mdash;

**Comment by Refactoring** [comment]
看其他网站介绍进来的， 没注意最新的版本......
下了最新版本v5.9.9.5, 不存在我描述的这个问题了。
