### ISSUE TITLE
Mydock 無法顯現 特定程式

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#548]
可否幫忙檢測一下，
我的Mydock 無法顯現 小魚易連 這個程式的icon
但在myfinder 上可以偵測到有開啟

PS. 我有確認沒有把這個程式列入禁止列表清單中

![圖片](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/48c0c8e6-08b2-4527-b226-a081f8e94f26)

小魚易連官網
https://www.xylink.com/download

**Comment by linitfor** [comment]
這項 大大有時間幫忙看一下問題嗎?

**Comment by mydockfinder** [comment]
啊&nbsp; 我忘了我现在测




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月3日(星期四) 下午2:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Mydock 無法顯現 特定程式 (Issue #548)





 
這項 大大有時間幫忙看一下問題嗎?
 
&mdash;

**Comment by mydockfinder** [comment]
我测试了一下，小鱼易连是pak不是exe所以没显示，我适配看看
![image](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/32895737/6e50b568-061b-41c1-8801-6e84a9f8565c)

**Comment by linitfor** [comment]
感謝大大 這個看看可不可以優先幫我加入下一版更新，不然開會切換畫面會有點小困擾

**Comment by mydockfinder** [comment]
修好了已经更新了
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月5日(星期六) 凌晨2:41
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Mydock 無法顯現 特定程式 (Issue #548)





 
感謝大大 這個看看可不可以優先幫我加入下一版更新，不然開會切換畫面會有點小困擾

**Comment by linitfor** [comment]
好的 我晚點測試看看 感謝大大

**Comment by linitfor** [comment]
有了 可以了 感謝大大支援

**Comment by mydockfinder** [comment]
不客气




№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月7日(星期一) 晚上11:17
***@***.***&gt;;
抄送:&nbsp;"№じ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [mydockfinder/mydockfinder-for-Win10-Win11] Mydock 無法顯現 特定程式 (Issue #548)





 
有了 可以了 感謝大大支援
