### ISSUE TITLE
微信、企业微信等程序主窗口会莫名其妙被关闭

### ISSUE THREAD

**Issue by strange-qwq** [mydockfinder/mydockfinder#550]
触发方式，以微信为例：
1. 打开微信主聊天窗口
2. 点击表情或发送的图片打开浮窗
3. 主窗口有概率被关闭
4. 若未关闭则多试几次

关闭MyFinder后正常

**Comment by mydockfinder** [comment]
是新版本的bug，只要点击托盘图标以后大概10秒就会窗口隐藏&nbsp; 代码的bug




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月25日(星期二) 下午2:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 微信、企业微信等程序主窗口会莫名其妙被关闭 (Issue #550)





 
触发方式，以微信为例：
  
打开微信主聊天窗口
 
点击表情或发送的图片打开浮窗
 
主窗口有概率被关闭
 
若未关闭则多试几次
  
关闭MyFinder后正常

**Comment by strange-qwq** [comment]
> 是新版本的bug，只要点击托盘图标以后大概10秒就会窗口隐藏&nbsp; 代码的bug

麻烦快点修复吧555

**Comment by mydockfinder** [comment]
好的 可以退到1.9.8.5，测试版通道里面有，没有测试代码
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月25日(星期二) 下午3:47
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 微信、企业微信等程序主窗口会莫名其妙被关闭 (Issue #550)





  
是新版本的bug，只要点击托盘图标以后大概10秒就会窗口隐藏&nbsp; 代码的bug
  
麻烦快点修复吧555

**Comment by strange-qwq** [comment]
再提个建议：
测试版可以发的频繁点，有修复问题或者新功能都可以自己简单测试后直接发个版；
正式版累计几个测试版后确认没有bug再发版；
现有的正式版也有些问题，想回退都不知道回退到哪个版本了 XD

**Comment by mydockfinder** [comment]
也是&nbsp; 最近忙的有点懵




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月25日(星期二) 下午3:52
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 微信、企业微信等程序主窗口会莫名其妙被关闭 (Issue #550)





 
再提个建议：
 测试版可以发的频繁点，有修复问题或者新功能都可以自己简单测试后直接发个版；
 正式版累计几个测试版后确认没有bug再发版；
 现有的正式版也有些问题，想回退都不知道回退到哪个版本了 XD
 
&mdash;

**Comment by chuck00000** [comment]
最新版本CPU动不动占用过高, 卡死

**Comment by mydockfinder** [comment]
emmmmm&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月31日(星期一) 中午1:47
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 微信、企业微信等程序主窗口会莫名其妙被关闭 (Issue #550)





 
最新版本CPU动不动占用过高, 卡死
 
&mdash;

**Comment by chuck00000** [comment]
> 
这种CPU高占用情况是在打开新版Windows Media Player 后100%触发, 任务管理器显示dock CPU占用率60%左右

**Comment by mydockfinder** [comment]
新版media play是哪个，是视频吗
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月31日(星期一) 下午5:57
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 微信、企业微信等程序主窗口会莫名其妙被关闭 (Issue #550)





   
这种CPU高占用情况是在打开新版Windows Media Player 后100%触发, 任务管理器显示dock CPU占用率60%左右

**Comment by 858622025** [comment]
QQ，微信，只能2选1前台展示，打开QQ，微信自己就关闭了打开微信，qq就关了，设置QQ打开图片，聊天窗自己就关了。QQ是新版的9.9.1。

**Comment by mydockfinder** [comment]
上一个问题，mediaplay新版是哪个




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月1日(星期二) 下午5:33
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 微信、企业微信等程序主窗口会莫名其妙被关闭 (Issue #550)





 
QQ，微信，只能2选1前台展示，打开QQ，微信自己就关闭了打开微信，qq就关了，设置QQ打开图片，聊天窗自己就关了。QQ是新版的9.9.1。
 
&mdash;

**Comment by chuck00000** [comment]
媒体播放器

![image](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/98159699/ed2f0707-0b22-4ac4-ac61-4824e2318f09)

**Comment by mydockfinder** [comment]
行&nbsp; 我试试，是听音乐还是看视频




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月2日(星期三) 中午11:25
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 微信、企业微信等程序主窗口会莫名其妙被关闭 (Issue #550)





 
媒体播放器
 

 
&mdash;

**Comment by chuck00000** [comment]
只要一启动 媒体播放器 就CPU占用过高, 光听音乐倒不至于导致dock崩溃卡死, 放视频绝对崩溃卡死

**Comment by chuck00000** [comment]
把 媒体播放器 关了,杀了其后台, dock CPU占用还一直很高

**Comment by mydockfinder** [comment]
emmmm&nbsp; 我试了五六次没事。。。。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月2日(星期三) 中午11:41
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 微信、企业微信等程序主窗口会莫名其妙被关闭 (Issue #550)





 
把 媒体播放器 关了,杀了其后台, dock CPU占用还一直很高
 
&mdash;

**Comment by chuck00000** [comment]
行吧 , 我用的最新版win11 canary 25915;  媒体播放器  上一次的更新时间是6月7日; 

退出dock, 再启动媒体播放器, CPU正常低占用 ,不会不正常一直高占用

**Comment by chuck00000** [comment]
![Screenshot (2)](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/98159699/b4e61237-51b4-4116-898b-995417c410a9)

**Comment by strange-qwq** [comment]
作者大大啥时候发布修复更新哇 XD

**Comment by mydockfinder** [comment]
更新了&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月3日(星期四) 下午5:58
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 微信、企业微信等程序主窗口会莫名其妙被关闭 (Issue #550)





 
作者大大啥时候发布修复更新哇 XD
