### ISSUE TITLE
無法顯示藍芽耳機電量

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#553]
如下圖所示
![圖片](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/f2e68161-f765-4e45-9293-f49b3f3d770f)

**Comment by mydockfinder** [comment]
不是低功耗的蓝牙4.0的设备我不会取电量。。。。。。。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月3日(星期四) 上午7:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 無法顯示藍芽耳機電量 (Issue #553)





 
如下圖所示

**Comment by linitfor** [comment]
喔喔 了解
沒關係 點進去看就好了 謝謝大大啦 ~

順便問一下，近期還有更新的計畫嗎?

**Comment by mydockfinder** [comment]
周日应该能更新，加了窗口显示动画，因为bug比较多上周没更新
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月3日(星期四) 下午2:13
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 無法顯示藍芽耳機電量 (Issue #553)





 
喔喔 了解
 沒關係 點進去看就好了 謝謝大大啦 ~
 
順便問一下，近期還有更新的計畫嗎?

**Comment by linitfor** [comment]
好啊 感謝大大， 另外建議大大 目前1.9.8.7 可以在新版更新時
保留1.9.8.7版本選項給我們切換，這板目前用起來還算穩定
除了小魚易連會議程式無法辨認的問題，其他的算式用起來穩定好用。

**Comment by mydockfinder** [comment]
小鱼易连我修好了，更新就行了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月5日(星期六) 凌晨2:46
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 無法顯示藍芽耳機電量 (Issue #553)





 
好啊 感謝大大， 另外建議大大 目前1.9.8.7 可以在新版更新時
 保留1.9.8.7版本選項給我們切換，這板目前用起來還算穩定
 除了小魚易連會議程式無法辨認的問題，其他的算式用起來穩定好用。
 
&mdash;
