### ISSUE TITLE
電池電量顯示方式選項

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#555]
大大有沒有機會把筆電電池時間，像藍芽顯示電量的選單，
多種選擇，顯示百分比或者剩餘可用時間。

建議: 把剩餘可用時間，用(hr:min) 這種表達方式。
讓我們使用筆電開會的時候，一眼就可以看還剩多少時間可以使用

![圖片](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/54065376-f4ef-4a8e-90de-f4f80ad15ce4)

**Comment by mydockfinder** [comment]
好的，是想鼠标悬停可以显示剩余时间吧



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月3日(星期四) 晚上10:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 電池電量顯示方式選項 (Issue #555)





 
大大有沒有機會把筆電電池時間，像藍芽顯示電量的選單，
 多種選擇，顯示百分比或者剩餘可用時間。
 
建議: 把剩餘可用時間，用(hr:min) 這種表達方式。
 讓我們使用筆電開會的時候，一眼就可以看還剩多少時間可以使用

**Comment by linitfor** [comment]
![image](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/36582e91-764c-4df0-b0b9-9188965697ff)


大大 不知道可不可以直接顯示在myfinder上，想像上圖這個mac 上的外掛程式一樣。
這樣不動滑鼠可以立即看到剩餘時間。

**Comment by mydockfinder** [comment]
也行&nbsp; 我可以加上
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月6日(星期天) 晚上9:13
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 電池電量顯示方式選項 (Issue #555)





 

 
大大 不知道可不可以直接顯示在myfinder上，想像上圖這個mac 上的外掛程式一樣。
 這樣不動滑鼠可以立即看到剩餘時間。

**Comment by linitfor** [comment]
請問這週有計畫更新嗎？
還是大大太忙，還要再等等呢？

**Comment by mydockfinder** [comment]
下周吧&nbsp; 在做新的功能




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月13日(星期天) 晚上10:07
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 電池電量顯示方式選項 (Issue #555)





 
請問這週有計畫更新嗎？
 還是大大太忙，還要再等等呢？
 
&mdash;

**Comment by mydockfinder** [comment]
有个问题，充电的时候还要不要显示剩余充满电的时间



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月13日(星期天) 晚上10:07
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 電池電量顯示方式選項 (Issue #555)





 
請問這週有計畫更新嗎？
 還是大大太忙，還要再等等呢？
 
&mdash;

**Comment by linitfor** [comment]
我看其他的程式都會有欸

放電時會顯示剩餘使用時間
充電中會顯示剩餘充電時間
但如果充滿的時候就不會顯示剩餘時間
圖示會從充電中，換成插電圖示

**Comment by linitfor** [comment]
感謝大大，目前有實現的應該是放電時會顯示剩餘使用時間
充電剩餘時間好像還沒時間實作對吧 ？

**Comment by mydockfinder** [comment]
充电应该是有的，主要是看代码能不能取到时间
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月2日(星期六) 上午10:36
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 電池電量顯示方式選項 (Issue #555)





 
感謝大大，目前有實現的應該是放電時會顯示剩餘使用時間
 充電剩餘時間好像還沒時間實作對吧 ？
