### ISSUE TITLE
翻译这几处有问题

### ISSUE THREAD

**Issue by chuck00000** [mydockfinder/mydockfinder#556]
最新版1.9.8.8 显示语言:那里 设置的英文,其选项显示"简体中文", 点击打开语言列表,发现"English" 选项乱码
![{B32F8C88-3AFD-45B7-8207-3A975E2711BB}](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/98159699/9be172b5-3706-47b2-9587-944c636ddb3f)
![{1C88B445-FC57-42A2-BC13-9C0135D2B073}](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/98159699/b667c7ff-48ba-4c05-8797-88dae1cf8e64)

还有一处就是之前就未翻译的地方, 如果你未运行Steam, 选择"上传配置文件/恢复配置", 其弹窗是中文,
![{739CFCE7-FE39-43EA-A5B9-0FB4F5ABA9AA}](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/98159699/da7f6221-f2ba-423c-99d8-3dd22ab45d0a)
![image](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/98159699/cbb09ef0-b906-4fd2-b733-b575b48b6cbe)

**Comment by mydockfinder** [comment]
第一个是阿拉伯语，应该是语言文件出错了
少的翻译回来补上




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月7日(星期一) 中午11:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 翻译这几处有问题 (Issue #556)





 
最新版1.9.8.8 显示语言:那里 设置的英文,其选项显示"简体中文", 点击打开语言列表,发现"English" 选项乱码
 
 
 
还有一处就是之前就未翻译的地方, 如果你未运行Steam, 选择"上传配置文件/恢复配置", 其弹窗是中文,
