### ISSUE TITLE
藍芽偏好設定選單建議位置移動

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#562]
大大可否把藍芽偏好設定選單按鈕往上移動到下圖框框的位置

原因是因為最近有時候要點藍芽偏好設定，進去內部看某些設備電量時，
但系統又再掃描藍芽裝置，每次要點藍芽偏好設定，就又跑出新的設備
就會一直點不到選單，感覺蠻好笑的，影響使用體驗。

如果把藍芽偏好設定選單放在上面，這樣再掃描顯示新的藍芽裝置
就不會影響要點選藍芽偏好設定選單了。

![圖片](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/cb9b1788-b08e-4e48-93a3-78b4419a881b)

**Comment by mydockfinder** [comment]
可以，不过你的蓝牙设备挺多的，我这就两三个刷新后就基本不会动了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月16日(星期三) 中午12:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 藍芽偏好設定選單建議位置移動 (Issue #562)





 
大大可否把藍芽偏好設定選單按鈕往上移動到下圖框框的位置
 
原因是因為最近有時候要點藍芽偏好設定，進去內部看某些設備電量時，
 但系統又再掃描藍芽裝置，每次要點藍芽偏好設定，就又跑出新的設備
 就會一直點不到選單，感覺蠻好笑的。
 
如果把藍芽偏好設定選單放在上面，這樣再掃描顯示新的藍芽裝置
 就不會影響要點選藍芽偏好設定選單了。

**Comment by linitfor** [comment]
哈哈哈 這些都不是我的阿，是在公司，一堆藍芽四射 XDD

**Comment by linitfor** [comment]
感謝大大協助修改
