### ISSUE TITLE
偵測目前是插電源還是拔電源模式，進一步來自動切換指定的電源模式

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#563]
有個提議，不知道會不會超出範圍，
想建議大大幫忙設計偵測目前是插電源還是拔電源模式，進一步來自動切換指定的電源模式

之前有裝過第三方電池維護軟體
有種功能是
可以設定當插上電源供應器的時候是一個模式
拔除電源，只使用電池的時候，可以指定另一種模式

如下圖，我目前是自己手動切換的情境的
在插上電源供應器時，我會自己切換成平衡或者全速的模式
如果筆電在開會只有使用電池時，我會先切換成省電模式
在閱讀或純看影片，非大量程式多工操作時，我會切換成閱讀模式，來爭取更多電源時間。

![圖片](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/27509aa0-f029-4c30-8fae-d90128146490)

PS. 這些電量模式都是在windows 電源模式，自建電源模式的
![圖片](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/77a3ffc1-0029-4cad-8b40-cf00e8d1ac2b)

**Comment by mydockfinder** [comment]
这个倒是可以




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月17日(星期四) 上午10:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 偵測目前是插電源還是拔電源模式，進一步來自動切換指定的電源模式 (Issue #563)





 
有個提議，不知道會不會超出範圍，
 想建議大大幫忙設計偵測目前是插電源還是拔電源模式，進一步來自動切換指定的電源模式
 
之前有裝過第三方電池維護軟體
 有種功能是
 可以設定當插上電源供應器的時候是一個模式
 拔除電源，只使用電池的時候，可以指定另一種模式
 
如下圖，我目前是自己手動切換的情境的
 在插上電源供應器時，我會自己切換成平衡或者全速的模式
 如果筆電在開會只有使用電池時，我會先切換成省電模式
 在閱讀或純看影片，非大量程式多工操作時，我會切換成閱讀模式，來爭取更多電源時間。
 

 
PS. 這些電量模式都是在windows 電源模式，自建電源模式的

**Comment by linitfor** [comment]
哇 大大工作繁忙齁 ~ 本來期待這周的更新的說 哈哈哈哈

**Comment by mydockfinder** [comment]
实在不好意思，加了steam的新功能，而且昨天下午发现了一处很久的自动退出问题到现在还没修好&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月21日(星期一) 上午9:26
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 偵測目前是插電源還是拔電源模式，進一步來自動切換指定的電源模式 (Issue #563)





 
哇 大大工作繁忙齁 ~ 本來期待這周的更新的說 哈哈哈哈

**Comment by linitfor** [comment]
喔喔 沒關係啦 還是按照大大的步調吧 ^.^b

**Comment by linitfor** [comment]
這週大大有計畫更新嗎？

**Comment by linitfor** [comment]
請問大大，這週有時間增加自動切換電源模式的功能嗎？

**Comment by mydockfinder** [comment]
可以 我回来加上
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月2日(星期六) 上午10:37
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 偵測目前是插電源還是拔電源模式，進一步來自動切換指定的電源模式 (Issue #563)





 
請問大大，這週有時間增加自動切換電源模式的功能嗎？

**Comment by linitfor** [comment]
ok ok 大大出差是吧 ? 辛苦啦

**Comment by mydockfinder** [comment]
不是啊，这两周脑细胞死了不少啊，重写了dock的结构代码为了后面出多屏同时显示dock，然后加了系统任务栏的那个右键菜单，可以在dock图标上面显示最近打开的文件和任务




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月15日(星期五) 下午4:07
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 偵測目前是插電源還是拔電源模式，進一步來自動切換指定的電源模式 (Issue #563)





 
ok ok 大大出差是吧 ? 辛苦啦
 
&mdash;

**Comment by linitfor** [comment]
好喔 聽起來好難@@ 謝謝大大不斷增強功能
