### ISSUE TITLE
Mydock 上的icon 實現顯示使用者狀態 or 數目 徽章

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#564]
請教大大，有辦法讀取軟體的徽章數目(如圖紅色框框的數字)

以下這個圖示是在釘選在windows 11 工作列上的 Microsoft to do 軟體。
然後顯示在mydock 圖示上嗎? 

![圖片](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/f338d263-4fa1-48bd-983a-6761569844b7)

目前看的到 Microsoft teams 的 使用者狀態
大大可以在Myfinder 上實現，但在mydock 上的icon 就沒有這樣的功能
![圖片](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/b927f033-8984-4aef-868e-56e917c2a045)

**Comment by mydockfinder** [comment]
之前想过，但是我也不会。。。。&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月17日(星期四) 下午5:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] Mydock 上的icon 實現 (Issue #564)





 
請教大大，有辦法讀取軟體的徽章數目(如圖紅色框框的數字)
 
以下這個圖示是在釘選在windows 11 工作列上的 Microsoft to do 軟體。
 然後顯示在mydock 圖示上嗎?
 

 
目前看的到 Microsoft teams 的 使用者狀態
 大大可以在Myfinder 上實現，但在mydock 上的icon 就沒有這樣的功能

**Comment by linitfor** [comment]
ok ok 沒關係 現有的功能就已經很棒了 感謝大大啦
