### ISSUE TITLE
win10 任务栏与 dock同时出现

### ISSUE THREAD

**Issue by qwq111** [mydockfinder/mydockfinder#57]
![image](https://user-images.githubusercontent.com/45617452/120689885-2b653d80-c4d7-11eb-804e-007bff17893c.png)
请问这个怎么处理呀，大神

**Comment by mydockfinder** [comment]
分隔符右键 隐藏任务栏




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月4日(星期五) 凌晨1:50
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder] win10 任务栏与 dock同时出现 (#57)





 

 请问这个怎么处理呀，大神
