### ISSUE TITLE
MyFinder中可以把时间隐藏起来吗

### ISSUE THREAD

**Issue by 0x083X** [mydockfinder/mydockfinder#572]
如题,想把MyFinder中的时间给去除掉请问怎么操作

**Comment by mydockfinder** [comment]
目前不行 话说不看时间吗。。。。






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月4日(星期一) 晚上11:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] MyFinder中可以把时间隐藏起来吗 (Issue #572)





 
如题,想把MyFinder中的时间给去除掉请问怎么操作

**Comment by 0x083X** [comment]
习惯了不看时间。。。
