### ISSUE TITLE
台前调度功能开了之后,只能同时显示一个程序吗

### ISSUE THREAD

**Issue by 0x083X** [mydockfinder/mydockfinder#576]
如题, 想同时显示两个程序是不是不行滴。

**Comment by linitfor** [comment]
剛開啟台前調度時不行
但開啟後 你把要的視窗都從左側預覽視窗拉出來後，就可以同時顯示啦

**Comment by 0x083X** [comment]
可以了 感谢

> 剛開啟台前調度時不行 但開啟後 你把要的視窗都從左側預覽視窗拉出來後，就可以同時顯示啦
