### ISSUE TITLE
1.9.9最新版本，固定在launchpad 启动盘的 所有的安卓子系统软件图标 点击无法启动

### ISSUE THREAD

**Issue by chuck00000** [mydockfinder/mydockfinder#580]
固定在launchpad 启动盘的 所有安卓软件图标 点击都无法启动；每次重启Dock 后， 启动盘 上 所有安卓软件图标底下的 文字名称 全部都是一样的。 

点击固定在Dock上的安卓软件图标倒是能正常启动。

**Comment by mydockfinder** [comment]
好的&nbsp; 我还没测试过安卓图标，是WSA的安卓图标吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月25日(星期一) 中午1:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 1.9.9最新版本，固定在launchpad 启动盘的 所有的安卓子系统软件图标 点击无法启动 (Issue #580)





 
固定在launchpad 启动盘的 所有安卓软件图标 点击都无法启动；每次重启Dock 后， 启动盘 上 所有安卓软件图标底下的 文字名称 全部都是一样的。
 
点击固定在Dock上的安卓软件图标倒是能正常启动。

**Comment by chuck00000** [comment]
是的

**Comment by chuck00000** [comment]
![Screenshot 2023-09-27 202855](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/98159699/137d1e12-507b-4fab-9644-54395d771f6c)
每次重启后, 启动盘的 WSA安卓图标底部的文字名称变得一样的Bug, 还未修复

**Comment by mydockfinder** [comment]
emmmmm&nbsp; 是名称啊，我看成了图标一样。。。。。&nbsp; 我的 下个版本修复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月27日(星期三) 晚上8:36
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 1.9.9最新版本，固定在launchpad 启动盘的 所有的安卓子系统软件图标 点击无法启动 (Issue #580)





 

 每次重启后, 启动盘的 WSA安卓图标底部的文字名称变得一样的Bug, 还未修复
 
&mdash;

**Comment by mydockfinder** [comment]
我测试了没有问题，可以在删除这几个图标重新添加一次看看




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月27日(星期三) 晚上8:36
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 1.9.9最新版本，固定在launchpad 启动盘的 所有的安卓子系统软件图标 点击无法启动 (Issue #580)





 

 每次重启后, 启动盘的 WSA安卓图标底部的文字名称变得一样的Bug, 还未修复
 
&mdash;

**Comment by chuck00000** [comment]
不行啊，只要重启Dockfinder后 启动盘 所有安卓图标名称全部变一样的，默认上次编辑最后一个安卓图标的名称
