### ISSUE TITLE
选择了始终显示系统托盘图标，可不可以把Finder 上的“展示系统托盘图标”的 箭头按钮 给隐藏掉

### ISSUE THREAD

**Issue by chuck00000** [mydockfinder/mydockfinder#584]
![Screenshot 2023-10-05 174431](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/98159699/62cb675e-bcab-4285-a8e9-e629eb2ac585)

**Comment by mydockfinder** [comment]
嗯&nbsp; 好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月5日(星期四) 下午5:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 选择了始终显示系统托盘图标，可不可以把Finder 上的“展示系统托盘图标”的 箭头按钮 给隐藏掉 (Issue #584)

**Comment by LD-KiLLer** [comment]
![Snipaste_2023-10-11_11-20-43](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/72300642/9c57bfad-a8a5-4292-9c16-16a53df6469b)
大佬，这些图标的间距能调小一点吗？13寸的surface，桌面空间寸土寸金啊😂

**Comment by mydockfinder** [comment]
emmmmmm&nbsp; &nbsp; 你是需要一个按钮间距的功能吗，我想想怎么加
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月11日(星期三) 中午11:22
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 选择了始终显示系统托盘图标，可不可以把Finder 上的“展示系统托盘图标”的 箭头按钮 给隐藏掉 (Issue #584)





 

 大佬，这些图标的间距能调小一点吗？13寸的surface，桌面空间寸土寸金啊😂

**Comment by LD-KiLLer** [comment]
> emmmmmm&nbsp; &nbsp; 你是需要一个按钮间距的功能吗，我想想怎么加 &nbsp; №じ&nbsp;尐乄鈊~→☆ ***@***.*** &nbsp;🔄  ❓
> […](#) ...
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年10月11日(星期三) 中午11:22 收件人: ***@***.***&gt;; 抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 选择了始终显示系统托盘图标，可不可以把Finder 上的“展示系统托盘图标”的 箭头按钮 给隐藏掉 (Issue #584) 大佬，这些图标的间距能调小一点吗？13寸的surface，桌面空间寸土寸金啊😂 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

是的，就是一个按钮间距的功能，感谢大佬👍👍👍
