### ISSUE TITLE
最新版本的网易云音乐顶部栏无法切歌暂停

### ISSUE THREAD

**Issue by xunyoyo** [mydockfinder/mydockfinder#585]
<img width="207" alt="image" src="https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/33387866/473c74c0-d8fe-4412-811d-31d4e150ad49">

无法进行暂停播放或者切歌

<img width="317" alt="image" src="https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/33387866/eb7a1cae-7f49-4cad-9132-c4febc9e6beb">

**Comment by mydockfinder** [comment]
看看播放器设置里面 我记得有个媒体案件响应还是媒体按键控制播放的，把他开启就可以了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月14日(星期六) 中午12:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 最新版本的网易云音乐顶部栏无法切歌暂停 (Issue #585)





  
无法进行暂停播放或者切歌

**Comment by xunyoyo** [comment]
感谢开发者回复支持，问题已解决
