### ISSUE TITLE
[Feature Request] Add a better network icon

### ISSUE THREAD

**Issue by zina0316** [mydockfinder/mydockfinder#588]
可以增加這個圖示嗎？
![brave_9KGgV0IUI8](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/94322065/b9282628-42bb-48d5-8411-b0191708ca7c)
我爸平常回關掉我的網路，我每次要確認我有沒有網路都要打開工作列或者是進到設定看。

**Comment by mydockfinder** [comment]
有啊，是个网线口的图标




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月22日(星期天) 晚上9:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] [Feature Request] Add a better network icon (Issue #588)





 
可以增加這個圖示嗎？
 
 我爸平常回關掉我的網路，我每次要確認我有沒有網路都要打開工作列或者是進到設定看。

**Comment by zina0316** [comment]
沒有網路他不會顯示

**Comment by mydockfinder** [comment]
不应该&nbsp; &nbsp;没有网络那就是个空的WiFi
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月23日(星期一) 上午10:46
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] [Feature Request] Add a better network icon (Issue #588)





 
沒有網路他不會顯示

**Comment by zina0316** [comment]
重裝成功了
