### ISSUE TITLE
大佬们，在哪能直接打包下载官网图标，只能一个个下载吗？

### ISSUE THREAD

**Issue by larva2333** [mydockfinder/mydockfinder#59]

**Comment by mydockfinder** [comment]
额 只能一个一个下，打包超过100M了 蓝奏云不能超100M




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月5日(星期六) 晚上6:40
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder] 大佬们，在哪能直接打包下载官网图标，只能一个个下载吗？ (#59)

**Comment by larva2333** [comment]
推荐一个Chrome插件：`fatkun` `ALT+Z`可以批量保存当前页面图片，注意浏览器设置要关闭下载前确认框，不然可能会弹出几百次。。。
