### ISSUE TITLE
Myfinder  可以新增切換使用者的按鈕

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#590]
如題

**Comment by mydockfinder** [comment]
嗯 下个版本加上，是系统账户那个吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月24日(星期二) 下午5:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] Myfinder  可以新增切換使用者的按鈕 (Issue #590)





 
如題

**Comment by linitfor** [comment]
請問這周有時間加入這個功能嗎?

**Comment by mydockfinder** [comment]
嗯&nbsp; 加
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月8日(星期三) 上午9:25
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Myfinder  可以新增切換使用者的按鈕 (Issue #590)





 
請問這周有時間加入這個功能嗎?
