### ISSUE TITLE
Launchpad 启动盘 底部的 圆点    不支持 点击 并立即调转到自己想要的页面

### ISSUE THREAD

**Issue by chuck00000** [mydockfinder/mydockfinder#591]
![69c3960a7e987a4a2c6b680774fa68a9](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/98159699/fdd4dfd8-9290-45ec-9b46-c6ff8db53fb2)

目前启动盘上下翻页，只能鼠标滚轮 滚动翻页，鼠标拖划翻页，但不支持点击 底部的 圆点，立即调转想要的页面，页数多了上下翻页有点麻烦，苹果macOS是支持的（如图所示）

**Comment by mydockfinder** [comment]
好的&nbsp; 下个版本加上




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月25日(星期三) 下午4:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] Launchpad 启动盘 底部的 圆点    不支持 点击 并立即调转到自己想要的页面 (Issue #591)





 

 
目前启动盘上下翻页，只能鼠标滚轮 滚动翻页，鼠标拖划翻页，但不支持点击 底部的 圆点，立即调转想要的页面，页数多了上下翻页有点麻烦，苹果macOS是支持的（如图所示）
