### ISSUE TITLE
Launchpad 背景动态模糊 自从1.9.9 版本就有马赛克条纹

### ISSUE THREAD

**Issue by chuck00000** [mydockfinder/mydockfinder#597]
1.之前启动台背景动态模糊不这样的，没有毛边，自从1.9.9的动态模糊有如图所示的严重毛边，是透明渲染方式改了？
![Screenshot 2023-11-04 124845](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/98159699/7ede8aad-80da-4b19-ac83-097c0041b055)
![Screenshot 2023-11-04 124909](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/98159699/c7d34fb2-3195-4621-a75a-9f5d3b8ee70e)
![Screenshot 2023-11-04 125437](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/98159699/2147884a-eee5-46e7-b2aa-8f7d2bb3bea5)
![Screenshot 2023-11-04 125255](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/98159699/f6d41a1c-bc83-43b1-846a-72078d65c543)
![Screenshot 2023-11-04 1252551](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/98159699/2bb58732-7e80-4b1a-ae31-ea5c07fc82e3)

2.下面这张图没开背景动态模糊的效果，没有毛边
![Screenshot 2023-11-04 125944](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/98159699/881db38a-79d2-4d18-af37-3f62ddbb998d)

**Comment by chuck00000** [comment]
放大图片能看出严重毛边

**Comment by chuck00000** [comment]
开了 启动台自定义背景模糊 + 动态模糊 + 模糊度最低

**Comment by mydockfinder** [comment]
是win10系统吗






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月4日(星期六) 中午1:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Launchpad 背景动态模糊 自从1.9.9 版本就有严重毛边 (Issue #597)





 
开了 启动台自定义背景模糊 + 动态模糊 + 模糊度最低
 
&mdash;

**Comment by chuck00000** [comment]
Windows 11

**Comment by mydockfinder** [comment]
那我优化一下
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月4日(星期六) 中午1:50
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Launchpad 背景动态模糊 自从1.9.9 版本就有严重毛边 (Issue #597)





 
Windows 11
