### ISSUE TITLE
藍芽裝置顯示選擇

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#599]
一個突發的想法，
我們目前這些顯示圖示或與電量的部分
可否更進一步自訂義那些裝置要顯示出來呢? 個別顯示方式分別是什麼 ?
對我們來說，通常會需要顯示出來的
大概就是藍芽耳機有沒有顯示
藍芽滑鼠還有多少電量
其他像手機或其他裝置
顯示出來也沒有意義
![圖片](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/371f001d-3257-4dc7-8a1f-33bdb70732f7)

![圖片](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/bca96450-81a0-461c-b04c-921a1545e151)

**Comment by mydockfinder** [comment]
不太好做配置文件，因为配置文件保存是个问题，名字的话蓝牙设备重名很多，mac地址有点不安全




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月14日(星期二) 晚上6:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 藍芽裝置顯示選擇 (Issue #599)





 
一個突發的想法，
 我們目前這些顯示圖示或與電量的部分
 可否更進一步自訂義那些裝置要顯示出來呢? 個別顯示方式分別是什麼 ?
 對我們來說，通常會需要顯示出來的
 大概就是藍芽耳機有沒有顯示
 藍芽滑鼠還有多少電量
 其他像手機或其他裝置
 顯示出來也沒有意義

**Comment by linitfor** [comment]
好吧 沒關係
