### ISSUE TITLE
Myfinder 提供類似mac bartender 功能

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#600]
不知道大大有沒有辦法實現類似下面這個Mac app 的功能呢?

https://leadingmrk.com/bartender-4-tutorial/
![CleanShot-2022-11-22-at-23 37 48](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/82b50a89-5b53-4ed0-90f1-3d7f7d6a346c)

**Comment by mydockfinder** [comment]
啊 。。。。&nbsp; &nbsp;我正在做的就是这个，只不过我没加设置哪个是隐藏的，就是超出不能显示的在隐藏里面了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月14日(星期二) 晚上6:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] Myfinder 提供類似mac bartender 功能 (Issue #600)





 
不知道大大有沒有辦法實現類似下面這個Mac app 的功能呢?
 
https://leadingmrk.com/bartender-4-tutorial/
