### ISSUE TITLE
测试版 1.9.9.4  启动台的图标自定义大小以及间距 自己恢复到默认状态

### ISSUE THREAD

**Issue by chuck00000** [mydockfinder/mydockfinder#601]
1.测试版 1.9.9.4 更新后   启动台的图标自定义大小以及间距 自动恢复到默认状态，再去设置里怎么调都不起效果。

2.还有我之前提到的启动台背景动态模糊 整个背景都是马赛克条纹，亮色壁纸更明显看出来；我看了一下，应该是没修

3.提示一处翻译的小问题：设置 → 关于  Library 后面 多打了一个字母 d

![Screenshot (4)](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/98159699/cb87944a-8aa5-47e6-a817-391c52b0dfd0)

**Comment by mydockfinder** [comment]
1、我测试看看
2、这是个鱼和熊掌不可兼得的问题，我是优化了模糊改成桌面分辨率的四分之一了然后放大渲染，这样模糊就不怎么占GPU了
3好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月19日(星期天) 晚上9:36
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] 测试版 1.9.9.4  启动台的图标自定义大小以及间距 自己恢复到默认状态 (Issue #601)





 
1.测试版 1.9.9.4 更新后   启动台的图标自定义大小以及间距 自动恢复到默认状态，再去设置里怎么调都不起效果。
 
2.还有我之前提到的启动台背景动态模糊 整个背景都是马赛克条纹，亮色壁纸更明显看出来；我看了一下，应该是没修
 
3.提示一处翻译的小问题：设置 → 关于  Library 后面 多打了一个字母 d

**Comment by chuck00000** [comment]
那 启动台图标大小 & 间距 估计是bug了，我之前重启了好几次电脑也没有好，依然是默认的大小 & 间距，刚开机自己突然好了，恢复了我之前定义的大小😅

**Comment by mydockfinder** [comment]
emmmmmmm&nbsp; 是不是改启动台的所在屏幕了，自定义的配置是跟随屏幕的，或者可能就是卡了必须重启系统
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月20日(星期一) 上午10:15
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 测试版 1.9.9.4  启动台的图标自定义大小以及间距 自己恢复到默认状态 (Issue #601)





 
那 启动台图标大小 &amp; 间距 估计是bug了，我之前重启了好几次电脑有没有好，依然是默认的大小 &amp; 间距，刚开机自己突然好了，恢复了我之前定义的大小😅

**Comment by chuck00000** [comment]
我没动，就一个显示器。

**Comment by mydockfinder** [comment]
那可能就是卡了&nbsp; &nbsp; 最近的win11系统bug挺多的
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月20日(星期一) 上午10:22
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 测试版 1.9.9.4  启动台的图标自定义大小以及间距 自己恢复到默认状态 (Issue #601)





 
我没动，就一个显示器。
