### ISSUE TITLE
MyFinder多屏幕时显示异常

### ISSUE THREAD

**Issue by strange-qwq** [mydockfinder/mydockfinder#613]
多屏幕分辨率不同时，设置仅主屏幕显示MyFinder，副屏顶部也会出现窗口边界。

似乎是从1.9.9版本开始的（不太确定，似乎是最近一两个版本开始出现的）

主屏：1920 * 1080
副屏：3840 * 2160

**Comment by mydockfinder** [comment]
这两个屏幕是怎么放的位置，设置里面能截图一下吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月19日(星期二) 上午9:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] MyFinder多屏幕时显示异常 (Issue #613)





 
多屏幕分辨率不同时，设置仅主屏幕显示MyFinder，副屏顶部也会出现窗口边界。
 
似乎是从1.9.9版本开始的（不太确定，似乎是最近一两个版本开始出现的）
 
主屏：1920 * 1080
 副屏：3840 * 2160

**Comment by strange-qwq** [comment]
![image](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/73089181/d9e8dd88-592b-46aa-9593-71915fe683bb)

主屏幕缩放 100%
副屏缩放 150%
不知道跟屏幕缩放有没有关系

**Comment by strange-qwq** [comment]
我截图的这个是我工作的电脑，家里的电脑好像好像是底部对齐的

**Comment by mydockfinder** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月19日(星期二) 上午10:42
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] MyFinder多屏幕时显示异常 (Issue #613)





 
我截图的这个是我工作的电脑，家里的电脑好像好像是底部对齐的
 
&mdash;
