### ISSUE TITLE
Myfinder 提供類似mydocker 智慧隱藏模式

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#618]
想請問大大Myfinder 提供類似mydocker 智慧隱藏模式，這樣子是否容易實現呢?
想要這個功能，感謝。

**Comment by mydockfinder** [comment]
不太容易实现，不过我倒是打算做，最难的地方就是窗口边界了，隐藏就要取消边界显示就要打开，频繁的打开取消系统就会很卡，有的软件不稳定就会出错或者崩溃例如adobe全家桶，但是不开边界桌面图标就会被myfinder遮挡，目前这是唯一的难点在想怎么处理




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月25日(星期一) 上午8:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] Myfinder 提供類似mydocker 智慧隱藏模式 (Issue #618)





 
想請問大大Myfinder 提供類似mydocker 智慧隱藏模式，這樣子是否容易實現呢?
 想要這個功能，感謝。

**Comment by linitfor** [comment]
好喔 聽起來就有點難 加油 XD
