### ISSUE TITLE
1.9.9.6 版本的台前調度 好像又比較頻繁出現暫時性的點擊無法反應的狀況

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#625]
如題
我的設定如下:

![圖片](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/f389433f-337c-4f64-a77c-2b2e197d7755)

![圖片](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/cd1fe63c-e842-4a3f-b854-148d2d634844)

**Comment by linitfor** [comment]
好像把動畫速度調成 1.0x，這個暫時凍結的狀況，好像會變好。

**Comment by mydockfinder** [comment]
能来个视频吗我看一下具体情况



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月5日(星期五) 中午11:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 1.9.9.6 版本的台前調度 好像又比較頻繁出現暫時性的點擊無法反應的狀況 (Issue #625)





 
好像把動畫速度調成 1.0x，這個暫時凍結的狀況，好像會變好。
 
&mdash;
