### ISSUE TITLE
[1.9.9.7][Feature] 專注助手 在 myfinder 一鍵開啟

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#626]
如題
是否可以提供 直接 在 myfinder 上 直接按鈕，
(一鍵快速開啟，不用額外開啟選單 )
還有圖示標示是否有開啟勿擾模式
![圖片](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/e4f88c70-d210-4294-b36d-a38c8b9c0f3e)

這樣可以在開會時
可以快速確認是否有開啟勿擾模式

**Comment by mydockfinder** [comment]
好的，我可以改成跟WiFi和蓝牙一样点左边的圆形按钮直接打开，点文字再展开菜单




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月5日(星期五) 中午11:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 專注助手 在 myfinder 一鍵開啟 (Issue #626)





 
如題
 是否可以提供 直接 在 myfinder 上 直接按鈕，
 (一鍵快速開啟，不用額外開啟選單 )
 還有圖示標示是否有開啟勿擾模式
 default.png (view on web)
 
這樣可以在開會時
 可以快速確認是否有開啟勿擾模式

**Comment by linitfor** [comment]
請問下次更新預計是什麼時候? 
可以先幫我加入專注模式直接在myfinder 上嗎?
因為最近常開會，蠻常需要快速切換這個功能。

**Comment by mydockfinder** [comment]
这周日会更新&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月22日(星期一) 下午2:31
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 專注助手 在 myfinder 一鍵開啟 (Issue #626)





 
請問下次更新預計是什麼時候?
 可以先幫我加入專注模式直接在myfinder 上嗎?
 因為最近常開會，蠻常需要快速切換這個功能。

**Comment by linitfor** [comment]
哇 大大忘了幫我增加這個功能了 再麻煩大大喔
最近會議
常常會需要確認有沒有開啟專注模式

**Comment by linitfor** [comment]
專注模式的功能，再麻煩大大喔~ 感謝

**Comment by mydockfinder** [comment]
我加了啊 直接点控制中心的月亮图标就打开了，跟WiFi蓝牙一样操作




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月23日(星期五) 中午11:28
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 專注助手 在 myfinder 一鍵開啟 (Issue #626)





 
專注模式的功能，再麻煩大大喔~ 感謝
 
&mdash;

**Comment by linitfor** [comment]
嗯 我知道控制中心有，
我的意思是像台前調度
額外增加單一按鈕直接顯示在myfinder上
這樣可以直接顯示現在是否有開啟專注模式
也可以比較快速一點切換專注模式

因為系統有一些自動開啟專注模式
有時候會忘記關掉
導致有些通知沒有即時收到

因為專注模式打開

mac 上是長這樣，在切換不同專注模式狀態
會顯示不同圖案，提供使用者確認目前開啟的是哪一個狀態。
![image](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/53db2e49-17b1-4c96-92a9-258ea8529bcf)

**Comment by mydockfinder** [comment]
哦 这个啊可以我下个版本加上&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月24日(星期六) 上午9:37
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 專注助手 在 myfinder 一鍵開啟 (Issue #626)





 
嗯 我知道控制中心有，
 我的意思是像台前調度
 額外增加單一按鈕直接顯示在myfinder上
 這樣可以直接顯示現在是否有開啟專注模式
 也可以比較快速一點切換專注模式
 
因為系統有一些自動開啟專注模式
 有時候會忘記關掉
 導致有些通知沒有即時收到
 
因為專注模式打開
 
mac 上是長這樣，在切換不同專注模式狀態
 會顯示不同圖案，提供使用者確認目前開啟的是哪一個狀態。
 4A7F0372-CEA4-48D9-A740-2E36C98C0127.png (view on web)

**Comment by linitfor** [comment]
大大這周忙嗎? 這周有機會幫忙更新這個功能嗎?
