### ISSUE TITLE
Mydockfinder 天氣資料來源

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#629]
想請教一下大大，有關於目前現行使用的天氣資料來源是哪裡的?
一般天氣資料大概有三個 白天溫度, 晚上溫度，現在溫度 
有一些會再多一個體感溫度
好像目前我們使用的顯示氣溫偏低，這是抓取的是體感溫度是嗎?還是是最低溫度?
這個氣溫程式，有辦法自定義來源嗎?

**Comment by linitfor** [comment]
有看到大大新的更新了，感覺更好閱讀了，很不錯耶

不過不確定是大大目前使用的氣象資料，跟Google 的有點差距 XD
還是我的氣象資料沒有正確更新，顯示出來的差距
![圖片](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/d9f41094-bf8b-47c1-9c9f-1ba8caf39578)

**Comment by mydockfinder** [comment]
是的 我这个天气源不是很准，但是全球都能用支持经纬度的，其他预报都要设置城市的代码比较不好适配




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月29日(星期一) 下午3:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Mydockfinder 天氣資料來源 (Issue #629)





 
有看到大大新的更新了，感覺更好閱讀了，很不錯耶
 
不過不確定是大大目前使用的氣象資料，跟Google 的有點差距 XD
 還是我的氣象資料沒有正確更新，顯示出來的差距
 default.png (view on web)
 
&mdash;

**Comment by linitfor** [comment]
好像更新速度的問題，今天觀察就蠻不錯的，
喜歡這個更新耶，跟iphone 的一樣，很直觀，讚讚b

**Comment by mydockfinder** [comment]
这个界面是按mac os14的桌面小组件改的




№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月30日(星期二) 下午3:06
***@***.***&gt;;
抄送:&nbsp;"№じ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [mydockfinder/mydockfinder-for-Win10-Win11] Mydockfinder 天氣資料來源 (Issue #629)





 
好像更新速度的問題，今天觀察就蠻不錯的，
 喜歡這個更新耶，跟iphone 的一樣，很直觀，讚讚b
