### ISSUE TITLE
myfinder不能正常打开“查看”等界面

### ISSUE THREAD

**Issue by Healthcliff-Ding** [mydockfinder/mydockfinder#63]
新装的myfinder在左上角只有windows徽标和“访达”两项鼠标左击有下拉菜单，其余的都没有

另外，我的机器上官网显示DNS错误，有点点奇怪

**Comment by Healthcliff-Ding** [comment]
也就是，文件、编辑、显示、前往、窗口都不能打开

**Comment by Healthcliff-Ding** [comment]
就比如 文件 编辑 显示 前往 等

**Comment by mydockfinder** [comment]
因为没加功能




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月6日(星期天) 晚上11:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] myfinder不能正常打开“查看”等界面 (#63)





 
就比如 文件 编辑 显示 前往 等
 
&mdash;
