### ISSUE TITLE
關於啟動台的使用體驗與建議

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#630]
關於啟動台的使用體驗與建議
1. 收集程式的資料夾，在名稱上好像不能有空格，
如下圖，其實我是想要命名Office Tool，但他會變成OfficeTool
![圖片](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/671bdf89-a01c-44de-8729-a291d08a4828)
2. 在收集程式的資料夾要更改命名的時候，會出現下圖奇怪的狀況，顯示字體突然放大糊掉，或者不顯示字體
![圖片](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/c740e3ac-83b6-4370-abce-e429cd35a35d)

3. 建議提供選項讓使用者自訂，在開啟啟動台下 ESC 按鍵設定成跳離啟動台，(目前ESC 按鍵，是設定成清除輸入)
    但我們清除輸入已經有backspace or delete。 ESC 可以是其他功能選項。

**Comment by mydockfinder** [comment]
好的 启动台回来优化一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月12日(星期五) 下午5:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 關於啟動台的使用體驗與建議 (Issue #630)





 
關於啟動台的使用體驗與建議
  
 
收集程式的資料夾，在名稱上好像不能有空格，
 如下圖，其實我是想要命名Office Tool，但他會變成OfficeTool
 default.png (view on web)
 
 
 
在收集程式的資料夾要更改命名的時候，會出現下圖奇怪的狀況，顯示字體突然放大糊掉，或者不顯示字體
 default.png (view on web)
 
 
 
建議提供選項 讓使用者 自訂 ESC 按鍵設定成跳離啟動台，(目前ESC 按鍵，是設定成清除輸入)

**Comment by linitfor** [comment]
大大出去玩嗎 XD

**Comment by mydockfinder** [comment]
没啊，前一阵发烧了，身边都是甲流乙流
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月15日(星期一) 下午4:23
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 關於啟動台的使用體驗與建議 (Issue #630)





 
大大出去玩嗎 XD

**Comment by linitfor** [comment]
天啊，保重身體!!
最近的流感真的多.......
我比你趕流行，去年十月剛開始流行，就先發燒過的 @@

**Comment by mydockfinder** [comment]
去年那阵也是有一波流感，我是刚有点就给吃药预防了，这回没躲过去




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月15日(星期一) 下午4:42
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 關於啟動台的使用體驗與建議 (Issue #630)





 
天啊，保重身體!!
 最近的流感真的多.......
 我比你趕流行，去年十月剛開始流行，就先發燒過的 @@
 
&mdash;

**Comment by linitfor** [comment]
身體好多了嗎? 一切平安喔~~

**Comment by mydockfinder** [comment]
谢谢，已经好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月18日(星期四) 上午10:14
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 關於啟動台的使用體驗與建議 (Issue #630)





 
身體好多了嗎? 一切平安喔~~
 
&mdash;

**Comment by linitfor** [comment]
另外，有辦法在啟動台的圖示上，按右鍵解除安裝程式嗎?

**Comment by mydockfinder** [comment]
我尽量，有点不会我得找找例子&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月19日(星期五) 上午10:17
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 關於啟動台的使用體驗與建議 (Issue #630)





 
另外，有辦法在啟動台的圖示上，按右鍵解除安裝程式嗎?

**Comment by linitfor** [comment]
另外，啟動台的背景模糊功能，好像在雙螢幕下，會怪怪的

原本，背景有一個程式開啟置中在使用的螢幕中心，
如下圖:
![圖片](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/7827093f-8ebe-4eec-8859-de363fc39901)

但開啟啟動台，啟動台背景去抓的畫面，
會發現這個程式，在啟動台背景卻往上跑了。
如下圖:
![圖片](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/b79a03cd-430d-4b8b-9c87-f5859124d5e7)

我猜測原因是因為我的雙螢幕是上下組合的。
你在抓取啟動台背景是使用所有螢幕的中心去抓。

**Comment by mydockfinder** [comment]
好的，因为当前屏幕背景是用的模拟算法，并不是真实的背景，应该是位置计算错误了，我修复一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月24日(星期三) 上午9:57
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 關於啟動台的使用體驗與建議 (Issue #630)





 
另外，啟動台的背景模糊功能，好像在雙螢幕下，會怪怪的
 
原本，背景有一個程式開啟置中在使用的螢幕中心，
 如下圖:
 default.png (view on web)
 
但開啟啟動台，啟動台背景去抓的畫面，
 會發現這個程式，在啟動台背景卻往上跑了。
 如下圖:
 default.png (view on web)
 
我猜測原因是因為我的雙螢幕是上下組合的。
 你在抓取啟動台背景是使用所有螢幕的中心去抓。
 
&mdash;

**Comment by linitfor** [comment]
雙螢幕 啟動台背景畫面看起來也修正好了，謝謝大大囉!

**Comment by mydockfinder** [comment]
不客气




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月29日(星期一) 下午2:46
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 關於啟動台的使用體驗與建議 (Issue #630)





 
雙螢幕 啟動台背景畫面看起來也修正好了，謝謝大大囉!
 
&mdash;
