### ISSUE TITLE
“通知”中的系统通知和app通知全开，但始终无一条右上角弹窗通知

### ISSUE THREAD

**Issue by Godshaos** [mydockfinder/mydockfinder#633]
![Snipaste_2024-01-17_19-22-35](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/89079910/713846ca-f344-43ab-91f0-b479db23a86c)、
![Snipaste_2024-01-17_19-28-05](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/89079910/6a377a4f-ded4-4aac-9f30-7dd8196e5552)
![Snipaste_2024-01-17_19-28-12](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/89079910/7fe64e2d-08df-4e32-a8be-772270360c1a)
qq接受消息时有红点但是无右上角弹窗通知

**Comment by mydockfinder** [comment]
怪事，按理说有红点应该就有横幅通知的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月17日(星期三) 晚上7:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] “通知”中的系统通知和app通知全开，但始终无一条右上角弹窗通知 (Issue #633)





 
Snipaste_2024-01-17_19-22-35.png (view on web)、
 Snipaste_2024-01-17_19-28-05.png (view on web)
 Snipaste_2024-01-17_19-28-12.png (view on web)
 qq接受消息时有红点但是无右上角弹窗通知

**Comment by Godshaos** [comment]
> 怪事，按理说有红点应该就有横幅通知的
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人: ***@***.***&gt;; 
> 发送时间: 2024年1月17日(星期三) 晚上7:37
> 收件人: ***@***.***&gt;; 
> 抄送: ***@***.***&gt;; 
> 主题: [mydockfinder/mydockfinder-for-Win10-Win11] “通知”中的系统通知和app通知全开，但始终无一条右上角弹窗通知 (Issue #633)
> 
> 
> 
> 
> 
>  
> Snipaste_2024-01-17_19-22-35.png (view on web)、
>  Snipaste_2024-01-17_19-28-05.png (view on web)
>  Snipaste_2024-01-17_19-28-12.png (view on web)
>  qq接受消息时有红点但是无右上角弹窗通知
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

请问有什么解决的方法或是建议吗。

**Comment by Godshaos** [comment]
> 怪事，按理说有红点应该就有横幅通知的
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人: ***@***.***&gt;; 
> 发送时间: 2024年1月17日(星期三) 晚上7:37
> 收件人: ***@***.***&gt;; 
> 抄送: ***@***.***&gt;; 
> 主题: [mydockfinder/mydockfinder-for-Win10-Win11] “通知”中的系统通知和app通知全开，但始终无一条右上角弹窗通知 (Issue #633)
> 
> 
> 
> 
> 
>  
> Snipaste_2024-01-17_19-22-35.png (view on web)、
>  Snipaste_2024-01-17_19-28-05.png (view on web)
>  Snipaste_2024-01-17_19-28-12.png (view on web)
>  qq接受消息时有红点但是无右上角弹窗通知
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

我重新在虚拟机内测试了，是可以使用的，对比了两方的不同，发现是专注助手的问题，关闭之后回复弹窗，感谢你的注意，此问题已经解决。
