### ISSUE TITLE
Mydock 開啟視窗邊界功能 特定軟體失效 

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#635]
如題 Mydock 開啟視窗邊界功能 在Microsoft Onenote 的整頁模式 會失效

https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/dbec08ee-1f94-400b-848c-97a9d006d76c

**Comment by mydockfinder** [comment]
下面那块不是mydock的窗口边界，那是系统任务栏的大小，应该是OneNote没有适配其他程序开启窗口边界的功能，只保留了系统任务栏的区域




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月18日(星期四) 下午3:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] Mydock 開啟視窗邊界功能 特定軟體失效  (Issue #635)





 
如題 Mydock 開啟視窗邊界功能 在Microsoft Onenote 的整頁模式 會失效
 
https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/dbec08ee-1f94-400b-848c-97a9d006d76c

**Comment by linitfor** [comment]
我印象windows 11 好像有多弄了一個平板模式。
我猜你講的是Onenote 是不是，預設開啟整頁模式後，就讓窗口邊界變成平板模式的邊界了
但是如下圖，我並沒有啟用這個功能，但onenote 邊界還是往下跑了......


![圖片](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/6ec37e1b-9d22-46b3-bb7a-2459d2093e79)
