### ISSUE TITLE
Mydock 資料夾 使用縮放模式 + 菜單模式 的小問題

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#638]
發現一個體驗上的問題，就是我設定Mydock 資料夾 使用縮放模式 + 菜單模式 下
但點擊完我選的檔案，發現mydock 放大後，不會自己縮小回去
但是扇形模式 or 網格模式 是可以的
https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/6976ad16-7b19-4bee-a66b-10b42572bb32

Mydock設定縮放模式
![圖片](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/572a438c-0d7f-4bd4-87e0-71729b3de0c7)

資料夾 設定是 菜單模式
![圖片](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/22cf7670-bfb8-487d-ba4c-6be5eb352096)

**Comment by mydockfinder** [comment]
嗯 确实是，下个版本修复&nbsp; 周日更新




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月25日(星期四) 上午9:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] Mydock 資料夾 使用縮放模式 + 菜單模式 的小問題 (Issue #638)





 
發現一個體驗上的問題，就是我設定Mydock 資料夾 使用縮放模式 + 菜單模式 下
 但點擊完我選的檔案，發現mydock 放大後，不會自己縮小回去
 但是扇形模式 or 網格模式 是可以的
 https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/6976ad16-7b19-4bee-a66b-10b42572bb32
 
Mydock設定縮放模式
 default.png (view on web)
 
資料夾 設定是 菜單模式
 default.png (view on web)

**Comment by linitfor** [comment]
1.9.9.7 beta 修復完成，謝謝大大 ^.^b
