### ISSUE TITLE
天气图标点击无反应

### ISSUE THREAD

**Issue by DreammStill** [mydockfinder/mydockfinder#642]
我在dock中添加了天气图标，但是点击没有反应，而且在设置中没有关于天气的相关选项，win11 23.12更新，amd r75800H处理器，3060显卡

**Comment by mydockfinder** [comment]
右键设置图标，然后地区那里改一下位置




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月30日(星期二) 晚上6:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 天气图标点击无反应 (Issue #642)





 
我在dock中添加了天气图标，但是点击没有反应，而且在设置中没有关于天气的相关选项，win11 23.12更新，amd r75800H处理器，3060显卡

**Comment by DreammStill** [comment]
> 右键设置图标，然后地区那里改一下位置
> [...](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人： ***@***.***>; 发送时间: 2024年1月30日(星期二) 晚上6:47 收件人： ***@***.***>; 抄送： ***@***.***>; 主题： [mydockfinder/mydockfinder-for-Win10-Win11] 天气图标点击无反应 （Issue #642） 我在dock中添加了天气图标，但是点击没有反应，而且在设置中没有关于天气的相关选项，win11 23.12更新，amd r75800H处理器，3060显卡 — 直接回复此电子邮件，在 GitHub 上查看或取消订阅。 您收到此消息是因为您订阅了此线程。邮件 ID：***@***.***>

我该怎么操作？是更改win设置里面的地区吗

**Comment by DreammStill** [comment]
> 右键设置图标，然后地区那里改一下位置
> [...](javascript:void(0);)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年1月30日(星期二) 晚上6:47 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [mydockfinder/mydockfinder-for-Win10-Win11] 天气图标点击无反应 (Issue #642) 我在dock中添加了天气图标，但是点击没有反应，而且在设置中没有关于天气的相关选项，win11 23.12更新，amd r75800H处理器，3060显卡 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

我在右键设置图标中似乎并没有找到地区设置，更改win地区似乎也不管用，我因为xbox所以系统地区必须是美国

**Comment by mydockfinder** [comment]
![image](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/32895737/36c4649b-7c1f-47a2-af57-5d3471e7f521)

**Comment by DreammStill** [comment]
> ![image](https://private-user-images.githubusercontent.com/32895737/300792881-36c4649b-7c1f-47a2-af57-5d3471e7f521.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MTUzMzAsIm5iZiI6MTcwNjYxNTAzMCwicGF0aCI6Ii8zMjg5NTczNy8zMDA3OTI4ODEtMzZjNDY0OWItN2MxZi00N2EyLWFmNTctNWQzNDcxZTdmNTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDExNDM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlYTllYjg2MWYzMTYxMWEyZTFhYWNmNjM0NGY0ODc1OTg3ZTBiNjk2YmZlMzAyMWMzMDk4NjViODNlN2JiZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CWBgd0jDxeFuj_ny47ZAoyjSJngXM2kNwHktKHCXqjU)

好了好了，谢谢大佬
