### ISSUE TITLE
Tray icon not working.

### ISSUE THREAD

**Issue by SniperUSA** [mydockfinder/mydockfinder#650]
I have been using MyDocFinder for a minute and I couldn't find the tray icon. I can now but my problem is it does not show any icons at all. it keeps saying this option that says show trayico but never does anything.
![Mydocfinder](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/160540967/2211a63c-cdea-4dff-82eb-02a7cbc07483)

**Comment by mydockfinder** [comment]
Can you record a video, I'll take a look at the specifics




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月20日(星期二) 凌晨4:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] Can&#39;t find tray icon. (Issue #650)





 
I have been using MyDocFinder for a minute and I couldn't find the tray icon. I can now but my problem is it does not show any icons at all.

**Comment by SniperUSA** [comment]
![Uploading Screenshot 2024-02-20 100718.png…]()

**Comment by SniperUSA** [comment]
![Uploading 2024-02-20-10-25-04.gif…]()

**Comment by mydockfinder** [comment]
This is an early free version that has stopped updating

**Comment by SniperUSA** [comment]
Thank You. I managed to update MyDocFinder and now the tray icons work. 
![image](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/160540967/cb4f0af5-038b-4ada-8b9f-80fce4652501)

**Comment by LiveEkansh** [comment]
How do i upade it? Im stuck on the same problem.

**Comment by iurybrenner** [comment]
Help, im with the same problem, but i already upadated
