### ISSUE TITLE
[1.9.9.7][BUG] 電池監控選項影響Mydockfinder 穩定性

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#654]
發現一個新加功能的問題
就是把電池百分比的選項
改成電池時

然後插拔電源後，整個mydockfinder 會開始變很慢，像當掉一樣
我是系統管理員刪掉dock.exe
重啟還是會遇到問題

最後是回到config.ini把設定切回不顯示
batteryvalue=0
batterytime=0

再次重啟mydockfinder 就恢復正常。

![圖片](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/7273eead-9ed0-4652-b70c-1b9b4e026e18)

**Comment by mydockfinder** [comment]
好吧，主要我是台式机没有电池，回来找个笔记本测试看看

**Comment by linitfor** [comment]
嗯嗯 这版1.9.9.7目前使用起来，只要不开启电池显示模式切换，就很稳定啦。谢谢大大提供好用工具啦

除了有一个我还在观察测试的功能，感觉有一点bug，台前调度与新开启程式视窗，在某种情节下，台前调度预览视窗不会下沈到新开启视窗后面。需要使用者再多点一下新开启的程式视窗，台前调度预览视窗才会下沈。
等我捕捉到规律，再另外开一个issue task来讨论吧。

**Comment by linitfor** [comment]
周一晚上更新的這版，看起來就不會影響到mydockfinder 了
但是有一個小疑問，不確定是不是故意設計的  (自己感覺顏色一致會比較順眼 ?)

如果有顯示電池版百分比，剩餘時間會是**黑色**
![圖片](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/ee931c66-d5e7-4fba-955e-3195a0c3245c)

沒有顯示電池版百分比，剩餘時間會是**灰色**
![圖片](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/2af04346-7a6d-426a-836e-3e65c6497051)

**Comment by mydockfinder** [comment]
可以啊 这样看着不错
