### ISSUE TITLE
[1.9.9.7][BUG] 台前調度預覽視窗與新視窗的交互關係

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#658]
如下影面所示
當我桌面已經開啟台前調度，且有一個正在瀏覽的視窗
當我再去mydock 點選開啟一個新的程式
當新的程式開啟
依照台前調度的流程
會把當前已開啟的視窗先歸列到左側的一個新預覽視窗
然後把新點選開啟的視窗放到視窗中間

照道理說，新點選開啟的視窗放到視窗，會被放在視窗中間
而且是上浮在所有視窗的最上面

但是畫面中可以看到，左側預覽視窗，好像沒有下沉到新開啟程式的視窗下方
而是等我把滑鼠滑到台前調度的左側預覽視窗上方，
激活預覽視窗的偵測
左側預覽視窗才會正確的下沉到新開啟程式視窗背後。

https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/a3d1174d-3611-40d5-a926-68023dedc13e

**Comment by mydockfinder** [comment]
确实，应该是窗口跟着dock一起置顶了，我修一下

**Comment by linitfor** [comment]
剛剛更新的這版，尚未解決這個問題，對嗎?

**Comment by mydockfinder** [comment]
对 我还没来及改
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月26日(星期一) 晚上8:09
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] [1.9.9.7][BUG] 台前調度預覽視窗與新視窗的交互關係 (Issue #658)





 
剛剛更新的這版，尚未解決這個問題，對嗎?

**Comment by linitfor** [comment]
請問這周有預計要更新修正這個問題嗎?

**Comment by mydockfinder** [comment]
估计有点悬，这一周改的界面给我改迷茫了&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月13日(星期三) 上午8:22
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] [1.9.9.7][BUG] 台前調度預覽視窗與新視窗的交互關係 (Issue #658)





 
請問這周有預計要更新修正這個問題嗎?

**Comment by linitfor** [comment]
-->好喔 大大加油吧! 感覺你工作也是挺忙的，期待下次更新~

**Comment by linitfor** [comment]
請問這周有預計更新嗎

**Comment by mydockfinder** [comment]
别提了，我脑子抽风把界面也全都改成winui，结果到昨天代码才能跑起来




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月17日(星期天) 上午10:01
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] [1.9.9.7][BUG] 台前調度預覽視窗與新視窗的交互關係 (Issue #658)





 
請問這周有預計更新嗎
 
&mdash;

**Comment by mydockfinder** [comment]
都给我改抑郁了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月17日(星期天) 上午10:01
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] [1.9.9.7][BUG] 台前調度預覽視窗與新視窗的交互關係 (Issue #658)





 
請問這周有預計更新嗎
 
&mdash;

**Comment by linitfor** [comment]
好喔 每天都要刷一下Steam 看看大大有沒有更新🥹🥹🥹

**Comment by mydockfinder** [comment]
这周日吧 我尽量周日能做完
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月26日(星期二) 中午12:30
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] [1.9.9.7][BUG] 台前調度預覽視窗與新視窗的交互關係 (Issue #658)





 
好喔 每天都要刷一下Steam 看看大大有沒有更新🥹🥹🥹

**Comment by linitfor** [comment]
感謝 ~ 期待中

**Comment by linitfor** [comment]
大大新版製作是不是整個大改阿，感覺好像很大工程的樣子?

**Comment by mydockfinder** [comment]
是的，界面全改成winui了，这周一才完成，虽然刚开始改完了体验感觉没啥区别，但是以后界面可以加上很多动画了
我可以开始加新功能了，是要加勿扰模式的单独菜单和台前调度新窗口优化是把




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月2日(星期二) 上午9:41
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] [1.9.9.7][BUG] 台前調度預覽視窗與新視窗的交互關係 (Issue #658)





 
大大新版製作是不是整個大改阿，感覺好像很大工程的樣子?
 
&mdash;

**Comment by linitfor** [comment]
是的 勿扰模式的单独菜单 跟 台前调度新窗口优化 是這一版 比較優先需要的 感謝

**Comment by mydockfinder** [comment]
菜单加完了，因为之前就有现成的只不过没有单独的图标加个图标的事台前调度费点劲，我试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月3日(星期三) 下午2:04
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] [1.9.9.7][BUG] 台前調度預覽視窗與新視窗的交互關係 (Issue #658)





 
是的 勿扰模式的单独菜单 跟 台前调度新窗口优化 是這一版 比較優先需要的 感謝
 
&mdash;

**Comment by linitfor** [comment]
好的 那請問明天有機會更新嗎？ 
期待中....

**Comment by mydockfinder** [comment]
这回可以更新了，基本都做好了除了台前调度
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月6日(星期六) 晚上8:52
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] [1.9.9.7][BUG] 台前調度預覽視窗與新視窗的交互關係 (Issue #658)














 
好的 那請問明天有機會更新嗎？
 期待中....

**Comment by linitfor** [comment]
好喔 感謝啦

**Comment by linitfor** [comment]
更新了 感恩大大 主要功能都恢復了
目前使用起來蠻不錯的
但有出現一兩次不預期當掉閃退
還沒抓到原因 
謝謝大大囉
