### ISSUE TITLE
[1.9.9.7][Issue] Memory 占用持續增加

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#660]
發現一個奇怪的現象
1.9.9.7 這版，好像會一直吃記憶體
我早上放一個早上，發現記憶體吃到800Mb

![圖片](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/b2a64529-77d9-427c-ae7c-149aa61aa6c6)

**Comment by mydockfinder** [comment]
嗯&nbsp; 晚上更新修复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月26日(星期一) 中午1:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] [1.9.9.7][Issue] Memory 占用持續增加 (Issue #660)





 
發現一個奇怪的現象
 1.9.9.7 這版，好像會一直吃記憶體
 我早上放一個早上，發現記憶體吃到800Mb
 
default.png (view on web)

**Comment by linitfor** [comment]
剛更新的這版，剛測試了一會，看起來問題解決囉~
