### ISSUE TITLE
[1.9.9.7][Issue] Mydock 行事曆點擊連結Windows 行事曆功能消失

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#662]
Mydock 行事曆點擊連結Windows 行事曆功能消失了
請問是大大決定取消這個功能嗎?
因為這個功能蠻方便的
可以快速去檢閱或開啟線上會議

另外，大大新加入可以快速預覽行事曆的功能
有考慮未來提供讀取會議行事曆的功能嗎

像calendar flyout app 這種設計
![圖片](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/292fa0d2-a5b2-484c-af31-66d51bc4a537)

這樣可以快速開啟線上會議連結
也可以快速瀏覽每日會議行程

**Comment by mydockfinder** [comment]
是myfinder吧，我记得myfinder可以直接激活这个，新版本改成鼠标右键了

**Comment by linitfor** [comment]
你可能誤會我的意思
先前mydock 上的行事曆，有提供點擊行事曆連結Window 內建的行事曆
連結到下面這個程式，但是這版消失了
![圖片](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/c107e18c-3520-4910-b8f5-f11fccffda5b)

另外，天氣預報連結到內建的天氣，這版也消失了
![圖片](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/af6d1d4f-6235-430e-be6b-e5f223e2ffba)

**Comment by mydockfinder** [comment]
哦 不是改了，是bug。。。。。。。
