### ISSUE TITLE
finder中英文状态不更新

### ISSUE THREAD

**Issue by cweijan** [mydockfinder/mydockfinder#673]
刚接触这个软件, 很喜欢顶部finder, 但是我切换中英文时状态不会改变.

希望老哥能参考一下这个ahk脚本, 它是调用DDL的, 理论上你这个软件也可以.

https://github.com/flyinclouds/KBLAutoSwitch/blob/master/KBLAutoSwitch.ahk

**Comment by mydockfinder** [comment]
emmmm 我用的就是这个原理。。。。。。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月22日(星期五) 晚上10:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] finder中英文状态不更新 (Issue #673)





 
刚接触这个软件, 很喜欢顶部finder, 但是我切换中英文时状态不会改变.
 
希望老哥能参考一下这个ahk脚本, 它是调用DDL的, 理论上你这个软件也可以.
 
https://github.com/flyinclouds/KBLAutoSwitch/blob/master/KBLAutoSwitch.ahk

**Comment by cweijan** [comment]
那可能是有bug导致状态没有及时更新呢

**Comment by mydockfinder** [comment]
有可能&nbsp; 是100%不刷新吗 还是运行一段时间后&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月23日(星期六) 中午1:30
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] finder中英文状态不更新 (Issue #673)





 
那可能是有bug导致状态没有及时更新呢

**Comment by lovesion** [comment]
目前版本的大小写状态更新比较慢,我使用
https://github.com/maxisan137/Lock-Keys-Taskbar-Indicator    
替代了

**Comment by cweijan** [comment]
@lovesion 我试了下,  这个只能显示大小写状态, finder能正确显示... 我的问题是中文输入法的中英文状态显示不及时.

**Comment by mydockfinder** [comment]
好吧，我看了一下他的代码他是100毫秒刷新一次，我是500毫秒一次，那我加快点




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月26日(星期二) 上午9:32
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] finder中英文状态不更新 (Issue #673)





 
目前版本的大小写状态更新比较慢,我使用
 https://github.com/maxisan137/Lock-Keys-Taskbar-Indicator
 替代了
 
&mdash;

**Comment by cweijan** [comment]
@mydockfinder 应该不是刷新频率的问题, 我刚才的回复有误, 不是不及时, 而是不实时, 状态始终不对, 我今晚回家后调试下.

**Comment by mydockfinder** [comment]
嗯&nbsp; 可以的话拍个视频我看一下
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月26日(星期二) 上午9:48
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] finder中英文状态不更新 (Issue #673)





 
@mydockfinder 应该不是刷新频率的问题, 我刚才的回复有误, 不是不及时, 而是不实时, 状态始终不对, 我今晚回家后调试下.

**Comment by cweijan** [comment]
不知道作者是否进行过更新, 目前我的中英文状态更新是正确了.

**Comment by mydockfinder** [comment]
没。。。。。&nbsp; &nbsp; &nbsp;有时这个中英文挺玄学的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月7日(星期六) 晚上11:26
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] finder中英文状态不更新 (Issue #673)





 
不知道作者是否进行过更新, 目前我的中英文状态更新是正确了.
 
&mdash;
