### ISSUE TITLE
能否绕开Steam启动？

### ISSUE THREAD

**Issue by LD-KiLLer** [mydockfinder/mydockfinder#678]
我这边因为是在surface上使用，经常是盒盖睡眠后就领着走，而且在办公室里插拔扩展屏幕。这样会时不时的导致MyDockFinder崩溃，所以我就特意在桌面上创建了一个MyDockFinder的快捷方式，当它崩溃后我通过这个快捷方式去启动。但是快捷方式启动每次都需要启动Steam，很烦。。。 而且Steam启动后，还要再重启下MyDockFinder，这样退出Steam时MyDockFinder才不会退出。

想问下有没有办法不要每次通过快捷方式启动时都启动Steam呢？

**Comment by mydockfinder** [comment]
安装目录里面的dock_64.exe 双击就可以启动了，目前这个休眠崩溃一直没办法修好，无数个版本了都没修好。。。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月29日(星期五) 中午12:26
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] 能否绕开Steam启动？ (Issue #678)





 
我这边因为是在surface上使用，经常是盒盖睡眠后就领着走，而且在办公室里插拔扩展屏幕。这样会时不时的导致MyDockFinder崩溃，所以我就特意在桌面上创建了一个MyDockFinder的快捷方式，当它崩溃后我通过这个快捷方式去启动。但是快捷方式启动每次都需要启动Steam，很烦。。。 而且Steam启动后，还要再重启下MyDockFinder，这样退出Steam时MyDockFinder才不会退出。
 
想问下有没有办法不要每次通过快捷方式启动时都启动Steam呢？

**Comment by LD-KiLLer** [comment]
原来如此，之前创建的快捷方式有误。。。
休眠崩溃还能忍受，毕竟也不是次次都崩溃。只是感觉每次唤醒后，先是窗口边界会出错，会比Dock高出来一节，但是只要用鼠标激活下Dock就正常了，希望有点帮助吧

**Comment by mydockfinder** [comment]
那应该是和系统任务栏重叠造成的，是休眠唤醒进入桌面以后错误吗，这样的话我可以加个登录的检测
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月29日(星期五) 晚上10:59
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 能否绕开Steam启动？ (Issue #678)














 
原来如此，之前创建的快捷方式有误。。。
 休眠崩溃还能忍受，毕竟也不是次次都崩溃。只是感觉每次唤醒后，先是窗口边界会出错，会比Dock高出来一节，但是只要用鼠标激活下Dock就正常了，希望有点帮助吧

**Comment by bootlegseahorse** [comment]
为啥我休眠唤醒从没崩溃过。。包括sleep和hibernate都没事。

我的电脑也是苏菲（Book 3）

**Comment by LD-KiLLer** [comment]
> 那应该是和系统任务栏重叠造成的，是休眠唤醒进入桌面以后错误吗，这样的话我可以加个登录的检测 &nbsp; №じ&nbsp;尐乄鈊~→☆ ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年3月29日(星期五) 晚上10:59 收件人: ***@***.***&gt;; 抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 能否绕开Steam启动？ (Issue #678) 原来如此，之前创建的快捷方式有误。。。 休眠崩溃还能忍受，毕竟也不是次次都崩溃。只是感觉每次唤醒后，先是窗口边界会出错，会比Dock高出来一节，但是只要用鼠标激活下Dock就正常了，希望有点帮助吧 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

准确的说，不是休眠，因为是win11的默认睡眠模式（混合睡眠模式），win11的睡眠模式真的很迷
![PixPin_2024-04-01_08-40-08](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/72300642/c913d0b0-02fe-4b5b-8a6b-d5af07a44467)

**Comment by LD-KiLLer** [comment]
> 为啥我休眠唤醒从没崩溃过。。包括sleep和hibernate都没事。
> 
> 我的电脑也是苏菲（Book 3）

我的是Pro7，感觉还是windows系统的问题，跟硬件的关系应该不大

**Comment by mydockfinder** [comment]
我自己也是，调试还是release的都没事，就算休眠断电重开都没事




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月1日(星期一) 上午8:44
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 能否绕开Steam启动？ (Issue #678)





  
为啥我休眠唤醒从没崩溃过。。包括sleep和hibernate都没事。
 
我的电脑也是苏菲（Book 3）
  
我的是Pro7，感觉还是windows系统的问题，跟硬件的关系应该不大
 
&mdash;

**Comment by LD-KiLLer** [comment]
也有可能是我外接屏幕搞的事情，Surface的屏幕分辨率是2736×1824，外接屏的是1920×1080。其实影响也不大，MyDockFinder也不是每次都出问题，就算崩了重启下也就好了

倒是睡眠唤醒后窗口边界出问题的概率比较大，基本每次都会有
