### ISSUE TITLE
顶部菜单栏上的默认图标按住Ctrl键可以拖动，但自己添加的托盘图标却不能拖动 Only the default icons on MyFinder can be dragged by holding the Ctrl key

### ISSUE THREAD

**Issue by bootlegseahorse** [mydockfinder/mydockfinder#679]
在MyFinder的设置里面，有一个可以按住Ctrl键拖动图标重新排序的选项，但我发现这个Ctrl键拖动功能只对MyFinder自带的默认图标有效，而对自己添加的托盘图标是无效的。希望下一个版本中可以增加一个“可以拖动MyFinder中自行添加的托盘图标”的功能。

In the settings of MyFinder, there is an option to rearrange icons by holding down the Ctrl key and dragging, but I’ve found that this Ctrl key hold-drag feature only works for the default icons that come with MyFinder, and not for the tray icons I’ve added myself. I hope that the next version could include a feature that allows dragging of the custom tray icons added to MyFinder.

**Comment by mydockfinder** [comment]
是的 下个版本就加




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月31日(星期天) 凌晨4:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 顶部菜单栏上的默认图标按住Ctrl键可以拖动，但自己添加的托盘图标却不能拖动 Only the default icons on MyFinder can be dragged by holding the Ctrl key (Issue #679)














 
在MyFinder的设置里面，有一个可以按住Ctrl键拖动图标重新排序的选项，但我发现这个Ctrl键拖动功能只对MyFinder自带的默认图标有效，而对自己添加的托盘图标是无效的。希望下一个版本中可以增加一个“可以拖动MyFinder中自行添加的托盘图标”的功能。
 
In the settings of MyFinder, there is an option to rearrange icons by holding down the Ctrl key and dragging, but I’ve found that this Ctrl key hold-drag feature only works for the default icons that come with MyFinder, and not for the tray icons I’ve added myself. I hope that the next version could include a feature that allows dragging of the custom tray icons added to MyFinder.
