### ISSUE TITLE
一些软件最小化后无法打开窗口

### ISSUE THREAD

**Issue by bao-cn** [mydockfinder/mydockfinder#687]
使用Inletex Easy Meeting Classic Pro软件，将软件最小化后再打开窗口，软件会无法显示，一直处于最小化状态（非台前调度，台前调度未测试）

**Comment by mydockfinder** [comment]
dock上的这个图标右键-选项-不再显示此程序最小化动画,这软件单机能运行吗，我看是局域网共享的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月12日(星期五) 上午9:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 一些软件最小化后无法打开窗口 (Issue #687)














 
使用Inletex Easy Meeting Classic Pro软件，将软件最小化后再打开窗口，软件会无法显示，一直处于最小化状态（非台前调度，台前调度未测试）

**Comment by bao-cn** [comment]
OK，解决了，单机能用是能用，但也要有人连才行😂，局域网用这个挺方便的，开会啥的
