### ISSUE TITLE
Media toast doesn't show up while using MyDockFinder

### ISSUE THREAD

**Issue by 21mtd** [mydockfinder/mydockfinder#691]
![media toast](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/75530836/2a737000-57db-4a57-89be-35b5028694f9)

this thing doesn't show up when using media keys, works when turn off MyDockFinder.
Can you add support to it?

**Comment by mydockfinder** [comment]
There is such a feature in the myfinder volume or media control menu




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月18日(星期四) 凌晨0:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] Media toast doesn&#39;t show up while using MyDockFinder (Issue #691)














 
media.toast.png (view on web)
 
this thing doesn't show up when using media keys, works when turn off MyDockFinder.
 Can you add support to it?

**Comment by 21mtd** [comment]
ahh I see it now, I blindly changed it to macOS style
![image](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/75530836/4a7f0372-66b0-4a8b-89a4-8017dbb535ea)
thank you for your time
