### ISSUE TITLE
[issue][1.9.9.8] mydock 的智慧隱藏功能好像壞掉

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#693]
version: 1.9.9.8 
更新日期:05/26 

更新這版好像mydock 的智慧隱藏功能好像壞掉了，請幫忙查閱一下。

**Comment by mydockfinder** [comment]
好的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月27日(星期一) 下午4:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] [issue][1.9.9.8] mydock 的智慧隱藏功能好像壞掉 (Issue #693)














 
version: 1.9.9.8
 更新日期:05/26
 
更新這版好像mydock 的智慧隱藏功能好像壞掉了，請幫忙查閱一下。

**Comment by linitfor** [comment]
感謝大大 進版修掉了 ^.^b
