### ISSUE TITLE
不小心在设置中关掉了dock栏，没有dock栏进不去设置，无法重新打开dock栏

### ISSUE THREAD

**Issue by wxzhoulf** [mydockfinder/mydockfinder#694]
不小心在设置中关掉了dock栏，没有dock栏进不去设置，无法重新打开dock栏
![image](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/68071555/e67c85ef-2dc0-4f0c-8c04-678245708608)
没有dock栏如何进入设置？

**Comment by mydockfinder** [comment]
在myfinder左边第二个按钮，就是自己总变的那个，圆圈旁边的按钮，点一下二级菜单有偏好设置，我怕图看不见






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月2日(星期天) 中午1:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 不小心在设置中关掉了dock栏，没有dock栏进不去设置，无法重新打开dock栏 (Issue #694)














 
不小心在设置中关掉了dock栏，没有dock栏进不去设置，无法重新打开dock栏
 image.png (view on web)
 没有dock栏如何进入设置？

**Comment by wxzhoulf** [comment]
找到啦，多谢🙏
