### ISSUE TITLE
官网无法打开，被Edge拦截，打开之后变成了另外一个网站（购物网站）

### ISSUE THREAD

**Issue by eliaszon** [mydockfinder/mydockfinder#7]
![20210416_114739](https://user-images.githubusercontent.com/73749474/115050262-28ee5a80-9f0e-11eb-905a-c275cf5d30ce.png)

**Comment by hahagugu233** [comment]
这网站都不是一般的购物网站，卖壮y药的，就离谱，今天已经修好了

**Comment by hahagugu233** [comment]
前天和昨天我遇到过相同的问题
