### ISSUE TITLE
Is it possible to minimize windows to the dock without the UAC prompt: its a little disturbing while working

### ISSUE THREAD

**Issue by teddtastic** [mydockfinder/mydockfinder#70]

**Comment by mydockfinder** [comment]
可以&nbsp; 但是任务管理器或者其他管理员模式运行的程序就没有最小化动画了，而且管理员模式的程序图标也不会在dock上面显示，因为权限不够




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月16日(星期三) 中午11:58
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder] Is it possible to minimize windows to the dock without the UAC prompt: its a little disturbing while working (#70)

**Comment by teddtastic** [comment]
oh okay
