### ISSUE TITLE
資料夾菜單模式下的排序方式

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#700]
請問一下，菜單模式下的資料夾排序，如果設定目錄優先後，目前狀況 只有資料夾跟文檔分開而已
是否還是可以按照字母排序呢? 

希望是 如下優先度排序
1. [a->z, A->Z] (資料夾) 
2. [a->z, A->Z] (一般文檔)

![image](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/b9990b48-8461-4d91-bae6-6bdbf5c53cbf)

![image](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/82a798f2-de7d-4700-bea7-8a375b411e57)

**Comment by mydockfinder** [comment]
好的 是我大意了回来加上




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月14日(星期五) 下午2:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 資料夾菜單模式下的排序方式 (Issue #700)














 
請問一下，菜單模式下的資料夾排序，如果設定目錄優先後，目前狀況 只有資料夾跟文檔分開而已
 是否還是可以按照字母排序呢?
 
希望是 如下優先度排序
  
[a-&gt;z, A-&gt;Z] (資料夾)
 
[a-&gt;z, A-&gt;Z] (一般文檔)
  
image.png (view on web)
 
image.png (view on web)

**Comment by linitfor** [comment]
大大休假還是出差去了嗎? 大概什麼時候回來呢? 有計劃什麼時候更新?

**Comment by mydockfinder** [comment]
最近工作有点忙，我争取这周更新一下
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月9日(星期二) 上午9:21
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 資料夾菜單模式下的排序方式 (Issue #700)














 
大大休假還是出差去了嗎? 大概什麼時候回來呢? 有計劃什麼時候更新?

**Comment by linitfor** [comment]
工作辛苦啦~ 按照大大的步調就好，不急現在用的還蠻順的。

**Comment by linitfor** [comment]
哇~~ 大大忘了幫忙更新資料夾排序這個bug 了! 再麻煩大大後續幫忙排入這個更新喔~~ 感謝

**Comment by linitfor** [comment]
看到大大的更新囉~ 感謝百忙之中，協助修改~ 感謝
