### ISSUE TITLE
CS1.6和HL1之类游戏全屏显示错误

### ISSUE THREAD

**Issue by MreAtKC** [mydockfinder/mydockfinder#703]
![cs](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/91823010/d5ca4fa1-805a-497d-858b-e1295676423f)
![hl](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/91823010/a2f92c58-b626-450a-bed1-6174d94f4862)
如图所见
关闭Mydockfinder后恢复正常

**Comment by mydockfinder** [comment]
emmmmmm&nbsp; 这俩图都是打开了myfinder啊
不过我大概猜了一下是哪里的问题，如果打开了mydock，dock上的游戏图标右键-选项-不再显示此程序最小化动画
然后打开偏好设置-窗口动画，显示和关闭动画全部添加游戏的排除项，然后重启mydockfinder和游戏应该就可以了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月30日(星期天) 晚上11:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] CS1.6和HL1之类游戏全屏显示错误 (Issue #703)














 
cs.png (view on web)
 hl.png (view on web)
 如图所见
 关闭Mydockfinder后恢复正常

**Comment by MreAtKC** [comment]
> emmmmmm&nbsp; 这俩图都是打开了myfinder啊 不过我大概猜了一下是哪里的问题，如果打开了mydock，dock上的游戏图标右键-选项-不再显示此程序最小化动画 然后打开偏好设置-窗口动画，显示和关闭动画全部添加游戏的排除项，然后重启mydockfinder和游戏应该就可以了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年6月30日(星期天) 晚上11:38 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [mydockfinder/mydockfinder-for-Win10-Win11] CS1.6和HL1之类游戏全屏显示错误 (Issue #703) cs.png (view on web) hl.png (view on web) 如图所见 关闭Mydockfinder后恢复正常 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

是的，感谢你的回复，这下我可以愉快的玩cs了！q(≧▽≦q)
