### ISSUE TITLE
Cannot fiind MyDockFinder settings when the Dock is not enabled

### ISSUE THREAD

**Issue by jojimow** [mydockfinder/mydockfinder#705]
Hi
after installing MDF, I have diabled the dock. Now I cannot fiind MyDockFinder settings. Is there a way to access it from MyFinder or elsewhere?
thanks

**Comment by jojimow** [comment]
Perhaps add a shortcut to MDF settings on the Finder bar.

**Comment by linitfor** [comment]
You can find the mydockfinder setting on the myfinder menu. 

![image](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/58168507/9c3ff2de-f8c1-4128-82f0-30694147e4e8)

**Comment by jojimow** [comment]
Great! thank you.
