### ISSUE TITLE
一個小建議 : Preview 內視窗 改圓角

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#713]
一個沒有很重要的小建議 XDD
Preview 視窗 內框 有可能弄成圓角嗎?
Win11 視窗都是圓角，但Preview 內視窗是直角 

![image](https://github.com/user-attachments/assets/8f59d7bc-1388-4d9a-8b81-08f9538ec1d8)

**Comment by mydockfinder** [comment]
因为这个预览用的是系统接口的窗口预览只能是直角而且不能控制，要是用合成的方法渲染窗口预览倒是可以圆角，但是个别程序窗口会有显示异常的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月31日(星期三) 中午11:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 一個小建議 : Preview 內視窗 改圓角 (Issue #713)














 
一個沒有很重要的小建議 XDD
 Preview 視窗 內框 有可能弄成圓角嗎?
 Win11 視窗都是圓角，但Preview 內視窗是直角
 
image.png (view on web)

**Comment by linitfor** [comment]
好的 了解
