### ISSUE TITLE
[1.9.9.9][issue] 行事曆按鈕失效

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#715]
昨天更新完最新版之後，如圖顯示，紅色框框的行事曆按鈕失效

![image](https://github.com/user-attachments/assets/3879f448-c4fb-4671-9d89-b7e96f433f96)

**Comment by mydockfinder** [comment]
嗯 新版的bug，今晚会更新修复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月6日(星期二) 凌晨5:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] [1.9.9.9][issue] 行事曆按鈕失效 (Issue #715)














 
昨天更新完最新版之後，如圖顯示，紅色框框的行事曆按鈕失效
 
image.png (view on web)

**Comment by linitfor** [comment]
更新已經修復 感謝
