### ISSUE TITLE
[1.9.9.9][issue] Mydocker 上的預覽視窗，無法預覽正在播放的影片

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#717]
Mydocker 上的預覽視窗，只有在單一網頁時，才可以正常撥放影片
這個跟之前的設計好像不太一樣

但左側台前調度預覽，可以正常撥放正在播放的影片
![image](https://github.com/user-attachments/assets/ec12e572-3326-4407-8f61-1cc630123765)

另外，滑鼠懸停那個選項好像被Fix 住了嗎? 看起來是個bug ... XD
![image](https://github.com/user-attachments/assets/51d5b9f2-3704-4817-ab10-b57bc93b0574)

**Comment by mydockfinder** [comment]
鼠标悬停那个应该是bug了，我看一下代码
dock上如果是多标签的预览是静态的，就像alt+tab一样的多标签页预览，台前调度是单个窗口的预览，标签页是浏览器缓存的一个静态图像

**Comment by mydockfinder** [comment]
如果想动态预览可以关闭alt+tab的多标签页预览，在系统设置-多任务
![image](https://github.com/user-attachments/assets/87294be2-1ea2-4bb6-8f9a-162d93f86529)

**Comment by linitfor** [comment]
原來如此 懂~~ 感謝

**Comment by mydockfinder** [comment]
不客气
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月8日(星期四) 上午10:57
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] [1.9.9.9][issue] Mydocker 上的預覽視窗，無法預覽正在播放的影片 (Issue #717)














 
原來如此 懂~~ 感謝
