### ISSUE TITLE
widget 點子

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#720]
有一個想法，但不知道好不好弄，

windows widget 在工作列，會有一個提醒功能
![image](https://github.com/user-attachments/assets/9f75fd2f-b117-42af-8a17-39ba694803ac)
這個不知道有沒有辦法
當出現這種快訊的時候
在mydocker or finder 上對應顯示相關資訊
然後點選那個資訊按鈕後
可以開啟這個windows 11 的wiget
![image](https://github.com/user-attachments/assets/f59da068-bc07-4cdb-a2c2-d5469d4f68b0)

**Comment by mydockfinder** [comment]
理论上来说是可以，但是我不会，都不知道怎么搜索相关的资料



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月13日(星期二) 上午10:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] widget 點子 (Issue #720)














 
有一個想法，但不知道好不好弄，
 
windows widget 在工作列，會有一個提醒功能
 image.png (view on web)
 這個不知道有沒有辦法
 當出現這種快訊的時候
 在mydocker or finder 上對應顯示相關資訊
 然後點選那個資訊按鈕後
 可以開啟這個windows 11 的wiget
 image.png (view on web)

**Comment by linitfor** [comment]
沒關係 只是剛剛踫出個想法 XD
