### ISSUE TITLE
台前調度 + 虛擬桌面 使用 組合視窗 的應用問題

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#728]
另外測試了一個比較複雜的使用方式，
台前調度 + 虛擬桌面，使用上也遇到一個問題。
當我開啟台前調度下
在虛擬桌面1 使用組合視窗(ex. word+ excel)
切換到虛擬桌面2 查詢一個文檔
然後在切回虛擬桌面1 後，
原本的組合視窗 word + excel ，看起來會被台前調度拆掉
word or excel 其中一個會被丟回左側視窗。

**Comment by mydockfinder** [comment]
目前是为了节省GPU的占用，每次切换虚拟桌面都会重建台前调度，其实最完美的办法就是每个虚拟桌面都是独立的这样就没事了，但是这样会加大GPU的占用



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月22日(星期四) 下午4:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 台前調度 + 虛擬桌面 使用 組合視窗 的應用問題 (Issue #728)














 
另外測試了一個比較複雜的使用方式，
 台前調度 + 虛擬桌面，使用上也遇到一個問題。
 當我開啟台前調度下
 在虛擬桌面1 使用組合視窗(ex. word+ excel)
 切換到虛擬桌面2 查詢一個文檔
 然後在切回虛擬桌面1 後，
 原本的組合視窗 word + excel ，看起來會被台前調度拆掉
 word or excel 其中一個會被丟回左側視窗。

**Comment by linitfor** [comment]
OK 能理解，這個用法比較多餘。
大大的設計想法是對的，先考慮使用效能體驗優先，
我只是突發奇想而已，當開啟台前調度就可以取代虛擬多桌面的用法。

我今天只是剛好發現windows 虛擬桌面有做一些調整，
似乎有調整了切換虛擬桌面的流暢度
在不開啟台前調度時，我去調整筆電觸碰板快捷手勢後
可以蠻像Mac 切換不同虛擬桌面一樣

**Comment by mydockfinder** [comment]
那微软应该是加入了触摸的优化，加了触摸的切换虚拟桌面动画




№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月22日(星期四) 下午4:50
***@***.***&gt;;
抄送:&nbsp;"№じ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [mydockfinder/mydockfinder-for-Win10-Win11] 台前調度 + 虛擬桌面 使用 組合視窗 的應用問題 (Issue #728)





 
OK 能理解，這個用法比較多餘。
 大大的設計想法是對的，先考慮使用效能體驗優先，
 我只是突發奇想而已，當開啟台前調度就可以取代虛擬多桌面的用法。
 
我今天只是剛好發現windows 虛擬桌面有做一些調整，
 似乎有調整了切換虛擬桌面的流暢度
 在不開啟台前調度時，我去調整筆電觸碰板快捷手勢後
 可以蠻像Mac 切換不同虛擬桌面一樣
