### ISSUE TITLE
是否可以考虑开源

### ISSUE THREAD

**Issue by PMExtra** [mydockfinder/mydockfinder#73]
如题，目前没看到 mydockfinder 有任何商业化的计划，而且考虑到这个项目本身的性质，商业化也可能迎来法律风险。
即使未来要考虑商业化，商业化也不和开源完全对立，我们可以看到很多知名的开源商业化项目，例如 [Synergy](https://github.com/symless/synergy-core), [GitLab](https://gitlab.com/gitlab-org/gitlab) 等。
因此恳请开源，可以让更多人参与和完善这个项目。

**Comment by mydockfinder** [comment]
目前不考虑开源，也不打算商业化，这属于侵犯苹果的专利了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月16日(星期三) 下午2:54
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder] 是否可以考虑开源 (#73)





 
如题，目前没看到 mydockfinder 有任何商业化的计划，而且考虑到这个项目本身的性质，商业化也可能迎来法律风险。
 即使未来要考虑商业化，商业化也不和开源完全对立，我们可以看到很多知名的开源商业化项目，例如 Synergy, GitLab 等。
 因此恳请开源，可以让更多人参与和完善这个项目。

**Comment by PMExtra** [comment]
嗯，是否开源是您的权力，非常感谢您制作了这个软件并且无偿开放给大家使用。但是冒昧多嘴问一句，您制作这款软件的初衷是什么？既然没有商业化的计划，那么为什么不能让更多的人参与贡献呢？

**Comment by mydockfinder** [comment]
国企上班闲着没事干，之前有个mac但是那时候打游戏mac玩不了，就又买了一个Windows，但是喜欢mac的界面Windows太难看了，网上找了半天每一个和我心意的然后自己开始做了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月16日(星期三) 下午3:18
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] 是否可以考虑开源 (#73)





 
嗯，是否开源是您的权力，非常感谢您制作了这个软件并且无偿开放给大家使用。但是冒昧多嘴问一句，您制作这款软件的初衷是什么？既然没有商业化的计划，那么为什么不能让更多的人参与贡献呢？

**Comment by PMExtra** [comment]
嗯，我是 mac 和 win 双电脑用户，双主机双屏幕，用 Synergy 共享一套键鼠。因为两个系统的体验差异对跨屏操作产生了割裂感，因此我一直致力于统一两个操作系统的使用体验，为此搞出了一个 mackeyboard 的 AutoHotKey 脚本（可以在windows上使用mac的快捷键，先把 Alt 和 Win 对调，然后使用例如 Win+C 复制 Win+V 粘贴，Win+` 可以在同一个程序内切换不同窗口等等，详见 https://gist.github.com/PMExtra/4462a90bf2bc0f4afa2d0339ddf301d1

昨天发现了 mydockfinder ，之前也体验过各种把 Win 模拟成 mac UI 的产品，说实话体验都差得远了。
mydockfinder 是我目前见过的完成度最高，体验最接近 mac 的产品。但还是有一些小瑕疵，这也是我希望参与到这个项目之中的原因。

**Comment by mydockfinder** [comment]
其实快捷键什么的&nbsp; mac偏好设置键盘里面可以修改修饰按键的，那样就换过来了不用其他软件的
很感谢，不过我并不是编程科班出身写的代码基本也就我自己能看懂，有时自己都不知道那个变量是干啥的，这也是不开源的原因之一，当然网上喷子太多不开源喷开源也喷而且又多了一个喷的点




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月16日(星期三) 下午3:48
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] 是否可以考虑开源 (#73)





 
嗯，我是 mac 和 win 双电脑用户，双主机双屏幕，用 Synergy 共享一套键鼠。因为两个系统的体验差异对跨屏操作产生了割裂感，因此我一直致力于统一两个操作系统的使用体验，为此搞出了一个 mackeyboard 的 AutoHotKey 脚本（可以在windows上使用mac的快捷键，先把 Alt 和 Win 对调，然后使用例如 Win+C 复制 Win+V 粘贴，Win+` 可以在同一个程序内切换不同窗口等等，详见 https://gist.github.com/PMExtra/4462a90bf2bc0f4afa2d0339ddf301d1
 
昨天发现了 mydockfinder ，之前也体验过各种把 Win 模拟成 mac UI 的产品，说实话体验都差得远了。
 mydockfinder 是我目前见过的完成度最高，体验最接近 mac 的产品。但还是有一些小瑕疵，这也是我希望参与到这个项目之中的原因。
 
&mdash;

**Comment by PMExtra** [comment]
嗯，我是比较习惯mac的快捷键，而且觉得mac大多数快捷键在操作上比win人性化，更加顺手。因此更希望让win模拟mac行为，而非mac模拟win。
然后喷子什么的，我觉得无视就好，他们喷他们的，我们根本不必理会他们，甚至用户都会帮忙喷回去。
我觉得代码质量或者代码风格之类，不足为虑，相反，这更是开源进行学习交流的机会。
比如我就自认为我还挺擅长于代码质量和架构的管理，但是在一些技术细节，或者说技术深度上有所不足。
一旦开源，像我这样的人可以从你的代码中学到一些具体的技术实现，而你也可以从别人的贡献中借鉴一些代码风格、架构上的实践。

当然，说了这么多，仅仅是一种期待和劝解，开不开源是您的权力，您甚至不必给出任何理由。很感谢您的分享和交流。

**Comment by mydockfinder** [comment]
谢谢，操作习惯统一是好的方向，主要是有的人并没有用过mac，就像音量提示我是被迫放到屏幕中间，mac是在dock上面的，放下每周都有人会说提示没居中，所以一些操作习惯我也是不得不妥协，其实技术我也没啥，只不过想法和其他人不一样，我更喜欢自己研究结构和算法，除非有真的很好优化的很不错的我才会用，要不然我宁可自己研究，至于源码里面有一些未公开的API还有一些系统底层的东西我不太想公开，要是让某些毒瘤软件用了可能后果不堪设想，当然了编译dll也是没啥用的，逆向分分钟就破了，只有全部在一起的代码他逆向才不好找




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月16日(星期三) 下午4:42
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] 是否可以考虑开源 (#73)





 
嗯，我是比较习惯mac的快捷键，而且觉得mac大多数快捷键在操作上比win人性化，更加顺手。因此更希望让win模拟mac行为，而非mac模拟win。
 然后喷子什么的，我觉得无视就好，他们喷他们的，我们根本不必理会他们，甚至用户都会帮忙喷回去。
 我觉得代码质量或者代码风格之类，不足为虑，相反，这更是开源进行学习交流的机会。
 比如我就自认为我还挺擅长于代码质量和架构的管理，但是在一些技术细节，或者说技术深度上有所不足。
 一旦开源，像我这样的人可以从你的代码中学到一些具体的技术实现，而你也可以从别人的贡献中借鉴一些代码风格、架构上的实践。
 
当然，说了这么多，仅仅是一种期待和劝解，开不开源是您的权力，您甚至不必给出任何理由。很感谢您的分享和交流。
 
&mdash;

**Comment by PMExtra** [comment]
我也注意到了音量提示的位置不对，我还以为是 big sur 把它放中间了…… (因为我一直没升 big sur
嗯，既然您坚定不开源，那我先关闭这个issue了。我之后会反馈更多使用中遇到的问题和建议，再次感谢您贡献了一个这么好的项目，也感谢您的耐心解答。

**Comment by mydockfinder** [comment]
好的&nbsp; 很感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月16日(星期三) 下午5:13
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] 是否可以考虑开源 (#73)





 
我也注意到了音量提示的位置不对，我还以为是 big sur 把它放中间了…… (因为我一直没升 big sur
 嗯，既然您坚定不开源，那我先关闭这个issue了。我之后会反馈更多使用中遇到的问题和建议，再次感谢您贡献了一个这么好的项目，也感谢您的耐心解答。
 
&mdash;
