### ISSUE TITLE
台前调度 怎么添加排除的程序啊

### ISSUE THREAD

**Issue by stevenhobs** [mydockfinder/mydockfinder#732]
点击 那个排除的按钮里面就显示无禁止程序。求好心人指引一下

**Comment by stevenhobs** [comment]
我知道了，右键这个窗口，可以设置不再关闭

**Comment by DSDHYS** [comment]
> 我知道了，右键这个窗口，可以设置不再关闭

很有用！
就是在台前调度显示的界面，右键不需要的程序
