### ISSUE TITLE
Make apps visible on all desktops

### ISSUE THREAD

**Issue by elkhaligy** [mydockfinder/mydockfinder#739]
There's no option to make all apps available on all desktops, this is the behavior on the original windows taskbar, but on mydockfinder it only applies to instant windows and not app icons, which makes this inconsistent behavior where apps on desktop 1 appears for a second and then disappears again.

https://github.com/user-attachments/assets/4a94689f-e4b5-4190-bc26-30c7e3f6d9e2

**Comment by mydockfinder** [comment]
Fix in the next release




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月14日(星期六) 晚上11:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] Make apps visible on all desktops (Issue #739)














 
There's no option to make all apps available on all desktops, this is the behavior on the original windows taskbar, but on mydockfinder it only applies to instant windows and not app icons, which makes this inconsistent behavior where apps on desktop 1 appears for a second and then disappears again.
 
https://github.com/user-attachments/assets/4a94689f-e4b5-4190-bc26-30c7e3f6d9e2

**Comment by elkhaligy** [comment]
Thank you :)
