### ISSUE TITLE
[1.9.9.9][issue] 莫名出現的幽靈dock icon

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#744]
更新到昨天更新的最新版，剛在使用發現一個靈異狀況
 
![image](https://github.com/user-attachments/assets/2dc88a30-8c34-49f6-a4b4-b4569caf3401)

點擊這個app icon，跳出的是edge 網頁
網頁內容如下:
![image](https://github.com/user-attachments/assets/539ae324-37b0-4cbb-bc73-4d858c529c73)

**Comment by mydockfinder** [comment]
这个图标以前是什么




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月18日(星期三) 下午3:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] [1.9.9.9][issue] 莫名出現的幽靈dock icon (Issue #744)














 
更新到昨天更新的最新版，剛在使用發現一個靈異狀況
 
image.png (view on web)
 
點擊這個app icon，跳出的是edge 網頁
 網頁內容如下:
 image.png (view on web)

**Comment by linitfor** [comment]
沒有耶 憑空出現的
你看有兩條分隔線，分隔線中間是新開且未保留在dock 的 app 。

**Comment by linitfor** [comment]
重新啟動mydockfinder 他居然自己改設定保留在mydocker 上
我把它移除掉，重新啟動就沒再出現了。

**Comment by linitfor** [comment]
阿 我剛try 出來了.... 
不小心把網頁上的圖，拖曳到mydock 上
這個狀況就會出現了 
sorry... 我的錯＠＠

**Comment by mydockfinder** [comment]
emmmm&nbsp; 还有这种操作&nbsp; 我试一下




№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月18日(星期三) 晚上7:04
***@***.***&gt;;
抄送:&nbsp;"№じ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [mydockfinder/mydockfinder-for-Win10-Win11] [1.9.9.9][issue] 莫名出現的幽靈dock icon (Issue #744)





 
阿 我剛try 出來了....
 不小心把網頁上的圖，拖曳到mydock 上
 這個狀況就會出現了
 sorry... 我的錯＠＠
