### ISSUE TITLE
窗口最大化沉浸模式失效

### ISSUE THREAD

**Issue by spring-believer** [mydockfinder/mydockfinder#745]
新版本，窗口最大化沉浸模式失效。
切换应用时，沉浸模式会闪烁生效一下，然后失效。
Windows版本：22631.4169

**Comment by spring-believer** [comment]
作者是没看到这个议题，还是看到不想搭理啊

**Comment by linitfor** [comment]
他可能工作太忙吧 体谅一下呗

**Comment by spring-believer** [comment]
> 他可能工作太忙吧 体谅一下呗

我太理解了，朋友，但是他连后边的议题都回复了。我明白在开源上，这不是必须的。但咱们也都是在steam上花了钱了，况且我也没说啥不礼貌的话

**Comment by mydockfinder** [comment]
> > 他可能工作太忙吧 体谅一下呗
> 
> 我太理解了，朋友，但是他连后边的议题都回复了。我明白在开源上，这不是必须的。但咱们也都是在steam上花了钱了，况且我也没说啥不礼貌的话

不好意思，应该是看到了，有可能要回复的时候被什么事给打断了，然后回来就给忘了
是win11的24H2吗

**Comment by spring-believer** [comment]
> > > 他可能工作太忙吧 体谅一下呗
> > 
> > 
> > 我太理解了，朋友，但是他连后边的议题都回复了。我明白在开源上，这不是必须的。但咱们也都是在steam上花了钱了，况且我也没说啥不礼貌的话
> 
> 不好意思，应该是看到了，有可能要回复的时候被什么事给打断了，然后回来就给忘了 是win11的24H2吗

我昨天测试了一下，和Windows版本没关系，是mydock开启【窗口边界防止遮挡dock】引起的。
感觉像是mydock防边界遮挡，将dock贴在了桌面上，然后Finder监控的是dock那一块的UI，导致的finder沉浸模式失效。
触发条件：finder置于屏幕左边侧；开启【窗口边界防止遮挡dock】；
就是我昨天发起的新的议题：
https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/issues/747
很好的产品，付费的同时也愿意为产品的提升做出一些贡献

**Comment by mydockfinder** [comment]
我测试了一下没有问题，能来个视频吗

**Comment by mydockfinder** [comment]
我测试了一下没有问题，能来个视频吗
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月12日(星期六) 上午9:38
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 窗口最大化沉浸模式失效 (Issue #745)














    
他可能工作太忙吧 体谅一下呗
  
我太理解了，朋友，但是他连后边的议题都回复了。我明白在开源上，这不是必须的。但咱们也都是在steam上花了钱了，况且我也没说啥不礼貌的话
  
不好意思，应该是看到了，有可能要回复的时候被什么事给打断了，然后回来就给忘了 是win11的24H2吗
  
我昨天测试了一下，和Windows版本没关系，是mydock开启【窗口边界防止遮挡dock】引起的。
 感觉像是mydock防边界遮挡，将dock贴在了桌面上，然后Finder监控的是dock那一块的UI，导致的finder沉浸模式失效
 就是我昨天发起的新的议题：
 #747
 很好的产品，付费的同时也愿意为产品的提升做出一些贡献

**Comment by spring-believer** [comment]
> 我测试了一下没有问题，能来个视频吗

视频文件如下，dock置于屏幕左边侧，我猜测是mydock防边界遮挡，将dock贴在了桌面上，然后Finder监控的是dock那一块的UI，导致的finder沉浸模式失效。

[Uploading 7e5095d6-cb7c-4499-9a2f-0c79efd12606.webm…]()

**Comment by spring-believer** [comment]
> 我测试了一下没有问题，能来个视频吗

视频文件如下，dock置于屏幕左边侧，我猜测是mydock防边界遮挡，将dock贴在了桌面上，然后Finder监控的是dock那一块的UI，导致的finder沉浸模式失效。

[7e5095d6-cb7c-4499-9a2f-0c79efd12606.webm](https://github.com/user-attachments/assets/f55c67f7-4ac5-46fa-933e-8c35b45cc563)

**Comment by mydockfinder** [comment]
卧槽 原来是放屏幕两边，难怪我没测出来，我修一下
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月12日(星期六) 中午11:32
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 窗口最大化沉浸模式失效 (Issue #745)














  
我测试了一下没有问题，能来个视频吗
  
视频文件如下，dock置于屏幕左边侧，我猜测是mydock防边界遮挡，将dock贴在了桌面上，然后Finder监控的是dock那一块的UI，导致的finder沉浸模式失效。
 
7e5095d6-cb7c-4499-9a2f-0c79efd12606.webm

**Comment by spring-believer** [comment]
> 卧槽 原来是放屏幕两边，难怪我没测出来，我修一下 &nbsp; №じ&nbsp;尐乄鈊~→☆ ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年10月12日(星期六) 中午11:32 收件人: ***@***.***&gt;; 抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 窗口最大化沉浸模式失效 (Issue #745) 我测试了一下没有问题，能来个视频吗 视频文件如下，dock置于屏幕左边侧，我猜测是mydock防边界遮挡，将dock贴在了桌面上，然后Finder监控的是dock那一块的UI，导致的finder沉浸模式失效。 7e5095d6-cb7c-4499-9a2f-0c79efd12606.webm — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

辛苦了

**Comment by mydockfinder** [comment]
修好了&nbsp; 下个版本更新就好了，不过可能得一两周了这些日子有点忙，有一种没有功劳也有苦劳的忙



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月12日(星期六) 中午11:37
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 窗口最大化沉浸模式失效 (Issue #745)





  
卧槽 原来是放屏幕两边，难怪我没测出来，我修一下   №じ 尐乄鈊~→☆ @.***  
 …
 ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2024年10月12日(星期六) 中午11:32 收件人: @.&gt;; 抄送: "№じ @.&gt;; @.&gt;; 主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 窗口最大化沉浸模式失效 (Issue #745) 我测试了一下没有问题，能来个视频吗 视频文件如下，dock置于屏幕左边侧，我猜测是mydock防边界遮挡，将dock贴在了桌面上，然后Finder监控的是dock那一块的UI，导致的finder沉浸模式失效。 7e5095d6-cb7c-4499-9a2f-0c79efd12606.webm — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
辛苦了
 
&mdash;

**Comment by spring-believer** [comment]
> 修好了&nbsp; 下个版本更新就好了，不过可能得一两周了这些日子有点忙，有一种没有功劳也有苦劳的忙
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年10月12日(星期六) 中午11:37 收件人: ***@***.***&gt;; 抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 窗口最大化沉浸模式失效 (Issue #745) 卧槽 原来是放屏幕两边，难怪我没测出来，我修一下   №じ 尐乄鈊~→☆ @.***   … ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2024年10月12日(星期六) 中午11:32 收件人: @.&gt;; 抄送: "№じ @.&gt;; @.&gt;; 主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 窗口最大化沉浸模式失效 (Issue #745) 我测试了一下没有问题，能来个视频吗 视频文件如下，dock置于屏幕左边侧，我猜测是mydock防边界遮挡，将dock贴在了桌面上，然后Finder监控的是dock那一块的UI，导致的finder沉浸模式失效。 7e5095d6-cb7c-4499-9a2f-0c79efd12606.webm — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; 辛苦了 &mdash; Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

其实我也是做程序的，能理解。
