### ISSUE TITLE
是否可以添加从 Windows 开始菜单的应用列表中导入到启动台的功能

### ISSUE THREAD

**Issue by Oracynx** [mydockfinder/mydockfinder#749]
应用太多了，一个一个导入很麻烦，现在我大部分时候还是 Win + S 搜索打开
可不可以支持扫描 `C:\ProgramData\Microsoft\Windows\Start Menu\Programs` 路径下的快捷方式，全部导入/勾选导入

**Comment by mydockfinder** [comment]
有没有一种可能，偏好设置里有这个选项



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月13日(星期天) 中午11:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 是否可以添加从 Windows 开始菜单的应用列表中导入到启动台的功能 (Issue #749)














 
应用太多了，一个一个导入很麻烦，现在我大部分时候还是 Win + S 搜索打开
 可不可以支持扫描 C:\ProgramData\Microsoft\Windows\Start Menu\Programs 路径下的快捷方式，全部导入/勾选导入

**Comment by Oracynx** [comment]
谢谢

**Comment by Oracynx** [comment]
![image](https://github.com/user-attachments/assets/20710f7f-a60c-47e0-a07f-f9a89358d4bb)
选了之后图标全部成了这样子，可能是什么原因呢

**Comment by mydockfinder** [comment]
偏好设置-关于里面两个选项，一个是清除启动台图标缓存，还一个是清除系统图标缓存，这两个都点一下，然后重启电脑
