### ISSUE TITLE
能否在全屏游戏/应用时设置也可以呼出 Dock

### ISSUE THREAD

**Issue by Oracynx** [mydockfinder/mydockfinder#751]
能否在全屏游戏/应用时设置也可以呼出 Dock
貌似没有找到，要是还是有这个功能的话当我傻了

**Comment by mydockfinder** [comment]
按WIN，显示开始菜单就一起出来了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月13日(星期天) 晚上7:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 能否在全屏游戏/应用时设置也可以呼出 Dock (Issue #751)














 
能否在全屏游戏/应用时设置也可以呼出 Dock
 貌似没有找到，要是还是有这个功能的话当我傻了

**Comment by Oracynx** [comment]
但是如果有窗口全屏，但目前的焦点在非全屏窗口，Dock 和 Finder 也不会显示

**Comment by Oracynx** [comment]
或者说，基于目前的呼出 Dock 快捷键进行改进，支持使用 Ctrl + Alt + xxx 的多控制键快捷键，要不然只能设置一个键很容易冲突

**Comment by mydockfinder** [comment]
确实，我回来改一下



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月14日(星期一) 下午2:53
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 能否在全屏游戏/应用时设置也可以呼出 Dock (Issue #751)





 
或者说，基于目前的呼出 Dock 快捷键进行改进，支持使用 Ctrl + Alt + xxx 的多控制键快捷键，要不然只能设置一个键很容易冲突
 
&mdash;
