### ISSUE TITLE
左上角的图标如何自定义

### ISSUE THREAD

**Issue by Oracynx** [mydockfinder/mydockfinder#754]
在偏好设置中，找到了这个选项
![image](https://github.com/user-attachments/assets/ca5a9ea2-d9d8-4f45-8977-cd14ee366a75)
但是使用 1 位位图（只有黑白的图）的 png 和 ico 格式均会变成一个黑块
![image](https://github.com/user-attachments/assets/f5c4f1bc-e8b9-426c-b4b3-340e244ece68)
是对图片的尺寸有要求吗，还是说有其他的要求
图片：[ico.zip](https://github.com/user-attachments/files/17430418/ico.zip)

**Comment by Oracynx** [comment]
图片是 64x64 的

**Comment by mydockfinder** [comment]
确实有点问题，我适配一下

**Comment by mydockfinder** [comment]
emmmmm  这个图没有透明的地方所以就会全黑了，logo的原理是整个变色，不要的地方得是透明才可以

**Comment by Oracynx** [comment]
所以说他要的是透明度的图片，像 png 的一样
然后是有颜色就是黑的，透明的就是镂空的地方？

**Comment by mydockfinder** [comment]
是的，不管原图什么颜色的，全变黑，镂空就要透明的&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月18日(星期五) 下午4:22
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 左上角的图标如何自定义 (Issue #754)














 
所以说他要的是透明度的图片，像 png 的一样
 然后是有颜色就是黑的，透明的就是镂空的地方？

**Comment by Oracynx** [comment]
好了，谢谢
