### ISSUE TITLE
在前台调度中的时候的一些问题

### ISSUE THREAD

**Issue by Oracynx** [mydockfinder/mydockfinder#758]
- Dock 在有些时候隐藏比窗口动画慢，被遮挡了
- 在选中一个最大化的窗口时当前窗口的动画有时会慢于其他未被选中的动画

- 左侧的调度区有时候的动画没有完全显示

依次复现视频：

https://github.com/user-attachments/assets/69aecc69-6d50-4f8e-ae2e-cb621d8adcb3

**Comment by mydockfinder** [comment]
显卡设置里面有个限制后台程序帧数关闭了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月22日(星期二) 中午1:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 在前台调度中的时候的一些问题 (Issue #758)














  
 
Dock 在有些时候隐藏比窗口动画慢，被遮挡了
 
 
 
在选中一个最大化的窗口时当前窗口的动画有时会慢于其他未被选中的动画
 
 
 
左侧的调度区有时候的动画没有完全显示
 
  
依次复现视频：
 
https://github.com/user-attachments/assets/69aecc69-6d50-4f8e-ae2e-cb621d8adcb3
