### ISSUE TITLE
No option to remove icon from dock if the icon is a Steam shortcut

### ISSUE THREAD

**Issue by sabretou** [mydockfinder/mydockfinder#761]
If I drag a regular shortcut to the Dock, I can see a menu that allows me to remove the icon from the dock.

![Screenshot 2024-10-25 140424](https://github.com/user-attachments/assets/2233a4ef-4d4e-4166-b2a0-3b5f8e9ec184)

However, if the shortcut is a URL (such as a Steam shortcut), this menu is not present.

![Screenshot 2024-10-25 140519](https://github.com/user-attachments/assets/8cbeed8b-3196-4db2-8257-1b571dbdf4e7)

In this case, the only way to remove the icon from the dock is to disable "Lock icon dragging" and drag the icon off the dock. This is both unintuitive and non-uniform. It is also cumbersome to do so for each icon that needs to be removed.

**Comment by mydockfinder** [comment]
When the icon is locked, the right-click menu does not display the option to remove




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月25日(星期五) 下午4:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] No option to remove icon from dock if the icon is a Steam shortcut (Issue #761)














 
If I drag a regular shortcut to the Dock, I can see a menu that allows me to remove the icon from the dock.
 
Screenshot.2024-10-25.140424.png (view on web)
 
However, if the shortcut is a URL (such as a Steam shortcut), this menu is not present.
 
Screenshot.2024-10-25.140519.png (view on web)
 
In this case, the only way to remove the icon from the dock is to disable "Lock icon dragging" and drag the icon off the dock. This is both unintuitive and non-uniform. It is also cumbersome to do so for each icon that needs to be removed.

**Comment by sabretou** [comment]
I see. How do I unlock the icon, then? As you can see in the screenshot I've included, "Lock icon dragging" is turned off already.

**Comment by mydockfinder** [comment]
Okay, I'll take a look at the code again, it's possible that it's not rigorous
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月25日(星期五) 下午4:46
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] No option to remove icon from dock if the icon is a Steam shortcut (Issue #761)














 
I see. How do I unlock the icon, then? As you can see in the screenshot I've included, "Lock icon dragging" is turned off already.

**Comment by dluccz** [comment]
I encountered the same problem. The solution was to drag the game icon out of the dock. It disappeared.

**Comment by mydockfinder** [comment]
Fixed in the next version


&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月28日(星期四) 上午10:47
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] No option to remove icon from dock if the icon is a Steam shortcut (Issue #761)














 
I encountered the same problem. The solution was to drag the game icon out of the dock. It disappeared.
