### ISSUE TITLE
[issue] 台前調度功能誤抓程式

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#765]
20241027 的版本更新會出現以下問題

開機自動啟動mydockfinder

台前調度好像會誤抓不確定是什麼程式
看起來像是explorer.exe
點擊該程式 
只有桌面閃了一下
沒有開啟其他任何程式

但重新啟動mydockfinder 這個誤抓狀況會消失
![image](https://github.com/user-attachments/assets/126cdc66-951f-4cbf-85b3-fef4d45a9bd4)

**Comment by mydockfinder** [comment]
emmmm  可能就是桌面了，我加个过滤

**Comment by linitfor** [comment]
更新20241029版本已解決
