### ISSUE TITLE
[Suggestion] 台前調度/專注模式 快速切換模式的功能按鈕

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#766]
大大，有個小建議，新版以下這個快速切換的功能，
可不可以把  alt + 中鍵改成右鍵
換成直接但單純只按右鍵 
感覺更直覺一點

一個小建議而已，不好改就算了。

![image](https://github.com/user-attachments/assets/b2ffc49d-47e1-43e7-ba16-3f615491d98e)

**Comment by mydockfinder** [comment]
emmmmm&nbsp; &nbsp;可能是翻译的问题，是alt+鼠标左键，或者鼠标中键直接点击，鼠标中键不用按alt直接点就可以




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月29日(星期二) 中午1:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] [Suggestion] 台前調度/專注模式 快速切換模式的功能按鈕 (Issue #766)














 
大大，有個小建議，新版以下這個快速切換的功能，
 可不可以把  alt + 中鍵改成右鍵
 換成直接但單純只按右鍵
 感覺更直覺一點
 
一個小建議而已，不好改就算了。
 
image.png (view on web)

**Comment by linitfor** [comment]
我寫錯了
因為筆電觸碰板要使用中鍵比要困難
我是用軟體去模擬中鍵
但這個模擬中鍵功能
好像在你這個功能是失效的

**Comment by mydockfinder** [comment]
我就是检测的窗口消息鼠标中键，alt+左键也是可以的&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月29日(星期二) 下午2:04
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] [Suggestion] 台前調度/專注模式 快速切換模式的功能按鈕 (Issue #766)














 
我寫錯了
 因為筆電觸碰板要使用中鍵比要困難
 我是用軟體去模擬中鍵
 但這個模擬中鍵功能
 好像在你這個功能是失效的

**Comment by linitfor** [comment]
恩恩 理解
