### ISSUE TITLE
多屏卡顿问题

### ISSUE THREAD

**Issue by QLozin** [mydockfinder/mydockfinder#770]
Hi~there
- 我尝试在Issue里检索相关问题, 但似乎没有找到 , [Issue501](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/issues/501) 有谈到类似的问题 , 但问题不大一样

在双屏使用时, 当我屏幕聚焦在另一块屏幕时, 顶栏会重新加载到聚焦屏幕, 每次都会导致整个系统有明显可感知的延迟和卡顿 

能否有一个设置让顶栏固定在一个屏幕上而不是跟随我的焦点反复移动

感谢您的回复 ❤️ .

**Comment by mydockfinder** [comment]
偏好设置&nbsp; myfinder通用里面有选择所显示的屏幕就可以了，可以固定一个屏幕也可以所有屏幕




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月29日(星期二) 晚上9:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 多屏卡顿问题 (Issue #770)














 
Hi~there
  
我尝试在Issue里检索相关问题, 但似乎没有找到 , Issue501 有谈到类似的问题 , 但问题不大一样
  
在双屏使用时, 当我屏幕聚焦在另一块屏幕时, 顶栏会重新加载到聚焦屏幕, 每次都会导致整个系统有明显可感知的延迟和卡顿
 
能否有一个设置让顶栏固定在一个屏幕上而不是跟随我的焦点反复移动
 
感谢您的回复 ❤️ .

**Comment by QLozin** [comment]
非常感谢 , 只需要在设置中选择即可
![图片](https://github.com/user-attachments/assets/c66dd5b5-563e-4d91-b7e0-bba5d9e5b7a3)
