### ISSUE TITLE
[issue] myfinder 顯示其他程式選項異常

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#771]
20241027 更新版本發現
myfinder 顯示其他程式選項異常
他抓到的app 
似乎是上一次使用的視窗程式
而非當下使用的的視窗程式
![圖片](https://github.com/user-attachments/assets/4424a7f4-8a36-4984-8c38-d5e2341879c0)

![圖片](https://github.com/user-attachments/assets/8e3f1fdd-ae29-4c1c-8a04-e19c1a641f2a)

**Comment by mydockfinder** [comment]
再更新一下，后来我又推送了修复这个问题了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月30日(星期三) 凌晨4:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] [issue] myfinder 顯示其他程式選項異常 (Issue #771)














 
20241027 更新版本發現
 myfinder 顯示其他程式選項異常
 他抓到的app
 似乎是上一次使用的視窗程式
 而非當下使用的的視窗程式
 default.png (view on web)
 
default.png (view on web)

**Comment by linitfor** [comment]
感謝 更新完 看起來修復了
