### ISSUE TITLE
[issue]音量快捷鍵 的音量增加鍵 某些情況失效

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#773]
音量快捷鍵 的音量增加鍵

如果起始音量是0 或起始音量是禁音的情況
去使用快捷鍵 按音量增加鍵 是沒辦法增加音量的
這個功能 在20241027 版本之前是正常的
應該是因為增加調整音量增減值後出現的bug

![圖片](https://github.com/user-attachments/assets/7c61a27f-6b02-40e1-a17f-6a0dbb5a90b5)

**Comment by mydockfinder** [comment]
好的&nbsp; 奇怪的bug增加了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月31日(星期四) 晚上10:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] [issue]音量快捷鍵 的音量增加鍵 某些情況失效 (Issue #773)














 
音量快捷鍵 的音量增加鍵
 
如果起始音量是0 或起始音量是禁音的情況
 去使用快捷鍵 按音量增加鍵 是沒辦法增加音量的
 這個功能 在20241027 版本之前是正常的
 應該是因為增加調整音量增減值後出現的bug
 
default.png (view on web)

**Comment by linitfor** [comment]
新版已解決 感謝
