### ISSUE TITLE
通知功能出现问题，仅在开机自启动有一次正常弹出，之后无论怎么发送消息测试都没有弹窗提示

### ISSUE THREAD

**Issue by Godshaos** [mydockfinder/mydockfinder#776]
![PixPin_2024-11-07_22-32-15](https://github.com/user-attachments/assets/fd863e4d-c031-4aa1-88b2-ca70af4bb14c)
![PixPin_2024-11-07_22-37-36](https://github.com/user-attachments/assets/7c1dc9e4-4eae-4a61-995c-13a70e864f50)
![PixPin_2024-11-07_22-37-58](https://github.com/user-attachments/assets/879cf316-37fc-4fa6-891e-5c35e29d1c0b)
没有弹窗，甚至没有接受到新消息的红点提示，新版ntQQ的自带提示一切正常
![PixPin_2024-11-07_22-41-24](https://github.com/user-attachments/assets/5d8fd6dc-2c06-4372-89a5-caf845530092)

**Comment by mydockfinder** [comment]
微信就很正常了，基操，过几天微信更新他能自己好

**Comment by mydockfinder** [comment]
微信就很正常了，基操，过几天微信更新他能自己好




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月7日(星期四) 晚上10:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 通知功能出现问题，仅在开机自启动有一次正常弹出，之后无论怎么发送消息测试都没有弹窗提示 (Issue #776)














 
PixPin_2024-11-07_22-32-15.png (view on web)
 PixPin_2024-11-07_22-37-36.png (view on web)
 PixPin_2024-11-07_22-37-58.png (view on web)
 没有弹窗，甚至没有接受到新消息的红点提示，新版ntQQ的自带提示一切正常
 PixPin_2024-11-07_22-41-24.png (view on web)

**Comment by Godshaos** [comment]
> 微信就很正常了，基操，过几天微信更新他能自己好

ntqq也没有这个软件的通知弹窗

**Comment by mydockfinder** [comment]
不可能 绝对不可能.gif
我天天用啊，不应该啊一直都能显示
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月8日(星期五) 晚上6:59
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 通知功能出现问题，仅在开机自启动有一次正常弹出，之后无论怎么发送消息测试都没有弹窗提示 (Issue #776)














  
微信就很正常了，基操，过几天微信更新他能自己好
  
ntqq也没有这个软件的通知弹窗

**Comment by Godshaos** [comment]
> 不可能 绝对不可能.gif
> 我天天用啊，不应该啊一直都能显示
> &nbsp;
> 
> 
> №じ&nbsp;尐乄鈊~→☆
> ***@***.***
> 
> 
> 
> &nbsp;
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人: ***@***.***&gt;; 
> 发送时间: 2024年11月8日(星期五) 晚上6:59
> 收件人: ***@***.***&gt;; 
> 抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
> 主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 通知功能出现问题，仅在开机自启动有一次正常弹出，之后无论怎么发送消息测试都没有弹窗提示 (Issue #776)
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
>   
> 微信就很正常了，基操，过几天微信更新他能自己好
>   
> ntqq也没有这个软件的通知弹窗
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***&gt;

现在好像又能出弹窗了，现在好了。谢谢，再次打扰了 (´∀`)

**Comment by Yahotong** [comment]
我有也出现了，怎么测试都不行，专注助手也关了，和你的截图一样都开了

**Comment by EdisionJ** [comment]
> 我有也出现了，怎么测试都不行，专注助手也关了，和你的截图一样都开了

<img width="1497" height="675" alt="Image" src="https://github.com/user-attachments/assets/6d40a6c9-58b6-4d52-a145-fea8817ed5e8" />
我关闭这个字设置后就行了

**Comment by mydockfinder** [comment]
微信还是QQ
