### ISSUE TITLE
[issue] edge 媒體播放器在mydock 上進度條更新狀態問題

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#778]
最近Apple podcast 終於有網頁版了，解決windows 聽apple podcast 一定要灌itune
但是發覺 edge 媒體播放器進度條更新狀態
似乎不會即時更新，
進度條的部分，會需要我點選 暫停 or 播放 才會更新下面的進度條
請問這是原本預期的設計嗎? (這樣mydock比較省電?)
還是這是bug ? 是Microsoft edge 問題? 還是 mydock 更新問題?

[Reference]
https://podcasts.apple.com/tw/browse

![image](https://github.com/user-attachments/assets/9f36c776-c0c9-4499-95cd-9bb40b060e7e)

**Comment by mydockfinder** [comment]
是浏览器的事，chrome也是这样，必须手动调节一下，播放暂停或者进度条才会刷新，可能是他们一直没在意过就一直没修

**Comment by linitfor** [comment]
喔喔 了解 ~
