### ISSUE TITLE
删除分隔符后无法打开 Dock 的设置

### ISSUE THREAD

**Issue by Oracynx** [mydockfinder/mydockfinder#782]
尝试重置了配置文件，几个图标仍然挤在一起，无法添加分隔符/添加系统图标

![image](https://github.com/user-attachments/assets/9d31bc71-0792-458e-8c62-7b9aa96bc689)

**Comment by Oracynx** [comment]
右键空隙无法点到，点开的是图标的菜单

**Comment by Oracynx** [comment]
如何完全重置文件呢

**Comment by mydockfinder** [comment]
![image](https://github.com/user-attachments/assets/111f0c8d-8b75-4e08-bf6c-e9fbdcd94db0)
