### ISSUE TITLE
[issue] Mydock 縮小視窗後，icon 上會有機率性出現殘影

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#787]
Mydock 縮小視窗後， dock icon 有時候會殘留 縮小的動畫白影，如下圖
需要滑鼠移動一下，才會消失

![image](https://github.com/user-attachments/assets/412c5b3c-299f-426d-a7c9-432e8f33ad85)

**Comment by mydockfinder** [comment]
这个模糊是系统渲染的，真的没法修。。。。。

**Comment by linitfor** [comment]
ok
