### ISSUE TITLE
i had an issue and a suggestion:

### ISSUE THREAD

**Issue by teddtastic** [mydockfinder/mydockfinder#79]
Issue: when on the desktop, File, Edit, Show, Go To, Windows and Help do not have a dropdown menu.

Suggestion: it would be great if you could include a mac style action centre

**Comment by mydockfinder** [comment]
文件 编辑 那些按钮我还没做功能了，所以现在点击是没有效果的，操作中心后面也会做的不过还是win10才有，win10以下的系统不行了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月18日(星期五) 凌晨0:50
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder] i had an issue and a suggestion: (#79)





 
Issue: when on the desktop, File, Edit, Show, Go To, Windows and Help do not have a dropdown menu.
 
Suggestion: it would be great if you could include a mac style action centre
