### ISSUE TITLE
Constant High CPU Usage 

### ISSUE THREAD

**Issue by elkhaligy** [mydockfinder/mydockfinder#795]
The title, Windows version is 24H2, dock version is 1.10
![image](https://github.com/user-attachments/assets/ff16502d-c619-4ed8-aff0-809fd64890d7)

**Comment by mydockfinder** [comment]
There is no way to solve the problem of the system, because the graphics card drivers are not currently adapted to 24H2

**Comment by elkhaligy** [comment]
> There is no way to solve the problem of the system, because the graphics card drivers are not currently adapted to 24H2

I will update the drivers and report back.

**Comment by elkhaligy** [comment]
Updating drivers fixed the issue, Thanks!
