### ISSUE TITLE
删掉steam后，dock栏的资源管理器图标无法正常显示

### ISSUE THREAD

**Issue by abc2809** [mydockfinder/mydockfinder#798]
版本是1.9.9.7，
在办公室使用，不想登录steam账号，把steam删掉后，正常使用倒是没问题，就是资源管理器的图标显示不对，
在dock栏中资源管理器有占位，但是图标不显示；
![1733478140531](https://github.com/user-attachments/assets/61333735-226d-4711-932f-0393cc9c4751)

如果移除再添加，也获取不到图标，会提示“程序路径和图标不能为空”，如果自定义图标，重启程序后就又不显示了
![QQ_1733478356885](https://github.com/user-attachments/assets/ad6c2382-5c87-4378-9a71-ab080bb9cc66)
![QQ_1733478443905](https://github.com/user-attachments/assets/04cbd715-2735-4b72-9362-165ff45c74a3)

如果打开一个文件夹，把文件夹保留在dock栏中，可以暂时显示，但重启程序后就又不显示了；
![QQ_1733478528634](https://github.com/user-attachments/assets/89f4dc18-1ed7-43fa-ace1-932a310c793c)

题外话：不登录steam的情况下能升级软件吗=。=

**Comment by mydockfinder** [comment]
是程序里面themes文件夹里面的主题图标文件没了，可以在家里的电脑里面dockfinder安装目录复制一份themes整个文件夹就可以了
升级的话就是复制新版本的里面的所有exe和dll那个文件夹就可以了

**Comment by abc2809** [comment]
OK，谢谢。
再问个设置的问题，dock栏的预览窗口的显示逻辑是活跃的窗口总是显示在最前面，但我的习惯是有多个窗口是就按他们固定的位置去操作，有选项可以设置预览窗口的位置固定不变吗？
![QQ_1733711627635](https://github.com/user-attachments/assets/37f7a57e-a9fa-4b2e-b6e9-057bac45e655)
