### ISSUE TITLE
建议优化触摸体验

### ISSUE THREAD

**Issue by h13-0** [mydockfinder/mydockfinder#80]
![Video_20210618_125613_155.gif](https://user-images.githubusercontent.com/61249472/122441294-ffb27f00-cfcf-11eb-9a03-6a449190d3f1.gif)
![Video_20210618_125652_456.gif](https://user-images.githubusercontent.com/61249472/122441399-178a0300-cfd0-11eb-830a-c1144a8ed1bf.gif)

**Comment by h13-0** [comment]
Finder左上角的Apple logo，弹出磁盘这几个是可以正常工作的。
docker用触摸屏就会出问题

**Comment by mydockfinder** [comment]
dock哪些地方有问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月18日(星期五) 凌晨2:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] 建议优化触摸体验 (#80)





 
Finder左上角的Apple logo，弹出磁盘这几个是可以正常工作的。
 docker用触摸屏就会出问题
 
&mdash;

**Comment by h13-0** [comment]
> dock哪些地方有问题
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人: ***@***.***&gt;; 
> 发送时间: 2021年6月18日(星期五) 凌晨2:28
> 收件人: ***@***.***&gt;; 
> 抄送: ***@***.***&gt;; 
> 主题: Re: [mydockfinder/mydockfinder] 建议优化触摸体验 (#80)
> 
> 
> 
> 
> 
>  
> Finder左上角的Apple logo，弹出磁盘这几个是可以正常工作的。
>  docker用触摸屏就会出问题
>  
> &mdash;
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

看p2，从dock点击app进去之后，dock还在不停的显示预览图

**Comment by mydockfinder** [comment]
额  这怪了为什么我的平板触摸点击就没事。。。。

**Comment by mydockfinder** [comment]
为什么你的finder沉浸模式没有渐变动画，是最新版5.9.9.8吗

**Comment by h13-0** [comment]
> 为什么你的finder沉浸模式没有渐变动画，是最新版5.9.9.8吗

是的，我先重启一下平板试试

**Comment by mydockfinder** [comment]
是ARM还是X64系统

**Comment by h13-0** [comment]
> 是ARM还是X64系统

surface Pro 4，x64，21h1

**Comment by h13-0** [comment]
> 为什么你的finder沉浸模式没有渐变动画，是最新版5.9.9.8吗

重启之后dock和Finder的问题和原来一样

**Comment by mydockfinder** [comment]
好吧我尽量




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月18日(星期五) 中午11:54
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] 建议优化触摸体验 (#80)





  
为什么你的finder沉浸模式没有渐变动画，是最新版5.9.9.8吗
  
重启之后dock和Finder的问题和原来一样
 
&mdash;
