### ISSUE TITLE
为什么出现黄色的背景

### ISSUE THREAD

**Issue by Oracynx** [mydockfinder/mydockfinder#808]
![image](https://github.com/user-attachments/assets/f6ae5df1-7e2d-4770-8fb9-548cc26d71f2)
![image](https://github.com/user-attachments/assets/ce6773c4-7199-4128-8937-a3d5e2c00307)
这是因为什么，或者可以怎么解决吗

**Comment by mydockfinder** [comment]
也有人反馈过一样的问题，他是把显卡设置重置就好了

**Comment by Oracynx** [comment]
+1，好了

mydockfinder ***@***.***> 于2024年12月31日周二 18:49写道：
