### ISSUE TITLE
无法正常安装/打开程序

### ISSUE THREAD

**Issue by ljynfo** [mydockfinder/mydockfinder#82]
下载的是5.9.9.8 MyDockFinder.x86-x64.setup.zip 63.3 MB
win10笔记本电脑64位
下载后解压，按照doc文档安装了图形工具、VC2019 64位、使用DirectXRepair_v4.0修复程序后，
点击“Dock.exe”、“Dock_64.exe”、“MyDock.exe” 均无任何反应

**Comment by mydockfinder** [comment]
你要是说“Dock_64.exe”、“MyDock.exe”没反应我还有点办法，dock.exe都没反应我就真没辙了，那个是32位的打开第一件事就是鉴别系统是不是64位，是64位会有弹窗那是最基本的代码，他都没反应我就没辙了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月18日(星期五) 下午3:59
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder] 无法正常安装/打开程序 (#82)





 
下载的是5.9.9.8 MyDockFinder.x86-x64.setup.zip 63.3 MB
 win10笔记本电脑64位
 下载后解压，按照doc文档安装了图形工具、VC2019 64位、使用DirectXRepair_v4.0修复程序后，
 点击“Dock.exe”、“Dock_64.exe”、“MyDock.exe” 均无任何反应
