### ISSUE TITLE
请问如何只把win10的消息提醒改成mac的样式

### ISSUE THREAD

**Issue by ljynfo** [mydockfinder/mydockfinder#86]

**Comment by mydockfinder** [comment]
你是说把微信QQ的消息提示关了吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月19日(星期六) 晚上6:23
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder] 请问如何只把win10的消息提醒改成mac的样式 (#86)

**Comment by ljynfo** [comment]
因为我安装后，没办法彻底的隐藏win10的任务栏，有消息时任务栏也会弹出来， 请问能不能彻底隐藏win的任务栏呢？

**Comment by mydockfinder** [comment]
dock设置里有启动时隐藏任务栏 dock分隔符右键也可以隐藏任务栏




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月19日(星期六) 晚上6:59
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] 请问如何只把win10的消息提醒改成mac的样式 (#86)





 
因为我安装后，没办法彻底的隐藏win10的任务栏，有消息时任务栏也会弹出来， 请问能不能彻底隐藏win的任务栏呢？

**Comment by YuizhiCode** [comment]
可以设置隐藏任务栏 在偏好设置里面

**Comment by ljynfo** [comment]
在连接外显示器情况下，任务栏经常自动弹出，多显示器体验效果不是很好
还有个很严重的问题，偏好设置更改设置无法保存、设置无法更新

**Comment by mydockfinder** [comment]
设置里面有人隐藏任务栏选项 选择隐藏所有屏幕任务栏，而且系统设置也可以设置只在第一屏显示任务栏，看一下dock目录的config.ini文件是不是只读了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月21日(星期一) 上午9:54
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] 请问如何只把win10的消息提醒改成mac的样式 (#86)





 
在连接外显示器情况下，任务栏经常自动弹出，多显示器体验效果不是很好
 还有个很严重的问题，偏好设置更改设置无法保存、设置无法更新
 
&mdash;
