### ISSUE TITLE
托盘这里不能自定义吗？

### ISSUE THREAD

**Issue by exkings** [mydockfinder/mydockfinder#87]
![image](https://user-images.githubusercontent.com/20751565/122650952-489d3b80-d168-11eb-81e6-3c3e34b88794.png)
比如说拖动位置，或者让某个应用从托盘中移出放到finder上？

**Comment by mydockfinder** [comment]
点左边圆形按钮




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月20日(星期天) 凌晨1:45
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder] 托盘这里不能自定义吗？ (#87)





 

 比如说拖动位置，或者让某个应用从托盘中移出放到finder上？
