### ISSUE TITLE
Win10最新release版本报毒

### ISSUE THREAD

**Issue by gingerZone27** [mydockfinder/mydockfinder#92]
Win10最新release版本报毒

**Comment by mydockfinder** [comment]
个人软件都这样，大厂的软件天天监视你的文件和浏览器历史记录也不会报毒，主要没交保护费




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月20日(星期天) 晚上10:00
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder] Win10最新release版本报毒 (#92)





 
Win10最新release版本报毒
