### ISSUE TITLE
Microsoft Text Input Application show 

### ISSUE THREAD

**Issue by giri-w** [mydockfinder/mydockfinder#93]
![image](https://user-images.githubusercontent.com/23527442/122690219-85306c00-d228-11eb-97c9-58c57fdee038.png)

This app is not in the active program but keeps appearing in the dock. It cannot be closed too.

**Comment by mydockfinder** [comment]
图标 右键菜单&nbsp; “不再显示此程序图标”&nbsp; &nbsp; &nbsp;“never show”




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月21日(星期一) 上午6:36
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder] Microsoft Text Input Application show  (#93)





 

 
This app is not in the active program but keeps appearing in the dock. It cannot be closed too.

**Comment by giri-w** [comment]
Thank you for the tips. It solves the issues.
