### ISSUE TITLE
cache.ico  这个是文件夹的图标缓存吗？

### ISSUE THREAD

**Issue by db-one** [mydockfinder/mydockfinder#96]
cache.ico  这个是文件夹的图标缓存吗？
这个每次dock关闭之后会删除，启动之后会重新建立
启动台基本没问题了，就是这个文件夹的每次重新启动电脑，首次运行还是要重新缓存不少时间
![image](https://user-images.githubusercontent.com/20243226/122870419-3b4aa180-d360-11eb-99d3-fbacd1517991.png)

**Comment by db-one** [comment]
![image](https://user-images.githubusercontent.com/20243226/122870499-4f8e9e80-d360-11eb-91c0-80e4d30a10b9.png)
运行状态下是有这个缓存文件夹的
![image](https://user-images.githubusercontent.com/20243226/122870528-5ae1ca00-d360-11eb-9446-eb8e8104bc78.png)
退出之后就自动删除了

**Comment by mydockfinder** [comment]
那是dock运行以后dock上的图标缓存，不缓存磁盘上在内存里面如果有清理内存的软件容易出错




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月22日(星期二) 中午1:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] cache.ico  这个是文件夹的图标缓存吗？ (#96)





 

 运行状态下是有这个缓存文件夹的
 
 退出之后就自动删除了
 
&mdash;

**Comment by db-one** [comment]
哦  那文件夹是的哪个缓存的，那个重新启动系统还是会读取很缓慢，启动台是正常的，缓存有效，基本可以秒开

**Comment by mydockfinder** [comment]
cache.ico 是运行以后dock上的图标缓存，并不是获取的缓存，dock是GPU渲染的都在显存里面取不出来，所以要有一个本地的缓存，防止显卡出错




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月22日(星期二) 下午2:19
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] cache.ico  这个是文件夹的图标缓存吗？ (#96)





 
哦  那文件夹是的哪个缓存的，那个重新启动系统还是会读取很缓慢，启动台是正常的，缓存有效，基本可以秒开

**Comment by db-one** [comment]
![image](https://user-images.githubusercontent.com/20243226/122874321-74394500-d365-11eb-9a35-ccc0edc1db97.png)
、那像是这种文件夹大量图标的，读取速度慢，暂时没有办法是吧
![image](https://user-images.githubusercontent.com/20243226/122874448-9632c780-d365-11eb-9ecc-a35cc26cf54c.png)

**Comment by mydockfinder** [comment]
这个不是缓存的问题，因为文件夹里面的图标尺寸显示的小，渲染的时候要不损失图标质量情况下缩小图标，渲染会有延迟




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月22日(星期二) 下午2:25
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] cache.ico  这个是文件夹的图标缓存吗？ (#96)





 

 、那像是这种文件夹大量图标的，读取速度慢，暂时没有办法是吧
 
 
&mdash;

**Comment by db-one** [comment]
好的，明白了，非常感谢

**Comment by mydockfinder** [comment]
没事




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月22日(星期二) 下午2:30
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] cache.ico  这个是文件夹的图标缓存吗？ (#96)





 
好的，明白了，非常感谢
 
&mdash;

**Comment by db-one** [comment]
只不过这个暂时确实影响体验，希望以后可以有好的解决方法，主要我图标多，懒得分组，哈哈，要是真没办法，就忽略这个问题吧

**Comment by mydockfinder** [comment]
我之前测试过，其实现在图标都是缓存的，创建一个图标很快的，就是渲染的时候慢，所以我才想为什么mac都是 128 256尺寸渲染了可能是为了速度




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月22日(星期二) 下午2:34
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] cache.ico  这个是文件夹的图标缓存吗？ (#96)





 
只不过这个暂时确实影响体验，希望以后可以有好的解决方法，主要我图标多，懒得分组，哈哈，要是真没办法，就忽略这个问题吧
 
&mdash;

**Comment by db-one** [comment]
嗯 那就只能先不管他了

**Comment by db-one** [comment]
另外最新5.9.9.85版本，开启使用GPU渲染，会不出现DOCK栏，看到有进程，但是没有dock界面，恢复到上一版本，或者关闭GPU渲染之后正常

**Comment by db-one** [comment]
不知道其他人有没有这个问题

**Comment by mydockfinder** [comment]
嗯&nbsp; 我现在就是在修复这个问题，出现问题可以最大化一个窗口，然后取消最大化他就会自己出来了，如果不出来重复两次，其实不是没出来，是已经出来了只不过没渲染而已看不见，GPU渲染机制不太一样，我没玩熟




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月22日(星期二) 下午3:24
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] cache.ico  这个是文件夹的图标缓存吗？ (#96)





 
不知道其他人有没有这个问题
 
&mdash;

**Comment by db-one** [comment]
嗯 好的  我暂时先关闭GPU渲染了  等下一个版本

**Comment by mydockfinder** [comment]
嗯 我争取下个版本修好




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月22日(星期二) 下午3:29
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] cache.ico  这个是文件夹的图标缓存吗？ (#96)





 
嗯 好的  我暂时先关闭GPU渲染了  等下一个版本
 
&mdash;
