### ISSUE TITLE
激活托盘占用CPU问题

### ISSUE THREAD

**Issue by zpengcom** [mydockfinder/mydockfinder#98]
![23-06-2021 11-27-34](https://user-images.githubusercontent.com/8217132/123031247-976ffd00-d416-11eb-85e5-63189319dc66.png)
激活托盘后 进程不会结束，而且会重复叠加 如图

**Comment by mydockfinder** [comment]
这个真的没有遇到过，激活托盘就一句命令然后就会自动退出，任务管理器里面的激活托盘都退出，然后删除dock目录的trayico.exe，还有是不是360提示拦截了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月23日(星期三) 中午11:32
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder] 激活托盘占用CPU问题 (#98)





 

 激活托盘后 进程不会结束，而且会重复叠加 如图

**Comment by zpengcom** [comment]
> 这个真的没有遇到过，激活托盘就一句命令然后就会自动退出，任务管理器里面的激活托盘都退出，然后删除dock目录的trayico.exe，还有是不是360提示拦截了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mydockfinder/mydockfinder" ***@***.***&gt;; 发送时间:&nbsp;2021年6月23日(星期三) 中午11:32 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[mydockfinder/mydockfinder] 激活托盘占用CPU问题 (#98) 激活托盘后 进程不会结束，而且会重复叠加 如图 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
